/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Execution.StoppedExecution
import EconCSLib.GameTheory.ExtensiveGame.Observed.Controlled

/-!
# Payoff-free controlled execution infrastructure

`ControlledObservedGame` helpers for no-chance mover recovery and pure-profile
history execution. General well-formedness, subgames, finite certificates,
quasistrategies, recall, objectives, and winning predicates are owned by
separate modules.
-/

namespace ExtensiveGame.ControlledObservedGame

variable {N : Type*} {G : ControlledObservedGame N}

/-! ## No-chance pure-profile execution -/

/-- The mover option at a nonterminal history is inhabited in a no-chance
payoff-free game. -/
def moverIsSome (hNoChance : G.base.NoChanceOnHistories)
    (history : G.base.History)
    (hnonterminal : ¬ G.base.isTerminal history.1) :
    (G.base.mover history.1).isSome = true :=
  Option.isSome_iff_exists.mpr
    (hNoChance history hnonterminal)

/-- The player controlling a nonterminal history in a no-chance payoff-free
game. -/
def playerAt (hNoChance : G.base.NoChanceOnHistories)
    (history : G.base.History)
    (hnonterminal : ¬ G.base.isTerminal history.1) : N :=
  (G.base.mover history.1).get
    (G.moverIsSome hNoChance history hnonterminal)

/-- `playerAt` recovers the mover stored by the controlled game. -/
theorem mover_playerAt (hNoChance : G.base.NoChanceOnHistories)
    (history : G.base.History)
    (hnonterminal : ¬ G.base.isTerminal history.1) :
    G.base.mover history.1 =
      some (G.playerAt hNoChance history hnonterminal) :=
  (Option.some_get
    (G.moverIsSome hNoChance history hnonterminal)).symm

/-- Convert a payoff-free pure profile into a terminal-aware history policy
when every nonterminal node has a strategic mover. -/
def PureProfile.toHistoryPolicy
    (profile : G.PureProfile)
    (hNoChance : G.base.NoChanceOnHistories) :
    G.base.toArena.HistoryPolicy G.base.init :=
  fun history hnonterminal =>
    (profile (G.playerAt hNoChance history hnonterminal)).actionAt
      G history
      (G.mover_playerAt hNoChance history hnonterminal)
      hnonterminal

/-- At a player-controlled history, payoff-free profile execution uses that
player's component strategy. -/
theorem PureProfile.toHistoryPolicy_of_mover
    (profile : G.PureProfile)
    (hNoChance : G.base.NoChanceOnHistories)
    (history : G.base.History)
    (hnonterminal : ¬ G.base.isTerminal history.1)
    (i : N)
    (hmover : G.base.mover history.1 = some i) :
    profile.toHistoryPolicy hNoChance history hnonterminal =
      (profile i).actionAt G history hmover hnonterminal := by
  have hplayer :
      G.playerAt hNoChance history hnonterminal = i := by
    apply Option.some.inj
    rw [← hmover]
    exact
      (G.mover_playerAt
        hNoChance history hnonterminal).symm
  subst i
  rfl

/-- A complete play is locally compatible with one payoff-free pure strategy
when every coordinate controlled by that player takes its prescribed concrete
action. Opponent and nature coordinates remain unconstrained. -/
def IsCompatibleWithPlayerStrategyFrom
    {current : G.base.History}
    (i : N) (strategy : G.PureStrategy i)
    (play : G.base.CompletePlayFromHistory current) : Prop :=
  ∀ (n : ℕ)
    (hnonterminal :
      ¬ G.base.isTerminal (play.historyAt n).1)
    (hmover :
      G.base.mover (play.historyAt n).1 = some i),
    play.historyAt (n + 1) =
      ⟨G.base.next (play.historyAt n).1
          (strategy.actionAt G (play.historyAt n) hmover hnonterminal),
        (play.historyAt n).2.snoc
          (strategy.actionAt G (play.historyAt n) hmover hnonterminal)⟩

/-- Root-started local compatibility in a payoff-free observed game. -/
abbrev IsCompatibleWithPlayerStrategy
    (G : ControlledObservedGame N) (i : N)
    (strategy : G.PureStrategy i)
    (play : G.base.CompletePlay) : Prop :=
  G.IsCompatibleWithPlayerStrategyFrom i strategy play

/-- The complete play generated by a no-chance payoff-free pure profile is
compatible with every component strategy. -/
theorem PureProfile.completePlay_isCompatibleWithPlayerStrategy
    [(state : G.base.State) →
      Decidable (G.base.isTerminal state)]
    (profile : G.PureProfile)
    (hNoChance : G.base.NoChanceOnHistories) (i : N) :
    G.IsCompatibleWithPlayerStrategy i (profile i)
      ((profile.toHistoryPolicy hNoChance).completePlay) := by
  intro n hnonterminal hmover
  change
    Arena.stoppedHistory
        (profile.toHistoryPolicy hNoChance) (n + 1) =
      ⟨G.base.next
          (Arena.stoppedHistory
            (profile.toHistoryPolicy hNoChance) n).1
          ((profile i).actionAt G
            (Arena.stoppedHistory
              (profile.toHistoryPolicy hNoChance) n)
            hmover hnonterminal),
        (Arena.stoppedHistory
            (profile.toHistoryPolicy hNoChance) n).2.snoc
          ((profile i).actionAt G
            (Arena.stoppedHistory
              (profile.toHistoryPolicy hNoChance) n)
            hmover hnonterminal)⟩
  rw [Arena.stoppedHistory,
    Arena.stoppedHistoryFrom_add
      (profile.toHistoryPolicy hNoChance)
      (Arena.HistoryFrom.nil
        G.base.toArena G.base.init) n 1]
  rw [Arena.stoppedHistoryFrom_succ_of_not_terminal
    (profile.toHistoryPolicy hNoChance)
    (Arena.stoppedHistoryFrom
      (profile.toHistoryPolicy hNoChance)
      (Arena.HistoryFrom.nil
        G.base.toArena G.base.init) n)
    0 hnonterminal]
  rw [Arena.stoppedHistoryFrom_zero]
  simp only [Arena.stoppedHistory]
  have haction :
      profile.toHistoryPolicy hNoChance
          (Arena.stoppedHistoryFrom
            (profile.toHistoryPolicy hNoChance)
            (Arena.HistoryFrom.nil
              G.base.toArena G.base.init) n)
          hnonterminal =
        (profile i).actionAt G
          (Arena.stoppedHistoryFrom
            (profile.toHistoryPolicy hNoChance)
            (Arena.HistoryFrom.nil
              G.base.toArena G.base.init) n)
          hmover hnonterminal :=
    profile.toHistoryPolicy_of_mover
      hNoChance _ hnonterminal i hmover
  rw [haction]

end ExtensiveGame.ControlledObservedGame
