/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.Examples.ExtensiveGame.FiniteLawIntegral
import EconCSLib.GameTheory.ExtensiveGame.Simulation.Kernel.EventPath

/-!
# Strict event-history measurable-policy boundary

A one-state discrete measurable-kernel arena with two actions that both loop
to the same state. Its event-history policy repeats the action occurrence
stored in the latest event. Consequently, two event prefixes with identical
state projections receive different deterministic action laws.

The reverse theorem proves that no `HistoryActionPolicy`, embedded through
`toEventHistoryActionPolicy`, agrees with this policy on every event prefix.
This is an interface-expressiveness regression over complete prefix inputs;
it does not claim that both hand-written witness prefixes are generated by
the particular deterministic time-zero branch of this policy.

`transitionLaw`, `actionLaw`, and `stepLaw` execute the same operations with
finite rational laws. Their kernel equalities and `stepLaw_eventMass` identify
the computed output with the original analytic executor on every prefix.
-/

open MeasureTheory ProbabilityTheory

namespace EconCSLib.Examples.ExtensiveGame.EventHistoryKernelBoundary

/-- A one-state analytic arena with two actions, neither of which changes the
state. -/
noncomputable def eventArena : MeasurableKernelArena where
  State := Unit
  Action := fun _ => Bool
  stateMeasurable := ⊤
  actionBundleMeasurable := ⊤
  stateProjection_measurable := by
    change
      @Measurable (Σ _state : Unit, Bool) Unit
        ⊤ ⊤ Sigma.fst
    exact fun _ _ => MeasurableSpace.measurableSet_top
  transition :=
    @Kernel.deterministic
      (Σ _state : Unit, Bool) Unit ⊤ ⊤
      (fun _ => ())
      (fun _ _ => MeasurableSpace.measurableSet_top)
  transition_isMarkov := by
    infer_instance

instance eventArena_stateSubsingleton :
    Subsingleton eventArena.State := by
  change Subsingleton Unit
  infer_instance

instance eventArena_actionBundleFintype :
    Fintype eventArena.ActionBundle := by
  change Fintype (Σ _state : Unit, Bool)
  infer_instance

instance eventArena_actionBundleMeasurableSingleton :
    MeasurableSingletonClass eventArena.ActionBundle where
  measurableSet_singleton _ :=
    MeasurableSpace.measurableSet_top

instance eventArena_optionalActionMeasurableSingleton :
    MeasurableSingletonClass
      (Unit ⊕ eventArena.ActionBundle) where
  measurableSet_singleton action := by
    cases action with
    | inl noAction =>
        simpa only [Set.image_singleton] using
          (MeasurableSet.inl_image
            (measurableSet_singleton noAction))
    | inr stateAction =>
        simpa only [Set.image_singleton] using
          (MeasurableSet.inr_image
            (measurableSet_singleton stateAction))

instance eventArena_pathEventFintype :
    Fintype eventArena.PathEvent := by
  change Fintype (Unit × (Unit ⊕ (Σ _state : Unit, Bool)))
  infer_instance

instance eventArena_pathEventMeasurableSingleton :
    MeasurableSingletonClass eventArena.PathEvent := by
  infer_instance

/-- Read the latest recorded action, using `false` when the event has no
incoming action occurrence. -/
def rememberedAction (time : ℕ)
    (history : Π index : Finset.Iic time,
      MeasurableKernelArena.EventAt eventArena index) :
    Bool :=
  match (history ⟨time, Finset.mem_Iic.mpr le_rfl⟩).2 with
  | Sum.inl _ => false
  | Sum.inr stateAction => stateAction.2

/-- An event-history policy that repeats the latest recorded action. -/
noncomputable def eventPolicy : eventArena.EventHistoryActionPolicy where
  kernel := fun time =>
    Kernel.deterministic
      (fun history =>
        (⟨MeasurableKernelArena.latestEventState time history,
          rememberedAction time history⟩ :
          eventArena.ActionBundle))
      (measurable_of_finite _)
  terminal_zero := by
    intro time history hterminal
    exact (hterminal.false false).elim
  nonterminal_isProbability := by
    intro _ _ _
    infer_instance
  legal := by
    intro time history _
    rw [Kernel.deterministic_apply]
    simp [MeasurableKernelArena.actionFiber]

@[simp]
theorem eventPolicy_kernel_apply
    (time : ℕ)
    (history : Π index : Finset.Iic time,
      MeasurableKernelArena.EventAt eventArena index) :
    eventPolicy.kernel time history =
      Measure.dirac
        (⟨MeasurableKernelArena.latestEventState time history,
          rememberedAction time history⟩ :
          eventArena.ActionBundle) := by
  exact Kernel.deterministic_apply
    (measurable_of_finite _) history

/-- A length-one event prefix whose recorded action occurrence is `false`. -/
def falseActionPrefix :
    Π _index : Finset.Iic 1, eventArena.PathEvent :=
  fun index =>
    if index.1 = 0 then
      ((), Sum.inl ())
    else
      ((), Sum.inr (⟨(), false⟩ : eventArena.ActionBundle))

/-- A length-one event prefix whose recorded action occurrence is `true`. -/
def trueActionPrefix :
    Π _index : Finset.Iic 1, eventArena.PathEvent :=
  fun index =>
    if index.1 = 0 then
      ((), Sum.inl ())
    else
      ((), Sum.inr (⟨(), true⟩ : eventArena.ActionBundle))

-- Runtime regression: identical state prefixes retain different action occurrences.
example : rememberedAction 1 falseActionPrefix = false ∧
    rememberedAction 1 trueActionPrefix = true := by
  exact ⟨rfl, rfl⟩

/-- The two event witnesses have exactly the same complete state prefix. -/
theorem eventPrefixStates_witness_eq :
    MeasurableKernelArena.eventPrefixStates 1 falseActionPrefix =
      MeasurableKernelArena.eventPrefixStates 1 trueActionPrefix := by
  funext index
  exact Subsingleton.elim _ _

@[simp]
theorem latestEventState_falseActionPrefix :
    MeasurableKernelArena.latestEventState 1 falseActionPrefix = () := by
  rfl

@[simp]
theorem latestEventState_trueActionPrefix :
    MeasurableKernelArena.latestEventState 1 trueActionPrefix = () := by
  rfl

@[simp]
theorem rememberedAction_falseActionPrefix :
    rememberedAction 1 falseActionPrefix = false := by
  rfl

@[simp]
theorem rememberedAction_trueActionPrefix :
    rememberedAction 1 trueActionPrefix = true := by
  rfl

/-- Despite identical state projections, the witnesses carry distinct latest
action occurrences. -/
theorem latestAction_witness_ne :
    (MeasurableKernelArena.latestEvent 1 falseActionPrefix).action ≠
      (MeasurableKernelArena.latestEvent 1 trueActionPrefix).action := by
  simp [MeasurableKernelArena.latestEvent,
    falseActionPrefix, trueActionPrefix,
    MeasurableKernelArena.PathEvent.action]

/-- No finite-state-prefix policy agrees with `eventPolicy` on every complete
event prefix. The state-only embedding must identify the two witness inputs,
whereas `eventPolicy` assigns different Dirac action laws. -/
theorem no_state_history_policy_representation :
    ¬ ∃ statePolicy : eventArena.HistoryActionPolicy,
      ∀ time history,
        statePolicy.toEventHistoryActionPolicy.kernel time history =
          eventPolicy.kernel time history := by
  rintro ⟨statePolicy, hagree⟩
  have hfalse := hagree 1 falseActionPrefix
  have htrue := hagree 1 trueActionPrefix
  have hembedded :
      statePolicy.toEventHistoryActionPolicy.kernel
          1 falseActionPrefix =
        statePolicy.toEventHistoryActionPolicy.kernel
          1 trueActionPrefix := by
    rw [
      MeasurableKernelArena.HistoryActionPolicy.toEventHistoryActionPolicy_kernel_apply,
      MeasurableKernelArena.HistoryActionPolicy.toEventHistoryActionPolicy_kernel_apply,
      eventPrefixStates_witness_eq]
  have hdirac :
      Measure.dirac
          (⟨(), false⟩ : eventArena.ActionBundle) =
        Measure.dirac
          (⟨(), true⟩ : eventArena.ActionBundle) := by
    rw [eventPolicy_kernel_apply] at hfalse htrue
    simpa using hfalse.symm.trans (hembedded.trans htrue)
  have hsingleton :
      MeasurableSet
        ({(⟨(), false⟩ : eventArena.ActionBundle)} :
          Set eventArena.ActionBundle) := by
    change
      @MeasurableSet eventArena.ActionBundle ⊤
        {(⟨(), false⟩ : eventArena.ActionBundle)}
    exact MeasurableSpace.measurableSet_top
  have happly := congrArg
    (fun measure : Measure eventArena.ActionBundle =>
      measure {(⟨(), false⟩ : eventArena.ActionBundle)})
    hdirac
  change
    Measure.dirac
        (⟨(), false⟩ : eventArena.ActionBundle)
        {(⟨(), false⟩ : eventArena.ActionBundle)} =
      Measure.dirac
        (⟨(), true⟩ : eventArena.ActionBundle)
        {(⟨(), false⟩ : eventArena.ActionBundle)}
    at happly
  rw [Measure.dirac_apply' _ hsingleton,
    Measure.dirac_apply' _ hsingleton] at happly
  simp at happly

section FiniteExecution

local notation "μ[" atoms "]" =>
  List.foldr (fun (atom : _ × ℚ≥0) rest =>
    ((Prod.snd atom : ℚ≥0) : ENNReal) • Measure.dirac (Prod.fst atom) + rest) 0 atoms

local instance : MeasurableSpace Unit := ⊤
local instance : MeasurableSpace eventArena.ActionBundle := ⊤

/-- Executable successor law of the original looping transition. -/
def transitionLaw (_bundle : eventArena.ActionBundle) : FiniteLaw eventArena.State :=
  FiniteLaw.pure ()

/-- Exact action law retaining the recorded action in the complete prefix. -/
def actionLaw (time : ℕ) (history : Π _index : Finset.Iic time, eventArena.PathEvent) :
    FiniteLaw eventArena.ActionBundle :=
  FiniteLaw.pure ⟨(history ⟨time, Finset.mem_Iic.mpr le_rfl⟩).1,
    rememberedAction time history⟩

/-- Execute action selection and transition while recording the selected
action occurrence in the next event. -/
def stepLaw (time : ℕ) (history : Π _index : Finset.Iic time, eventArena.PathEvent) :
    FiniteLaw eventArena.PathEvent :=
  (actionLaw time history).bind fun bundle =>
    (transitionLaw bundle).map fun next => (next, Sum.inr bundle)

/-- The computed finite transition denotes the original analytic kernel. -/
theorem transitionLaw_eq_kernel (bundle : eventArena.ActionBundle) :
    μ[(transitionLaw bundle).atoms] = eventArena.transition bundle := by
  simp only [transitionLaw, FiniteLaw.pure_atoms, List.foldr_cons, List.foldr_nil]
  rw [show ((1 : ℚ≥0) : ENNReal) = 1 by
    change (((1 : ℚ≥0) : NNReal) : ENNReal) = 1
    norm_num, one_smul, add_zero]
  rfl

/-- The computed action law denotes the original event-history policy. -/
theorem actionLaw_eq_kernel (time : ℕ) (history : Π _index : Finset.Iic time, eventArena.PathEvent) :
    μ[(actionLaw time history).atoms] = eventPolicy.kernel time history := by
  simp [actionLaw, FiniteLaw.pure_atoms, eventPolicy_kernel_apply, ← ENNReal.coe_nnratCast]
  rfl

/-- The computed next-event law denotes the original analytic path step. -/
theorem stepLaw_eq_kernel (hterminal : MeasurableSet eventArena.terminalSet)
    (time : ℕ) (history : Π _index : Finset.Iic time, eventArena.PathEvent) :
    μ[(stepLaw time history).atoms] = eventPolicy.pathStepKernel hterminal time history := by
  rw [MeasurableKernelArena.EventHistoryActionPolicy.pathStepKernel_apply_nonterminal
    _ hterminal _ _ (fun hempty => hempty.false false)]
  rw [eventPolicy_kernel_apply, Measure.dirac_bind eventArena.recordedTransition.measurable]
  simp only [stepLaw, actionLaw, transitionLaw, FiniteLaw.pure_bind, FiniteLaw.pure_map,
    FiniteLaw.pure_atoms, List.foldr_cons, List.foldr_nil]
  rw [show ((1 : ℚ≥0) : ENNReal) = 1 by
    change (((1 : ℚ≥0) : NNReal) : ENNReal) = 1
    norm_num]
  rw [one_smul, add_zero]
  rw [MeasurableKernelArena.recordedTransition, Kernel.map_apply _ (by fun_prop)]
  rw [Kernel.prod_apply, Kernel.id_apply]
  change _ = ((Measure.dirac _).prod (Measure.dirac ())).map _
  rw [Measure.dirac_prod_dirac, Measure.map_dirac']
  · rfl
  · fun_prop

/-- Any Boolean event on the recorded next event has exactly its computed
finite-law mass under the original analytic executor. -/
theorem stepLaw_eventMass (hterminal : MeasurableSet eventArena.terminalSet)
    (time : ℕ) (history : Π _index : Finset.Iic time, eventArena.PathEvent)
    (test : eventArena.PathEvent → Bool) :
    eventPolicy.pathStepKernel hterminal time history {x | test x} =
      ((stepLaw time history).eventMass test : ENNReal) := by
  rw [← stepLaw_eq_kernel]
  exact _root_.Examples.ExtensiveGame.FiniteLawIntegral.measure_eventMass _ _
    (by
      letI : MeasurableSingletonClass eventArena.PathEvent :=
        eventArena_pathEventMeasurableSingleton
      exact (Set.toFinite _).measurableSet)

/-- Observe whether the next event records a true action. -/
def recordsTrue (next : eventArena.PathEvent) : Bool :=
  match next.2 with
  | Sum.inl _ => false
  | Sum.inr bundle => bundle.2

/-- Identical state prefixes yield different computed recorded-action laws. -/
theorem stepLaw_regression :
    (stepLaw 1 falseActionPrefix).eventMass recordsTrue = 0 ∧
    (stepLaw 1 trueActionPrefix).eventMass recordsTrue = 1 := by
  norm_num [stepLaw, actionLaw, transitionLaw, FiniteLaw.pure_bind, FiniteLaw.pure_map,
    FiniteLaw.eventMass, FiniteLaw.pure_atoms, recordsTrue, falseActionPrefix,
    trueActionPrefix, rememberedAction]

#eval show IO Unit from do
  unless (stepLaw 1 falseActionPrefix).eventMass recordsTrue == 0 &&
      (stepLaw 1 trueActionPrefix).eventMass recordsTrue == 1 do
    throw (IO.userError "event-history finite execution regression")

end FiniteExecution

end EconCSLib.Examples.ExtensiveGame.EventHistoryKernelBoundary
