/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Simulation.Kernel.EventPath

/-!
# Strict event-history measurable-policy boundary

A one-state discrete measurable-kernel arena with two actions that both loop
to the same state. Its event-history policy repeats the action occurrence
stored in the latest event. Consequently, two event prefixes with identical
state projections receive different deterministic action laws.

The reverse theorem proves that no `HistoryActionPolicy`, embedded through
`toEventHistoryActionPolicy`, agrees with this policy on every event prefix.
This is an interface-expressiveness regression over complete prefix inputs;
it does not claim that both hand-written witness prefixes are generated by
the particular deterministic time-zero branch of this policy.
-/

open MeasureTheory ProbabilityTheory

namespace EconCSLib.Examples.ExtensiveGame.EventHistoryKernelBoundary

/-- A one-state analytic arena with two actions, neither of which changes the
state. -/
noncomputable def eventArena : MeasurableKernelArena where
  State := Unit
  Action := fun _ => Bool
  stateMeasurable := ⊤
  actionBundleMeasurable := ⊤
  stateProjection_measurable := by
    change
      @Measurable (Σ _state : Unit, Bool) Unit
        ⊤ ⊤ Sigma.fst
    exact fun _ _ => MeasurableSpace.measurableSet_top
  transition :=
    @Kernel.deterministic
      (Σ _state : Unit, Bool) Unit ⊤ ⊤
      (fun _ => ())
      (fun _ _ => MeasurableSpace.measurableSet_top)
  transition_isMarkov := by
    infer_instance

noncomputable instance eventArena_stateSubsingleton :
    Subsingleton eventArena.State := by
  change Subsingleton Unit
  infer_instance

noncomputable instance eventArena_actionBundleFintype :
    Fintype eventArena.ActionBundle := by
  change Fintype (Σ _state : Unit, Bool)
  infer_instance

instance eventArena_actionBundleMeasurableSingleton :
    MeasurableSingletonClass eventArena.ActionBundle where
  measurableSet_singleton _ :=
    MeasurableSpace.measurableSet_top

instance eventArena_optionalActionMeasurableSingleton :
    MeasurableSingletonClass
      (Unit ⊕ eventArena.ActionBundle) where
  measurableSet_singleton action := by
    cases action with
    | inl noAction =>
        simpa only [Set.image_singleton] using
          (MeasurableSet.inl_image
            (measurableSet_singleton noAction))
    | inr stateAction =>
        simpa only [Set.image_singleton] using
          (MeasurableSet.inr_image
            (measurableSet_singleton stateAction))

noncomputable instance eventArena_pathEventFintype :
    Fintype eventArena.PathEvent := by
  change Fintype (Unit × (Unit ⊕ (Σ _state : Unit, Bool)))
  infer_instance

instance eventArena_pathEventMeasurableSingleton :
    MeasurableSingletonClass eventArena.PathEvent := by
  infer_instance

/-- Read the latest recorded action, using `false` when the event has no
incoming action occurrence. -/
noncomputable def rememberedAction (time : ℕ)
    (history : Π index : Finset.Iic time,
      MeasurableKernelArena.EventAt eventArena index) :
    Bool :=
  match (MeasurableKernelArena.latestEvent time history).action with
  | Sum.inl _ => false
  | Sum.inr stateAction => stateAction.2

/-- An event-history policy that repeats the latest recorded action. -/
noncomputable def eventPolicy : eventArena.EventHistoryActionPolicy where
  kernel := fun time =>
    Kernel.deterministic
      (fun history =>
        (⟨MeasurableKernelArena.latestEventState time history,
          rememberedAction time history⟩ :
          eventArena.ActionBundle))
      (measurable_of_finite _)
  terminal_zero := by
    intro time history hterminal
    exact (hterminal.false false).elim
  nonterminal_isProbability := by
    intro _ _ _
    infer_instance
  legal := by
    intro time history _
    rw [Kernel.deterministic_apply]
    simp [MeasurableKernelArena.actionFiber]

@[simp]
theorem eventPolicy_kernel_apply
    (time : ℕ)
    (history : Π index : Finset.Iic time,
      MeasurableKernelArena.EventAt eventArena index) :
    eventPolicy.kernel time history =
      Measure.dirac
        (⟨MeasurableKernelArena.latestEventState time history,
          rememberedAction time history⟩ :
          eventArena.ActionBundle) := by
  exact Kernel.deterministic_apply
    (measurable_of_finite _) history

/-- A length-one event prefix whose recorded action occurrence is `false`. -/
noncomputable def falseActionPrefix :
    Π _index : Finset.Iic 1, eventArena.PathEvent :=
  fun index =>
    if index.1 = 0 then
      eventArena.initialEvent ()
    else
      ((), Sum.inr (⟨(), false⟩ : eventArena.ActionBundle))

/-- A length-one event prefix whose recorded action occurrence is `true`. -/
noncomputable def trueActionPrefix :
    Π _index : Finset.Iic 1, eventArena.PathEvent :=
  fun index =>
    if index.1 = 0 then
      eventArena.initialEvent ()
    else
      ((), Sum.inr (⟨(), true⟩ : eventArena.ActionBundle))

/-- The two event witnesses have exactly the same complete state prefix. -/
theorem eventPrefixStates_witness_eq :
    MeasurableKernelArena.eventPrefixStates 1 falseActionPrefix =
      MeasurableKernelArena.eventPrefixStates 1 trueActionPrefix := by
  funext index
  exact Subsingleton.elim _ _

@[simp]
theorem latestEventState_falseActionPrefix :
    MeasurableKernelArena.latestEventState 1 falseActionPrefix = () := by
  rfl

@[simp]
theorem latestEventState_trueActionPrefix :
    MeasurableKernelArena.latestEventState 1 trueActionPrefix = () := by
  rfl

@[simp]
theorem rememberedAction_falseActionPrefix :
    rememberedAction 1 falseActionPrefix = false := by
  rfl

@[simp]
theorem rememberedAction_trueActionPrefix :
    rememberedAction 1 trueActionPrefix = true := by
  rfl

/-- Despite identical state projections, the witnesses carry distinct latest
action occurrences. -/
theorem latestAction_witness_ne :
    (MeasurableKernelArena.latestEvent 1 falseActionPrefix).action ≠
      (MeasurableKernelArena.latestEvent 1 trueActionPrefix).action := by
  simp [MeasurableKernelArena.latestEvent,
    falseActionPrefix, trueActionPrefix,
    MeasurableKernelArena.PathEvent.action]

/-- No finite-state-prefix policy agrees with `eventPolicy` on every complete
event prefix. The state-only embedding must identify the two witness inputs,
whereas `eventPolicy` assigns different Dirac action laws. -/
theorem no_state_history_policy_representation :
    ¬ ∃ statePolicy : eventArena.HistoryActionPolicy,
      ∀ time history,
        statePolicy.toEventHistoryActionPolicy.kernel time history =
          eventPolicy.kernel time history := by
  rintro ⟨statePolicy, hagree⟩
  have hfalse := hagree 1 falseActionPrefix
  have htrue := hagree 1 trueActionPrefix
  have hembedded :
      statePolicy.toEventHistoryActionPolicy.kernel
          1 falseActionPrefix =
        statePolicy.toEventHistoryActionPolicy.kernel
          1 trueActionPrefix := by
    rw [
      MeasurableKernelArena.HistoryActionPolicy.toEventHistoryActionPolicy_kernel_apply,
      MeasurableKernelArena.HistoryActionPolicy.toEventHistoryActionPolicy_kernel_apply,
      eventPrefixStates_witness_eq]
  have hdirac :
      Measure.dirac
          (⟨(), false⟩ : eventArena.ActionBundle) =
        Measure.dirac
          (⟨(), true⟩ : eventArena.ActionBundle) := by
    rw [eventPolicy_kernel_apply] at hfalse htrue
    simpa using hfalse.symm.trans (hembedded.trans htrue)
  have hsingleton :
      MeasurableSet
        ({(⟨(), false⟩ : eventArena.ActionBundle)} :
          Set eventArena.ActionBundle) := by
    change
      @MeasurableSet eventArena.ActionBundle ⊤
        {(⟨(), false⟩ : eventArena.ActionBundle)}
    exact MeasurableSpace.measurableSet_top
  have happly := congrArg
    (fun measure : Measure eventArena.ActionBundle =>
      measure {(⟨(), false⟩ : eventArena.ActionBundle)})
    hdirac
  change
    Measure.dirac
        (⟨(), false⟩ : eventArena.ActionBundle)
        {(⟨(), false⟩ : eventArena.ActionBundle)} =
      Measure.dirac
        (⟨(), true⟩ : eventArena.ActionBundle)
        {(⟨(), false⟩ : eventArena.ActionBundle)}
    at happly
  rw [Measure.dirac_apply' _ hsingleton,
    Measure.dirac_apply' _ hsingleton] at happly
  simp at happly

end EconCSLib.Examples.ExtensiveGame.EventHistoryKernelBoundary
