/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Simulation.Equilibrium.Outcome

/-!
# Strict payoff regression for measurable kernel profiles

This one-player, one-step observed game has two legal root actions. Action
`false` terminates with payoff zero and action `true` terminates with payoff
one. The baseline measurable player profile selects `false`; a constructive
unilateral deviation selects `true`.

The regression checks the complete analytic stack rather than only the
profile-assembly interface:

* the two assembled profiles have different time-one state laws;
* both profiles terminate by time one;
* the safe stopped terminal-payoff utility has expected values zero and one;
* the baseline profile therefore fails constructive Nash optimality.

All carriers are finite here so that the strict payoff calculation is
transparent. The neighboring non-atomic regressions separately ensure that
the measurable-kernel interfaces do not collapse to PMFs.
-/

open MeasureTheory ProbabilityTheory

namespace Examples.ObservedMeasurableKernelOutcomeBoundary

open ExtensiveGame
open MeasurableKernelArena

/-! ## One-step payoff game -/

/-- A root and two action-labelled terminal states. -/
inductive Node
  | root
  | terminal (action : Bool)
  deriving DecidableEq

/-- Both Boolean actions are legal at the root and none is legal after
termination. -/
def nodeAction : Node → Type
  | .root => Bool
  | .terminal _ => Empty

/-- The chosen Boolean action is retained in the terminal state. -/
def nodeNext : (state : Node) → nodeAction state → Node
  | .root, action => .terminal action
  | .terminal _, action => nomatch action

/-- The unique player controls the root. -/
def nodeMover : Node → Option Unit
  | .root => some ()
  | .terminal _ => none

/-- Payoff is one exactly after choosing `true`. -/
def nodePayoff : Node → Unit → ℝ
  | .root, _ => 0
  | .terminal false, _ => 0
  | .terminal true, _ => 1

/-- Underlying one-player one-step extensive game. -/
def base : ExtensiveGame Unit ℝ where
  State := Node
  Action := nodeAction
  next := nodeNext
  init := .root
  mover := nodeMover
  payoff := nodePayoff

/-- One-information-state observation layer. -/
def observed : ObservedGame Unit ℝ where
  base := base
  Observation := fun _ => Unit
  PublicObservation := Unit
  observe := fun _ _ => ()
  publicObserve := fun _ => ()
  publicOf := fun _ _ => ()
  observe_public := fun _ _ => rfl
  InfoState := fun _ => Unit
  infoObserve := fun _ _ => ()
  infoAt := fun _ _ _ _ => ()
  infoAt_observe := fun _ _ _ _ => rfl
  InfoAction := fun _ _ => Bool
  actionEquiv := by
    intro history i hmover _hnonterminal
    cases i
    cases hstate : history.1 with
    | root =>
        change Bool ≃ Bool
        exact Equiv.refl Bool
    | terminal action =>
        change nodeMover history.1 = some () at hmover
        rw [hstate] at hmover
        contradiction

abbrev History := ObservedGame.CompleteHistory observed

/-- Empty initial history. -/
def rootHistory : History :=
  Arena.HistoryFrom.nil observed.base.toArena observed.base.init

/-- Terminal history generated by one Boolean root action. -/
def terminalHistory (action : Bool) : History :=
  ⟨.terminal action, rootHistory.2.snoc action⟩

/-- Any complete history ending at the root is the empty history. -/
theorem eq_rootHistory_of_endpoint_root
    (history : History)
    (hroot : history.1 = .root) :
    history = rootHistory := by
  rcases history with ⟨state, path⟩
  cases path with
  | nil => rfl
  | @snoc previousState path previousAction =>
      cases previousState with
      | root => contradiction
      | terminal action => exact Empty.elim previousAction

/-- Exact discrete measurable model for the finite complete-history system. -/
noncomputable def historyModel :
    observed.MeasurableHistoryModel :=
  ObservedGame.MeasurableHistoryModel.discrete observed

noncomputable local instance historyMeasurable : MeasurableSpace History :=
  historyModel.historyMeasurable

noncomputable local instance historyMeasurableSingletonClass :
    MeasurableSingletonClass History where
  measurableSet_singleton :=
    historyModel.singleton_measurable

noncomputable abbrev AnalyticArena := historyModel.toArena

/-! ## Full-history information and deterministic action realization -/

/-- Common information is the latest complete history. -/
def eventInformation :
    AnalyticArena.EventInformation where
  Information := fun _ => History
  informationMeasurable := fun _ => ⊤
  informationAt := fun time events =>
    latestEventState time events
  informationAt_measurable := by
    intro time
    exact measurable_latestEventState time

/-- Concrete legal root bundle for one abstract Boolean action. -/
def rootBundle (action : Bool) :
    AnalyticArena.ActionBundle :=
  ⟨rootHistory, action⟩

/-- Deterministically realize an abstract Boolean as the matching root
action bundle. Only represented nonterminal inputs are semantically used. -/
noncomputable def realizationKernel (time : ℕ) :
    Kernel
      (AnalyticArena.EventPrefix time × Bool)
      AnalyticArena.ActionBundle :=
  Kernel.deterministic
    (fun input => rootBundle input.2)
    (by
      exact
        (Measurable.of_discrete :
          Measurable rootBundle).comp measurable_snd)

@[simp]
theorem realizationKernel_apply
    (time : ℕ)
    (events : AnalyticArena.EventPrefix time)
    (action : Bool) :
    realizationKernel time (events, action) =
      Measure.dirac (rootBundle action) := by
  rw [realizationKernel, Kernel.deterministic_apply]

/-- Boolean abstract action realization. -/
noncomputable def realization :
    EventInformation.ActionRealization eventInformation where
  AbstractAction := fun _ => Bool
  abstractActionMeasurable := fun _ => ⊤
  kernel := realizationKernel
  kernel_isSFinite := by
    intro time
    unfold realizationKernel
    infer_instance

/-- Structural measurable presentation; there are no reachable chance
histories. -/
noncomputable def presentation :
    observed.MeasurableKernelPresentation historyModel where
  information := eventInformation
  realization := realization
  playerInformation := fun _ _ => rootHistory
  player_informationAt := by
    intro time events i hmover _hnonterminal
    cases i
    change latestEventState time events = rootHistory
    apply eq_rootHistory_of_endpoint_root
    cases hstate : (latestEventState time events).1 with
    | root => rfl
    | terminal action =>
        change nodeMover _ = some () at hmover
        rw [hstate] at hmover
        contradiction
  chanceKernel := fun _ => 0
  chanceKernel_isSFinite := by
    intro _
    infer_instance

/-! ## Measurable roles and player-profile assembly -/

/-- Terminal complete histories. -/
def terminalInformationSet : Set History :=
  {history | base.isTerminal history.1}

/-- Nonterminal complete histories. -/
def playerInformationSet : Set History :=
  {history | ¬ base.isTerminal history.1}

/-- Exact measurable role classification. -/
def roles :
    presentation.InformationRoles where
  playerTagMeasurable := ⊤
  playerTagSingleton_measurable := by
    intro _
    exact MeasurableSpace.measurableSet_top
  terminalInformationSet := fun _ => terminalInformationSet
  terminalInformationSet_measurable := by
    intro _
    exact MeasurableSpace.measurableSet_top
  playerInformationSet := fun _ => playerInformationSet
  playerInformationSet_measurable := by
    intro _
    exact MeasurableSpace.measurableSet_top
  playerTag := fun _ _ => some ()
  playerTag_measurable := by
    intro _
    exact measurable_const
  terminal_at := by
    intro _ _ hterminal
    exact hterminal
  player_at := by
    intro _ _ i hnonterminal hmover
    cases i
    exact ⟨hnonterminal, hnonterminal, rfl⟩
  chance_at := by
    intro time events hnonterminal hmover
    cases hstate : (latestEventState time events).1 with
    | root =>
        change nodeMover _ = none at hmover
        rw [hstate] at hmover
        contradiction
    | terminal action =>
        exact
          (hnonterminal (by
            rw [hstate]
            change IsEmpty Empty
            exact ⟨Empty.elim⟩)).elim

/-- No represented nonterminal history is chance-controlled. -/
theorem no_nonterminal_chance
    (time : ℕ)
    (events : AnalyticArena.EventPrefix time)
    (hnonterminal :
      ¬ base.isTerminal (latestEventState time events).1)
    (hmover :
      base.mover (latestEventState time events).1 = none) :
    False := by
  cases hstate : (latestEventState time events).1 with
  | root =>
      change nodeMover _ = none at hmover
      rw [hstate] at hmover
      contradiction
  | terminal action =>
      exact
        hnonterminal (by
          rw [hstate]
          change IsEmpty Empty
          exact ⟨Empty.elim⟩)

/-- Profile assembly with an unreachable zero chance branch. -/
noncomputable def assembly :
    presentation.ProfileAssembly where
  toInformationRoles := roles
  chanceAbstractKernel := fun _ => 0
  chanceAbstractKernel_isSFinite := by
    intro _
    infer_instance
  chance_isProbability := by
    intro time events hnonterminal hmover
    exact (no_nonterminal_chance time events hnonterminal hmover).elim
  chance_realization_isProbability := by
    intro time events hnonterminal hmover
    exact (no_nonterminal_chance time events hnonterminal hmover).elim
  chance_realization_legal := by
    intro time events hnonterminal hmover
    exact (no_nonterminal_chance time events hnonterminal hmover).elim
  chance_realizedKernel := by
    intro time events hnonterminal hmover
    exact (no_nonterminal_chance time events hnonterminal hmover).elim

/-- Any represented player prefix is the root history. -/
theorem latestEventState_eq_root_of_mover
    (time : ℕ)
    (events : AnalyticArena.EventPrefix time)
    (i : Unit)
    (hmover :
      base.mover (latestEventState time events).1 = some i) :
    latestEventState time events = rootHistory := by
  cases i
  apply eq_rootHistory_of_endpoint_root
  cases hstate : (latestEventState time events).1 with
  | root => rfl
  | terminal action =>
      change nodeMover _ = some () at hmover
      rw [hstate] at hmover
      contradiction

/-- Deterministic realization is normalized at every player prefix. -/
theorem realization_isProbability_at_player
    (time : ℕ)
    (events : AnalyticArena.EventPrefix time)
    (measure : Measure Bool)
    (_i : Unit)
    (_hnonterminal :
      ¬ base.isTerminal (latestEventState time events).1)
    (_hmover :
      base.mover (latestEventState time events).1 = some ()) :
    ∀ᵐ action ∂measure,
      IsProbabilityMeasure
        (realizationKernel time (events, action)) := by
  exact Filter.Eventually.of_forall fun action => by
    rw [realizationKernel_apply]
    infer_instance

/-- Deterministic realization lies in the represented root action fiber. -/
theorem realization_legal_at_player
    (time : ℕ)
    (events : AnalyticArena.EventPrefix time)
    (measure : Measure Bool)
    (i : Unit)
    (_hnonterminal :
      ¬ base.isTerminal (latestEventState time events).1)
    (hmover :
      base.mover (latestEventState time events).1 = some i) :
    ∀ᵐ action ∂measure,
      realizationKernel time (events, action)
          (AnalyticArena.actionFiber
            (latestEventState time events)) =
        1 := by
  exact Filter.Eventually.of_forall fun action => by
    rw [realizationKernel_apply]
    apply Measure.dirac_apply_of_mem
    change rootHistory = latestEventState time events
    exact (latestEventState_eq_root_of_mover time events i hmover).symm

/-! ## Baseline and deviating player laws -/

/-- Joint baseline law selecting `false` at every tagged input. -/
noncomputable def baselineProfile :
    assembly.PlayerKernelProfile where
  kernel := fun _ =>
    Kernel.deterministic (fun _ => false) measurable_const
  kernel_isSFinite := by
    intro _
    infer_instance
  isProbability := by
    intro time events i _ _
    change
      IsProbabilityMeasure
        ((Kernel.deterministic
          (fun _ : assembly.PlayerInput time => false)
          measurable_const)
          ⟨some i, latestEventState time events⟩)
    rw [Kernel.deterministic_apply]
    infer_instance
  realization_isProbability := by
    intro time events i hnonterminal hmover
    change
      ∀ᵐ action
          ∂Measure.dirac false,
        IsProbabilityMeasure
          (realizationKernel time (events, action))
    exact
      realization_isProbability_at_player
        time events (Measure.dirac false) i hnonterminal hmover
  realization_legal := by
    intro time events i hnonterminal hmover
    change
      ∀ᵐ stateAction
          ∂(Measure.dirac false).bind
            (Kernel.sectR
              (realizationKernel time) events),
        stateAction ∈
          AnalyticArena.actionFiber
            (latestEventState time events)
    apply
      MeasurableKernelArena.EventInformation.RealizedActionPolicy.ae_bind_mem_actionFiber_of_ae_mass_one
        (Measure.dirac false)
        (Kernel.sectR (realizationKernel time) events)
        (latestEventState time events)
    · simpa only [Kernel.sectR_apply] using
        realization_isProbability_at_player
          time events (Measure.dirac false)
            i hnonterminal hmover
    · simpa only [Kernel.sectR_apply] using
        realization_legal_at_player
          time events (Measure.dirac false)
            i hnonterminal hmover

@[simp]
theorem baselineProfile_kernel
    (time : ℕ)
    (input : assembly.PlayerInput time) :
    baselineProfile.kernel time input =
      Measure.dirac false := by
  change
    (Kernel.deterministic
      (fun _ : assembly.PlayerInput time => false)
      measurable_const) input =
        Measure.dirac false
  rw [Kernel.deterministic_apply]

/-- Replacement strategy selecting the payoff-one action `true`. -/
noncomputable def trueStrategy :
    assembly.PlayerStrategy () where
  kernel := fun _ =>
    Kernel.deterministic (fun _ => true) measurable_const
  kernel_isSFinite := by
    intro _
    infer_instance
  isProbability := by
    intro time events _ _
    change
      IsProbabilityMeasure
        ((Kernel.deterministic
          (fun _ : History => true)
          measurable_const)
          (latestEventState time events))
    rw [Kernel.deterministic_apply]
    infer_instance
  realization_isProbability := by
    intro time events hnonterminal hmover
    change
      ∀ᵐ action
          ∂Measure.dirac true,
        IsProbabilityMeasure
          (realizationKernel time (events, action))
    exact
      realization_isProbability_at_player
        time events (Measure.dirac true) () hnonterminal hmover
  realization_legal := by
    intro time events hnonterminal hmover
    change
      ∀ᵐ stateAction
          ∂(Measure.dirac true).bind
            (Kernel.sectR
              (realizationKernel time) events),
        stateAction ∈
          AnalyticArena.actionFiber
            (latestEventState time events)
    apply
      MeasurableKernelArena.EventInformation.RealizedActionPolicy.ae_bind_mem_actionFiber_of_ae_mass_one
        (Measure.dirac true)
        (Kernel.sectR (realizationKernel time) events)
        (latestEventState time events)
    · simpa only [Kernel.sectR_apply] using
        realization_isProbability_at_player
          time events (Measure.dirac true)
            () hnonterminal hmover
    · simpa only [Kernel.sectR_apply] using
        realization_legal_at_player
          time events (Measure.dirac true)
            () hnonterminal hmover

@[simp]
theorem trueStrategy_kernel
    (time : ℕ)
    (history : History) :
    trueStrategy.kernel time history =
      Measure.dirac true := by
  change
    (Kernel.deterministic
      (fun _ : History => true)
      measurable_const) history =
        Measure.dirac true
  rw [Kernel.deterministic_apply]

/-- Constructive unilateral deviation to the payoff-one action. -/
noncomputable def deviatedProfile :
    assembly.PlayerKernelProfile :=
  ObservedGame.MeasurableKernelPresentation.ProfileAssembly.PlayerKernelProfile.deviate
    (assembly := assembly)
    baselineProfile () trueStrategy

/-- Assembled baseline profile. -/
noncomputable def assembledBaseline :
    presentation.KernelBehavioralProfile :=
  assembly.toKernelBehavioralProfile baselineProfile

/-- Assembled payoff-improving deviation. -/
noncomputable def assembledDeviation :
    presentation.KernelBehavioralProfile :=
  assembly.toKernelBehavioralProfile deviatedProfile

/-! ## Strict compiled and path-law witnesses -/

/-- Inhabited initial event prefix. -/
noncomputable def rootPrefix :
    AnalyticArena.EventPrefix 0 :=
  fun _ => AnalyticArena.initialEvent rootHistory

@[simp]
theorem latestEventState_rootPrefix :
    latestEventState 0 rootPrefix = rootHistory :=
  rfl

/-- The represented initial history is nonterminal. -/
theorem root_nonterminal :
    ¬ base.isTerminal (latestEventState 0 rootPrefix).1 := by
  change ¬ IsEmpty Bool
  intro hempty
  exact hempty.false false

/-- The unique player genuinely controls the represented initial history. -/
theorem root_mover :
    base.mover (latestEventState 0 rootPrefix).1 =
      some () :=
  rfl

/-- The assembled baseline selects exactly the concrete `false` bundle at the
inhabited root. -/
theorem assembledBaseline_compiled_kernel_root :
    assembledBaseline.compiledPolicy.kernel 0 rootPrefix =
      Measure.dirac (rootBundle false) := by
  rw [
    ObservedGame.MeasurableKernelPresentation.KernelBehavioralProfile.compiledPolicy_kernel,
    EventInformation.RealizedActionPolicy.realizedKernel_apply]
  change
    (assembly.abstractKernel baselineProfile 0 rootHistory).bind
        (fun action =>
          realizationKernel 0 (rootPrefix, action)) =
      Measure.dirac (rootBundle false)
  have habstract :=
    assembly.abstractKernel_apply_player
      baselineProfile 0 rootPrefix () root_nonterminal root_mover
  change
    assembly.abstractKernel baselineProfile 0 rootHistory =
      baselineProfile.kernel 0 ⟨some (), rootHistory⟩
    at habstract
  rw [habstract, baselineProfile_kernel]
  change
    (realizationKernel 0).sectR rootPrefix ∘ₘ
        Measure.dirac false =
      Measure.dirac (rootBundle false)
  rw [Measure.dirac_bind
    ((realizationKernel 0).sectR rootPrefix).measurable]
  exact realizationKernel_apply 0 rootPrefix false

/-- The assembled deviation selects exactly the concrete `true` bundle at the
inhabited root. -/
theorem assembledDeviation_compiled_kernel_root :
    assembledDeviation.compiledPolicy.kernel 0 rootPrefix =
      Measure.dirac (rootBundle true) := by
  rw [
    ObservedGame.MeasurableKernelPresentation.KernelBehavioralProfile.compiledPolicy_kernel,
    EventInformation.RealizedActionPolicy.realizedKernel_apply]
  change
    (assembly.abstractKernel deviatedProfile 0 rootHistory).bind
        (fun action =>
          realizationKernel 0 (rootPrefix, action)) =
      Measure.dirac (rootBundle true)
  have habstract :=
    assembly.abstractKernel_apply_player
      deviatedProfile 0 rootPrefix () root_nonterminal root_mover
  change
    assembly.abstractKernel deviatedProfile 0 rootHistory =
      deviatedProfile.kernel 0 ⟨some (), rootHistory⟩
    at habstract
  rw [habstract]
  unfold deviatedProfile
  rw [
    ObservedGame.MeasurableKernelPresentation.ProfileAssembly.PlayerKernelProfile.deviate_kernel_same,
    trueStrategy_kernel]
  change
    (realizationKernel 0).sectR rootPrefix ∘ₘ
        Measure.dirac true =
      Measure.dirac (rootBundle true)
  rw [Measure.dirac_bind
    ((realizationKernel 0).sectR rootPrefix).measurable]
  exact realizationKernel_apply 0 rootPrefix true

/-- The assembled profiles satisfy the library's generic unilateral-deviation
relation. -/
theorem assembledDeviation_isUnilateralDeviation :
    assembledBaseline.IsUnilateralDeviation
      () assembledDeviation :=
  assembly.toKernelBehavioralProfile_deviate
    baselineProfile () trueStrategy

/-- The analytic history transition appends the selected root action
deterministically. -/
@[simp]
theorem transition_rootBundle
    (action : Bool) :
    AnalyticArena.transition (rootBundle action) =
      Measure.dirac (terminalHistory action) := by
  change
    AnalyticArena.nextMeasure rootHistory action =
      Measure.dirac (terminalHistory action)
  rw [
    ObservedGame.MeasurableHistoryModel.toArena_nextMeasure,
    PMF.toMeasure_pure]
  rfl

/-- The baseline time-one state coordinate is concentrated on the
payoff-zero terminal history. -/
theorem assembledBaseline_stateCoordinate_one :
    assembledBaseline.compiledPolicy.stateCoordinateMeasure
        historyModel.toArena_terminalSet_measurable
        rootHistory 1 =
      Measure.dirac (terminalHistory false) := by
  rw [
    MeasurableKernelArena.EventHistoryActionPolicy.stateCoordinateMeasure_one_of_nonterminal
      assembledBaseline.compiledPolicy
      historyModel.toArena_terminalSet_measurable
      rootHistory]
  · have hkernel := assembledBaseline_compiled_kernel_root
    change
      assembledBaseline.compiledPolicy.kernel 0
          (fun _ : Finset.Iic 0 =>
            AnalyticArena.initialEvent rootHistory) =
        Measure.dirac (rootBundle false)
      at hkernel
    rw [hkernel]
    rw [Measure.dirac_bind AnalyticArena.transition.measurable]
    exact transition_rootBundle false
  · change ¬ IsEmpty Bool
    intro hempty
    exact hempty.false false

/-- The deviated time-one state coordinate is concentrated on the payoff-one
terminal history. -/
theorem assembledDeviation_stateCoordinate_one :
    assembledDeviation.compiledPolicy.stateCoordinateMeasure
        historyModel.toArena_terminalSet_measurable
        rootHistory 1 =
      Measure.dirac (terminalHistory true) := by
  rw [
    MeasurableKernelArena.EventHistoryActionPolicy.stateCoordinateMeasure_one_of_nonterminal
      assembledDeviation.compiledPolicy
      historyModel.toArena_terminalSet_measurable
      rootHistory]
  · have hkernel := assembledDeviation_compiled_kernel_root
    change
      assembledDeviation.compiledPolicy.kernel 0
          (fun _ : Finset.Iic 0 =>
            AnalyticArena.initialEvent rootHistory) =
        Measure.dirac (rootBundle true)
      at hkernel
    rw [hkernel]
    rw [Measure.dirac_bind AnalyticArena.transition.measurable]
    exact transition_rootBundle true
  · change ¬ IsEmpty Bool
    intro hempty
    exact hempty.false false

/-- The unilateral deviation changes the time-one state law strictly. -/
theorem timeOne_state_laws_ne :
    assembledBaseline.compiledPolicy.stateCoordinateMeasure
        historyModel.toArena_terminalSet_measurable
        rootHistory 1 ≠
      assembledDeviation.compiledPolicy.stateCoordinateMeasure
        historyModel.toArena_terminalSet_measurable
        rootHistory 1 := by
  rw [
    assembledBaseline_stateCoordinate_one,
    assembledDeviation_stateCoordinate_one]
  intro heq
  have hstate :
      terminalHistory false = terminalHistory true :=
    injective_dirac heq
  have hendpoint := congrArg Sigma.fst hstate
  have hbool : false = true :=
    Node.terminal.inj hendpoint
  contradiction

/-! ## Safe terminal payoff and constructive Nash failure -/

/-- The baseline terminates by the first post-initial coordinate. -/
theorem assembledBaseline_terminatesBy_one :
    assembledBaseline.TerminatesBy rootHistory 1 := by
  unfold
    ObservedGame.MeasurableKernelPresentation.KernelBehavioralProfile.TerminatesBy
  refine
    MeasureTheory.ae_of_ae_map
      (μ := assembledBaseline.statePathMeasure rootHistory)
      (f := fun path : ℕ → AnalyticArena.State => path 1)
      (p := fun history => base.isTerminal history.1)
      (measurable_pi_apply 1).aemeasurable
      ?_
  change
    ∀ᵐ history
        ∂assembledBaseline.compiledPolicy.stateCoordinateMeasure
          historyModel.toArena_terminalSet_measurable
          rootHistory 1,
      base.isTerminal history.1
  rw [assembledBaseline_stateCoordinate_one]
  apply
    (MeasureTheory.ae_dirac_iff
      historyModel.toArena_terminalSet_measurable).2
  change IsEmpty Empty
  exact ⟨Empty.elim⟩

/-- The deviated profile also terminates by the first post-initial
coordinate. -/
theorem assembledDeviation_terminatesBy_one :
    assembledDeviation.TerminatesBy rootHistory 1 := by
  unfold
    ObservedGame.MeasurableKernelPresentation.KernelBehavioralProfile.TerminatesBy
  refine
    MeasureTheory.ae_of_ae_map
      (μ := assembledDeviation.statePathMeasure rootHistory)
      (f := fun path : ℕ → AnalyticArena.State => path 1)
      (p := fun history => base.isTerminal history.1)
      (measurable_pi_apply 1).aemeasurable
      ?_
  change
    ∀ᵐ history
        ∂assembledDeviation.compiledPolicy.stateCoordinateMeasure
          historyModel.toArena_terminalSet_measurable
          rootHistory 1,
      base.isTerminal history.1
  rw [assembledDeviation_stateCoordinate_one]
  apply
    (MeasureTheory.ae_dirac_iff
      historyModel.toArena_terminalSet_measurable).2
  change IsEmpty Empty
  exact ⟨Empty.elim⟩

/-- The base payoff itself is a measurable bounded extension from terminal
histories to all complete histories. -/
noncomputable def terminalPayoff :
    ObservedGame.MeasurableHistoryModel.BoundedTerminalPayoffExtension
      observed historyModel where
  payoff := fun _ history =>
    base.payoff history.1 ()
  payoff_measurable := by
    intro _
    change
      @Measurable History ℝ ⊤ inferInstance
        (fun history => base.payoff history.1 ())
    exact Measurable.of_discrete
  payoff_eq_base := by
    intro _ _ _
    rfl
  bound := 1
  norm_payoff_le := by
    intro i history _
    cases i
    change ‖nodePayoff history.1 ()‖ ≤ (1 : ℝ)
    cases hstate : history.1 with
    | root => simp [nodePayoff]
    | terminal action =>
        cases action <;> simp [nodePayoff]

/-- Horizon-one stopped terminal payoff. -/
noncomputable def evaluation :
    ObservedGame.MeasurableHistoryModel.BoundedPathUtility
      historyModel :=
  terminalPayoff.stoppedBoundedPathUtility 1

/-- The assembled baseline has expected utility zero. -/
theorem assembledBaseline_expectedUtility :
    evaluation.expectedUtility
        assembledBaseline rootHistory () =
      0 := by
  change
    (terminalPayoff.stoppedBoundedPathUtility 1).expectedUtility
        assembledBaseline rootHistory () =
      0
  rw [
    ObservedGame.MeasurableHistoryModel.BoundedTerminalPayoffExtension.expectedUtility_eq_integral_stateCoordinate_of_terminatesBy
      terminalPayoff assembledBaseline rootHistory 1
      assembledBaseline_terminatesBy_one ()]
  rw [assembledBaseline_stateCoordinate_one]
  calc
    (∫ history,
      terminalPayoff.payoff () history
      ∂Measure.dirac (terminalHistory false)) =
        terminalPayoff.payoff () (terminalHistory false) := by
      exact
        @integral_dirac
          History ℝ _ _ _
          historyModel.historyMeasurable
          historyMeasurableSingletonClass
          (terminalPayoff.payoff ())
          (terminalHistory false)
    _ = 0 := rfl

/-- The constructive unilateral deviation has expected utility one. -/
theorem assembledDeviation_expectedUtility :
    evaluation.expectedUtility
        assembledDeviation rootHistory () =
      1 := by
  change
    (terminalPayoff.stoppedBoundedPathUtility 1).expectedUtility
        assembledDeviation rootHistory () =
      1
  rw [
    ObservedGame.MeasurableHistoryModel.BoundedTerminalPayoffExtension.expectedUtility_eq_integral_stateCoordinate_of_terminatesBy
      terminalPayoff assembledDeviation rootHistory 1
      assembledDeviation_terminatesBy_one ()]
  rw [assembledDeviation_stateCoordinate_one]
  calc
    (∫ history,
      terminalPayoff.payoff () history
      ∂Measure.dirac (terminalHistory true)) =
        terminalPayoff.payoff () (terminalHistory true) := by
      exact
        @integral_dirac
          History ℝ _ _ _
          historyModel.historyMeasurable
          historyMeasurableSingletonClass
          (terminalPayoff.payoff ())
          (terminalHistory true)
    _ = 1 := rfl

/-- The payoff-zero baseline is not Nash because the certified `true`
strategy raises the unique player's expected payoff from zero to one. -/
theorem baseline_not_nash :
    ¬ evaluation.IsNashAt
        assembly rootHistory baselineProfile := by
  intro hnash
  have hdeviation := hnash () trueStrategy
  change
    evaluation.expectedUtility
        assembledDeviation rootHistory () ≤
      evaluation.expectedUtility
        assembledBaseline rootHistory ()
    at hdeviation
  rw [
    assembledDeviation_expectedUtility,
    assembledBaseline_expectedUtility]
    at hdeviation
  norm_num at hdeviation

end Examples.ObservedMeasurableKernelOutcomeBoundary
