/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Execution.Discrete.EffectivePathUtility

/-!
# Certified finite-prefix approximation schemes

This module supplies a measure-free execution interface for rational
finite-prefix approximation schemes.  A state or event scheme gives, at every
horizon, an executable rational prefix observable and a nonnegative rational
radius.  A coherent effective path law computes the center exactly with
`FiniteLaw.expectRat`; the corresponding **scheme interval** is
`[center - radius, center + radius]`.

The word "scheme" is material: the radius is finite algorithmic data.  By
itself it does not prove that an infinite-path utility, a real expectation, or
any other external target lies in the interval.  Such a conclusion requires a
separate semantic approximation certificate relating that target to every
finite-prefix observable.  In particular, no target expectation or desired
error conclusion is accepted as runtime input here.

The common radius search tests horizons `0, ..., budget - 1` and returns the
first one whose exact radius meets the tolerance.  Its proofs give soundness,
minimality, and a precise characterization of search exhaustion.  An
unbounded least horizon is available only from an explicit existence proof;
an optional `Vanishes` contract is a sufficient source of such witnesses for
positive tolerances.

Event observables receive complete action-recording prefixes, so route and
action occurrences remain available.  State schemes can be projected to
event execution explicitly, with a correctness theorem for policies compiled
by `toEventHistoryPolicy`.

For a supplied effective law, evaluating one center is linear in the law's
weighted occurrence list.  A budgeted search performs at most `budget` radius
comparisons and computes a center only at the selected horizon.  Constructing
the finite prefix law may still grow exponentially with horizon and branching
degree.

## Main definitions and results

* `RationalSchemeEstimate` and its exact rational `interval`;
* `ApproximationRadius.searchHorizon`, with sound/minimal/none-iff results;
* state/event `PrefixApproximationScheme.center`, `estimate`, and `search`;
* explicit-existence least-horizon computation;
* zero-radius exact cylinder estimates from prefix-law coherence;
* `StatePrefixApproximationScheme.toEvent` and its policy projection theorem.
-/

namespace KernelArena

universe uS uA

/-- An exact rational center paired with a declared nonnegative rational
scheme radius.  The radius acquires target-error meaning only from a separate
semantic approximation certificate. -/
structure RationalSchemeEstimate where
  center : ℚ
  radius : ℚ≥0
deriving DecidableEq

namespace RationalSchemeEstimate

/-- Two rational scheme estimates are equal when both exact fields agree. -/
@[ext]
theorem ext {left right : RationalSchemeEstimate}
    (hcenter : left.center = right.center)
    (hradius : left.radius = right.radius) : left = right := by
  cases left
  cases right
  simp_all

/-- Closed rational endpoints generated by a scheme estimate. -/
def interval (estimate : RationalSchemeEstimate) : ℚ × ℚ :=
  (estimate.center - (estimate.radius : ℚ),
    estimate.center + (estimate.radius : ℚ))

@[simp]
theorem interval_fst (estimate : RationalSchemeEstimate) :
    estimate.interval.1 = estimate.center - (estimate.radius : ℚ) :=
  rfl

@[simp]
theorem interval_snd (estimate : RationalSchemeEstimate) :
    estimate.interval.2 = estimate.center + (estimate.radius : ℚ) :=
  rfl

/-- The lower endpoint of every scheme interval is at most its center. -/
theorem lower_le_center (estimate : RationalSchemeEstimate) :
    estimate.interval.1 ≤ estimate.center := by
  simp [interval]

/-- The center of every scheme interval is at most its upper endpoint. -/
theorem center_le_upper (estimate : RationalSchemeEstimate) :
    estimate.center ≤ estimate.interval.2 := by
  simp [interval]

/-- A zero-radius estimate is the singleton rational interval at its exact
center. -/
@[simp]
theorem interval_of_radius_eq_zero (estimate : RationalSchemeEstimate)
    (hradius : estimate.radius = 0) :
    estimate.interval = (estimate.center, estimate.center) := by
  simp [interval, hradius]

end RationalSchemeEstimate

/-- Executable nonnegative rational radii indexed by finite horizon. -/
abbrev ApproximationRadius := ℕ → ℚ≥0

namespace ApproximationRadius

/-- Search horizons `0, ..., budget - 1` for the first radius no larger than
`tolerance`.  The budget counts horizon zero. -/
def searchHorizon (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget : ℕ) : Option ℕ :=
  (List.range budget).find? fun horizon =>
    decide (radius horizon ≤ tolerance)

/-- A successful radius search stays inside its budget and meets the exact
rational tolerance. -/
theorem searchHorizon_sound (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : radius.searchHorizon tolerance budget = some horizon) :
    horizon < budget ∧ radius horizon ≤ tolerance := by
  refine ⟨List.mem_range.mp (List.mem_of_find?_eq_some hsearch), ?_⟩
  have hp := List.find?_some
    (p := fun candidate => decide (radius candidate ≤ tolerance)) hsearch
  exact of_decide_eq_true hp

/-- A successful radius search has rejected every earlier horizon. -/
theorem searchHorizon_minimal (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : radius.searchHorizon tolerance budget = some horizon) :
    ∀ earlier < horizon, tolerance < radius earlier := by
  have hfind := List.find?_range_eq_some.mp hsearch
  intro earlier hearlier
  have hfailed := hfind.2.2 earlier hearlier
  apply lt_of_not_ge
  simpa using hfailed

/-- Search exhaustion says exactly that every tested horizon has radius
strictly above tolerance.  It says nothing about later horizons. -/
theorem searchHorizon_eq_none_iff (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget : ℕ) :
    radius.searchHorizon tolerance budget = none ↔
      ∀ horizon < budget, tolerance < radius horizon := by
  simp [searchHorizon, List.find?_eq_none]

/-- Least acceptable horizon, given an explicit proof that one exists.  The
proof is erased from the computed natural number. -/
def leastHorizon (radius : ApproximationRadius) (tolerance : ℚ≥0)
    (hexists : ∃ horizon, radius horizon ≤ tolerance) : ℕ :=
  Nat.find hexists

/-- The explicit-existence computation returns the least acceptable
horizon. -/
theorem leastHorizon_spec (radius : ApproximationRadius)
    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, radius horizon ≤ tolerance) :
    radius (radius.leastHorizon tolerance hexists) ≤ tolerance ∧
      ∀ earlier < radius.leastHorizon tolerance hexists,
        tolerance < radius earlier := by
  unfold leastHorizon
  exact ⟨Nat.find_spec hexists,
    fun _ hlt => lt_of_not_ge (Nat.find_min hexists hlt)⟩

/-- A genuine vanishing-radius contract: every positive tolerance eventually
bounds all later radii.  This is proof data, not a convergence-rate oracle. -/
def Vanishes (radius : ApproximationRadius) : Prop :=
  ∀ tolerance : ℚ≥0, 0 < tolerance →
    ∃ cutoff, ∀ horizon, cutoff ≤ horizon → radius horizon ≤ tolerance

/-- A vanishing radius supplies an acceptable horizon for every positive
tolerance. -/
theorem Vanishes.exists_within {radius : ApproximationRadius}
    (hvanishes : radius.Vanishes) (tolerance : ℚ≥0)
    (htolerance : 0 < tolerance) :
    ∃ horizon, radius horizon ≤ tolerance := by
  obtain ⟨cutoff, hcutoff⟩ := hvanishes tolerance htolerance
  exact ⟨cutoff, hcutoff cutoff le_rfl⟩

end ApproximationRadius

/-- A state-prefix approximation scheme.  Both fields are executable finite
data; no infinite-path target is stored in the scheme. -/
structure StatePrefixApproximationScheme (A : KernelArena) (start : ℕ) where
  observable : (horizon : ℕ) → A.StatePrefix (start + horizon) → ℚ
  radius : ApproximationRadius

end KernelArena
