/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Execution.Discrete.EffectivePathUtility

/-!
# Certified finite-prefix approximation schemes

This module supplies a measure-free execution interface for rational
finite-prefix approximation schemes.  A state or event scheme gives, at every
horizon, an executable rational prefix observable and a nonnegative rational
radius.  A coherent effective path law computes the center exactly with
`FiniteLaw.expectRat`; the corresponding **scheme interval** is
`[center - radius, center + radius]`.

The word "scheme" is material: the radius is finite algorithmic data.  By
itself it does not prove that an infinite-path utility, a real expectation, or
any other external target lies in the interval.  Such a conclusion requires a
separate semantic approximation certificate relating that target to every
finite-prefix observable.  In particular, no target expectation or desired
error conclusion is accepted as runtime input here.

The common radius search tests horizons `0, ..., budget - 1` and returns the
first one whose exact radius meets the tolerance.  Its proofs give soundness,
minimality, and a precise characterization of search exhaustion.  An
unbounded least horizon is available only from an explicit existence proof;
an optional `Vanishes` contract is a sufficient source of such witnesses for
positive tolerances.

Event observables receive complete action-recording prefixes, so route and
action occurrences remain available.  State schemes can be projected to
event execution explicitly, with a correctness theorem for policies compiled
by `toEventHistoryPolicy`.

For a supplied effective law, evaluating one center is linear in the law's
weighted occurrence list.  A budgeted search performs at most `budget` radius
comparisons and computes a center only at the selected horizon.  Constructing
the finite prefix law may still grow exponentially with horizon and branching
degree.

## Main definitions and results

* `RationalSchemeEstimate` and its exact rational `interval`;
* `ApproximationRadius.searchHorizon`, with sound/minimal/none-iff results;
* state/event `PrefixApproximationScheme.center`, `estimate`, and `search`;
* explicit-existence least-horizon computation;
* zero-radius exact cylinder estimates from prefix-law coherence;
* `StatePrefixApproximationScheme.toEvent` and its policy projection theorem.
-/

namespace KernelArena

universe uS uA

/-- An exact rational center paired with a declared nonnegative rational
scheme radius.  The radius acquires target-error meaning only from a separate
semantic approximation certificate. -/
structure RationalSchemeEstimate where
  center : ℚ
  radius : ℚ≥0
deriving DecidableEq

namespace RationalSchemeEstimate

/-- Two rational scheme estimates are equal when both exact fields agree. -/
@[ext]
theorem ext {left right : RationalSchemeEstimate}
    (hcenter : left.center = right.center)
    (hradius : left.radius = right.radius) : left = right := by
  cases left
  cases right
  simp_all

/-- Closed rational endpoints generated by a scheme estimate. -/
def interval (estimate : RationalSchemeEstimate) : ℚ × ℚ :=
  (estimate.center - (estimate.radius : ℚ),
    estimate.center + (estimate.radius : ℚ))

@[simp]
theorem interval_fst (estimate : RationalSchemeEstimate) :
    estimate.interval.1 = estimate.center - (estimate.radius : ℚ) :=
  rfl

@[simp]
theorem interval_snd (estimate : RationalSchemeEstimate) :
    estimate.interval.2 = estimate.center + (estimate.radius : ℚ) :=
  rfl

/-- The lower endpoint of every scheme interval is at most its center. -/
theorem lower_le_center (estimate : RationalSchemeEstimate) :
    estimate.interval.1 ≤ estimate.center := by
  simp [interval]

/-- The center of every scheme interval is at most its upper endpoint. -/
theorem center_le_upper (estimate : RationalSchemeEstimate) :
    estimate.center ≤ estimate.interval.2 := by
  simp [interval]

/-- A zero-radius estimate is the singleton rational interval at its exact
center. -/
@[simp]
theorem interval_of_radius_eq_zero (estimate : RationalSchemeEstimate)
    (hradius : estimate.radius = 0) :
    estimate.interval = (estimate.center, estimate.center) := by
  simp [interval, hradius]

end RationalSchemeEstimate

/-- Executable nonnegative rational radii indexed by finite horizon. -/
abbrev ApproximationRadius := ℕ → ℚ≥0

namespace ApproximationRadius

/-- Search horizons `0, ..., budget - 1` for the first radius no larger than
`tolerance`.  The budget counts horizon zero. -/
def searchHorizon (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget : ℕ) : Option ℕ :=
  (List.range budget).find? fun horizon =>
    decide (radius horizon ≤ tolerance)

/-- A successful radius search stays inside its budget and meets the exact
rational tolerance. -/
theorem searchHorizon_sound (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : radius.searchHorizon tolerance budget = some horizon) :
    horizon < budget ∧ radius horizon ≤ tolerance := by
  refine ⟨List.mem_range.mp (List.mem_of_find?_eq_some hsearch), ?_⟩
  have hp := List.find?_some
    (p := fun candidate => decide (radius candidate ≤ tolerance)) hsearch
  exact of_decide_eq_true hp

/-- A successful radius search has rejected every earlier horizon. -/
theorem searchHorizon_minimal (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : radius.searchHorizon tolerance budget = some horizon) :
    ∀ earlier < horizon, tolerance < radius earlier := by
  have hfind := List.find?_range_eq_some.mp hsearch
  intro earlier hearlier
  have hfailed := hfind.2.2 earlier hearlier
  apply lt_of_not_ge
  simpa using hfailed

/-- Search exhaustion says exactly that every tested horizon has radius
strictly above tolerance.  It says nothing about later horizons. -/
theorem searchHorizon_eq_none_iff (radius : ApproximationRadius)
    (tolerance : ℚ≥0) (budget : ℕ) :
    radius.searchHorizon tolerance budget = none ↔
      ∀ horizon < budget, tolerance < radius horizon := by
  simp [searchHorizon, List.find?_eq_none]

/-- Least acceptable horizon, given an explicit proof that one exists.  The
proof is erased from the computed natural number. -/
def leastHorizon (radius : ApproximationRadius) (tolerance : ℚ≥0)
    (hexists : ∃ horizon, radius horizon ≤ tolerance) : ℕ :=
  Nat.find hexists

/-- The explicit-existence computation returns the least acceptable
horizon. -/
theorem leastHorizon_spec (radius : ApproximationRadius)
    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, radius horizon ≤ tolerance) :
    radius (radius.leastHorizon tolerance hexists) ≤ tolerance ∧
      ∀ earlier < radius.leastHorizon tolerance hexists,
        tolerance < radius earlier := by
  unfold leastHorizon
  exact ⟨Nat.find_spec hexists,
    fun _ hlt => lt_of_not_ge (Nat.find_min hexists hlt)⟩

/-- A genuine vanishing-radius contract: every positive tolerance eventually
bounds all later radii.  This is proof data, not a convergence-rate oracle. -/
def Vanishes (radius : ApproximationRadius) : Prop :=
  ∀ tolerance : ℚ≥0, 0 < tolerance →
    ∃ cutoff, ∀ horizon, cutoff ≤ horizon → radius horizon ≤ tolerance

/-- A vanishing radius supplies an acceptable horizon for every positive
tolerance. -/
theorem Vanishes.exists_within {radius : ApproximationRadius}
    (hvanishes : radius.Vanishes) (tolerance : ℚ≥0)
    (htolerance : 0 < tolerance) :
    ∃ horizon, radius horizon ≤ tolerance := by
  obtain ⟨cutoff, hcutoff⟩ := hvanishes tolerance htolerance
  exact ⟨cutoff, hcutoff cutoff le_rfl⟩

end ApproximationRadius

/-- A state-prefix approximation scheme.  Both fields are executable finite
data; no infinite-path target is stored in the scheme. -/
structure StatePrefixApproximationScheme (A : KernelArena) (start : ℕ) where
  observable : (horizon : ℕ) → A.StatePrefix (start + horizon) → ℚ
  radius : ApproximationRadius

/-- An action-recording event-prefix approximation scheme.  Its observables
may inspect every selected-action occurrence in the prefix. -/
structure EventPrefixApproximationScheme (A : KernelArena) (start : ℕ) where
  observable : (horizon : ℕ) → A.EventPrefix (start + horizon) → ℚ
  radius : ApproximationRadius

namespace StatePrefixApproximationScheme

variable {A : KernelArena} {start : ℕ}
variable {initialPrefix : A.StatePrefix start}

variable (scheme : StatePrefixApproximationScheme A start)
variable (law : StateEffectivePathLawFrom A start initialPrefix)

/-- Exact rational center of a state-prefix scheme at one horizon. -/
def center
    (horizon : ℕ) : ℚ :=
  law.expectedPrefixValue horizon (scheme.observable horizon)

/-- Exact center and declared radius of a state-prefix scheme at one
horizon. -/
def estimate
    (horizon : ℕ) : RationalSchemeEstimate :=
  ⟨scheme.center law horizon, scheme.radius horizon⟩

/-- Rational endpoints generated by a state-prefix scheme at one horizon.
This is a scheme interval until a downstream semantic certificate identifies
a target that it encloses. -/
def interval
    (horizon : ℕ) : ℚ × ℚ :=
  (scheme.estimate law horizon).interval

/-- Search the state scheme's radius schedule without evaluating unused
prefix observables. -/
def searchHorizon
    (tolerance : ℚ≥0) (budget : ℕ) : Option ℕ :=
  scheme.radius.searchHorizon tolerance budget

/-- Return the first budgeted acceptable state horizon and compute its exact
scheme estimate. -/
def search
    (tolerance : ℚ≥0) (budget : ℕ) :
    Option (ℕ × RationalSchemeEstimate) :=
  (scheme.searchHorizon tolerance budget).map fun horizon =>
    (horizon, scheme.estimate law horizon)

/-- Successful state-scheme horizon search is within budget and within the
declared tolerance. -/
theorem searchHorizon_sound
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : scheme.searchHorizon tolerance budget = some horizon) :
    horizon < budget ∧ scheme.radius horizon ≤ tolerance :=
  ApproximationRadius.searchHorizon_sound
    scheme.radius tolerance budget horizon hsearch

/-- State-scheme search rejects every earlier radius. -/
theorem searchHorizon_minimal
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : scheme.searchHorizon tolerance budget = some horizon) :
    ∀ earlier < horizon, tolerance < scheme.radius earlier :=
  ApproximationRadius.searchHorizon_minimal
    scheme.radius tolerance budget horizon hsearch

/-- Exhausting state-scheme search is equivalent to every tested radius
exceeding tolerance. -/
theorem searchHorizon_eq_none_iff
    (tolerance : ℚ≥0) (budget : ℕ) :
    scheme.searchHorizon tolerance budget = none ↔
      ∀ horizon < budget, tolerance < scheme.radius horizon :=
  ApproximationRadius.searchHorizon_eq_none_iff
    scheme.radius tolerance budget

/-- Every returned state result is the exact estimate at the first acceptable
horizon. -/
theorem search_sound
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (result : RationalSchemeEstimate)
    (hsearch : scheme.search law tolerance budget = some (horizon, result)) :
    horizon < budget ∧
      scheme.estimate law horizon = result ∧
      result.radius ≤ tolerance := by
  obtain ⟨selected, hselected, heq⟩ := Option.map_eq_some_iff.mp hsearch
  have hsound := scheme.searchHorizon_sound
    tolerance budget selected hselected
  cases heq
  exact ⟨hsound.1, rfl, hsound.2⟩

/-- Least acceptable state-scheme horizon from an explicit existence proof. -/
def leastHorizon
    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, scheme.radius horizon ≤ tolerance) : ℕ :=
  scheme.radius.leastHorizon tolerance hexists

/-- The explicit-existence state computation returns the least acceptable
horizon. -/
theorem leastHorizon_spec
    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, scheme.radius horizon ≤ tolerance) :
    scheme.radius (scheme.leastHorizon tolerance hexists) ≤ tolerance ∧
      ∀ earlier < scheme.leastHorizon tolerance hexists,
        tolerance < scheme.radius earlier :=
  ApproximationRadius.leastHorizon_spec scheme.radius tolerance hexists

/-- Compute the state estimate at the least horizon certified to exist. -/
def approximateAtLeastHorizon

    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, scheme.radius horizon ≤ tolerance) :
    ℕ × RationalSchemeEstimate :=
  let horizon := scheme.leastHorizon tolerance hexists
  (horizon, scheme.estimate law horizon)

end StatePrefixApproximationScheme

namespace EventPrefixApproximationScheme

variable {A : KernelArena} {start : ℕ}
variable {initialPrefix : A.EventPrefix start}

variable (scheme : EventPrefixApproximationScheme A start)
variable (law : EventEffectivePathLawFrom A start initialPrefix)

/-- Exact rational center of an event-prefix scheme at one horizon. -/
def center
    (horizon : ℕ) : ℚ :=
  law.expectedPrefixValue horizon (scheme.observable horizon)

/-- Exact center and declared radius of an event-prefix scheme at one
horizon. -/
def estimate
    (horizon : ℕ) : RationalSchemeEstimate :=
  ⟨scheme.center law horizon, scheme.radius horizon⟩

/-- Rational endpoints generated by an event-prefix scheme at one horizon. -/
def interval
    (horizon : ℕ) : ℚ × ℚ :=
  (scheme.estimate law horizon).interval

/-- Search the event scheme's radius schedule without evaluating unused
prefix observables. -/
def searchHorizon
    (tolerance : ℚ≥0) (budget : ℕ) : Option ℕ :=
  scheme.radius.searchHorizon tolerance budget

/-- Return the first budgeted acceptable event horizon and compute its exact
scheme estimate. -/
def search
    (tolerance : ℚ≥0) (budget : ℕ) :
    Option (ℕ × RationalSchemeEstimate) :=
  (scheme.searchHorizon tolerance budget).map fun horizon =>
    (horizon, scheme.estimate law horizon)

/-- Successful event-scheme horizon search is within budget and within the
declared tolerance. -/
theorem searchHorizon_sound
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : scheme.searchHorizon tolerance budget = some horizon) :
    horizon < budget ∧ scheme.radius horizon ≤ tolerance :=
  ApproximationRadius.searchHorizon_sound
    scheme.radius tolerance budget horizon hsearch

/-- Event-scheme search rejects every earlier radius. -/
theorem searchHorizon_minimal
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (hsearch : scheme.searchHorizon tolerance budget = some horizon) :
    ∀ earlier < horizon, tolerance < scheme.radius earlier :=
  ApproximationRadius.searchHorizon_minimal
    scheme.radius tolerance budget horizon hsearch

/-- Exhausting event-scheme search is equivalent to every tested radius
exceeding tolerance. -/
theorem searchHorizon_eq_none_iff
    (tolerance : ℚ≥0) (budget : ℕ) :
    scheme.searchHorizon tolerance budget = none ↔
      ∀ horizon < budget, tolerance < scheme.radius horizon :=
  ApproximationRadius.searchHorizon_eq_none_iff
    scheme.radius tolerance budget

/-- Every returned event result is the exact estimate at the first acceptable
horizon. -/
theorem search_sound
    (tolerance : ℚ≥0) (budget horizon : ℕ)
    (result : RationalSchemeEstimate)
    (hsearch : scheme.search law tolerance budget = some (horizon, result)) :
    horizon < budget ∧
      scheme.estimate law horizon = result ∧
      result.radius ≤ tolerance := by
  obtain ⟨selected, hselected, heq⟩ := Option.map_eq_some_iff.mp hsearch
  have hsound := scheme.searchHorizon_sound
    tolerance budget selected hselected
  cases heq
  exact ⟨hsound.1, rfl, hsound.2⟩

/-- Least acceptable event-scheme horizon from an explicit existence proof. -/
def leastHorizon
    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, scheme.radius horizon ≤ tolerance) : ℕ :=
  scheme.radius.leastHorizon tolerance hexists

/-- The explicit-existence event computation returns the least acceptable
horizon. -/
theorem leastHorizon_spec
    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, scheme.radius horizon ≤ tolerance) :
    scheme.radius (scheme.leastHorizon tolerance hexists) ≤ tolerance ∧
      ∀ earlier < scheme.leastHorizon tolerance hexists,
        tolerance < scheme.radius earlier :=
  ApproximationRadius.leastHorizon_spec scheme.radius tolerance hexists

/-- Compute the event estimate at the least horizon certified to exist. -/
def approximateAtLeastHorizon

    (tolerance : ℚ≥0)
    (hexists : ∃ horizon, scheme.radius horizon ≤ tolerance) :
    ℕ × RationalSchemeEstimate :=
  let horizon := scheme.leastHorizon tolerance hexists
  (horizon, scheme.estimate law horizon)

end EventPrefixApproximationScheme

namespace StateEffectivePathLawFrom

variable {A : KernelArena} {start : ℕ}
variable {initialPrefix : A.StatePrefix start}

variable (law : StateEffectivePathLawFrom A start initialPrefix)

/-- Radius-zero estimate of one exact state-prefix observable. -/
def exactPrefixEstimate
    (horizon : ℕ) (value : A.StatePrefix (start + horizon) → ℚ) :
    RationalSchemeEstimate :=
  ⟨law.expectedPrefixValue horizon value, 0⟩

/-- Radius-zero estimate of an earlier state-prefix cylinder, evaluated at a
later horizon. -/
def exactCylinderEstimate
    (earlier extra : ℕ)
    (value : A.StatePrefix (start + earlier) → ℚ) :
    RationalSchemeEstimate :=
  law.exactPrefixEstimate (earlier + extra) fun history =>
    value (StatePrefix.truncate history (start + earlier) (by omega))

/-- Exact cylinder coherence makes the later zero-radius state estimate
identical to the estimate at its determining horizon. -/
theorem exactCylinderEstimate_eq
    (earlier extra : ℕ)
    (value : A.StatePrefix (start + earlier) → ℚ) :
    law.exactCylinderEstimate earlier extra value =
      law.exactPrefixEstimate earlier value := by
  apply RationalSchemeEstimate.ext
  · exact law.expectedPrefixValue_extend earlier extra value
  · rfl

/-- An exact state-prefix estimate has a singleton scheme interval. -/
@[simp]
theorem exactPrefixEstimate_interval
    (horizon : ℕ) (value : A.StatePrefix (start + horizon) → ℚ) :
    (law.exactPrefixEstimate horizon value).interval =
      (law.expectedPrefixValue horizon value,
        law.expectedPrefixValue horizon value) := by
  simp [exactPrefixEstimate, RationalSchemeEstimate.interval]

end StateEffectivePathLawFrom

namespace EventEffectivePathLawFrom

variable {A : KernelArena} {start : ℕ}
variable {initialPrefix : A.EventPrefix start}

variable (law : EventEffectivePathLawFrom A start initialPrefix)

/-- Radius-zero estimate of one exact action-recording event-prefix
observable. -/
def exactPrefixEstimate
    (horizon : ℕ) (value : A.EventPrefix (start + horizon) → ℚ) :
    RationalSchemeEstimate :=
  ⟨law.expectedPrefixValue horizon value, 0⟩

/-- Radius-zero estimate of an earlier event-prefix cylinder, evaluated at a
later horizon.  The retained cylinder may inspect every action occurrence. -/
def exactCylinderEstimate
    (earlier extra : ℕ)
    (value : A.EventPrefix (start + earlier) → ℚ) :
    RationalSchemeEstimate :=
  law.exactPrefixEstimate (earlier + extra) fun history =>
    value (EventPrefix.truncate history (start + earlier) (by omega))

/-- Exact cylinder coherence makes the later zero-radius event estimate
identical to the estimate at its determining horizon. -/
theorem exactCylinderEstimate_eq
    (earlier extra : ℕ)
    (value : A.EventPrefix (start + earlier) → ℚ) :
    law.exactCylinderEstimate earlier extra value =
      law.exactPrefixEstimate earlier value := by
  apply RationalSchemeEstimate.ext
  · exact law.expectedPrefixValue_extend earlier extra value
  · rfl

/-- An exact event-prefix estimate has a singleton scheme interval. -/
@[simp]
theorem exactPrefixEstimate_interval
    (horizon : ℕ) (value : A.EventPrefix (start + horizon) → ℚ) :
    (law.exactPrefixEstimate horizon value).interval =
      (law.expectedPrefixValue horizon value,
        law.expectedPrefixValue horizon value) := by
  simp [exactPrefixEstimate, RationalSchemeEstimate.interval]

end EventEffectivePathLawFrom

namespace StatePrefixApproximationScheme

variable {A : KernelArena} {start : ℕ}

/-- View a state-prefix scheme through complete action-recording event
prefixes.  Only the observable is projected; the radius schedule is retained
definitionally. -/
def toEvent (scheme : StatePrefixApproximationScheme A start) :
    EventPrefixApproximationScheme A start where
  observable horizon history := scheme.observable horizon history.states
  radius := scheme.radius

/-- Projecting a state scheme to an event law computes the explicit
state-prefix expectation of that law. -/
theorem toEvent_center (scheme : StatePrefixApproximationScheme A start)
    {initialPrefix : A.EventPrefix start}
    (law : EventEffectivePathLawFrom A start initialPrefix)
    (horizon : ℕ) :
    scheme.toEvent.center law horizon =
      law.expectedStatePrefixValue horizon (scheme.observable horizon) := by
  rw [EventPrefixApproximationScheme.center]
  exact
    (law.expectedStatePrefixValue_eq_expectedPrefixValue_states
      horizon (scheme.observable horizon)).symm

/-- Action-recording execution of a state-history policy preserves the full
state-scheme estimate after the event-state projection. -/
theorem toEvent_estimate_effectivePathLawFrom
    [(state : A.State) → Decidable (IsEmpty (A.Action state))]
    (scheme : StatePrefixApproximationScheme A start)
    (policy : A.StateHistoryPolicy)
    (initialPrefix : A.EventPrefix start) (horizon : ℕ) :
    scheme.toEvent.estimate
        ((policy.toEventHistoryPolicy).effectivePathLawFrom
          start initialPrefix) horizon =
      scheme.estimate
        (policy.effectivePathLawFrom start initialPrefix.states) horizon := by
  apply RationalSchemeEstimate.ext
  · rw [EventPrefixApproximationScheme.estimate,
      StatePrefixApproximationScheme.estimate]
    rw [scheme.toEvent_center]
    exact
      EventHistoryPolicy.toEventHistoryPolicy_effectivePathLawFrom_expectedStatePrefixValue
        policy start initialPrefix horizon (scheme.observable horizon)
  · rfl

/-- The corresponding state and projected-event scheme intervals are equal. -/
theorem toEvent_interval_effectivePathLawFrom
    [(state : A.State) → Decidable (IsEmpty (A.Action state))]
    (scheme : StatePrefixApproximationScheme A start)
    (policy : A.StateHistoryPolicy)
    (initialPrefix : A.EventPrefix start) (horizon : ℕ) :
    scheme.toEvent.interval
        ((policy.toEventHistoryPolicy).effectivePathLawFrom
          start initialPrefix) horizon =
      scheme.interval
        (policy.effectivePathLawFrom start initialPrefix.states) horizon := by
  exact congrArg RationalSchemeEstimate.interval
    (scheme.toEvent_estimate_effectivePathLawFrom
      policy initialPrefix horizon)

/-- State and projected-event schemes perform the same radius-only horizon
search. -/
@[simp]
theorem toEvent_searchHorizon
    (scheme : StatePrefixApproximationScheme A start)
    (tolerance : ℚ≥0) (budget : ℕ) :
    scheme.toEvent.searchHorizon tolerance budget =
      scheme.searchHorizon tolerance budget :=
  rfl

end StatePrefixApproximationScheme

end KernelArena
