/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.StrategicGame.NashEquilibrium

/-!
# EconCSLib.GameTheory.GameForm.Basic

A small representation-neutral strategy/outcome semantic layer.

`GameForm` deliberately forgets histories, observations, chance syntax, and
subgames.  A concrete game language compiles to per-player strategy spaces and
an outcome evaluator.  `GameForm.Iso` then records per-player strategy
equivalences, an outcome equivalence, and the commuting evaluation square.

This is the appropriate layer for transferring outcome and pure-Nash facts.
Subgame-perfect equilibrium and perfect-recall facts must be transferred before
compilation, or through stronger structures that also remember subgames and
information.

## Main definitions

* `GameForm` — game-bound strategy spaces and deterministic outcomes.
* `GameForm.Hom` — playerwise strategy maps with a commuting outcome map.
* `GameForm.Iso` — strategy/outcome isomorphism with evaluator compatibility.
* `GameForm.IsNash` — pure Nash relative to an outcome-utility function.

## Main results

* `Hom.mapProfile_deviate` — playerwise strategy maps preserve unilateral
  changes.
* `Hom.ext`, `Hom.refl_trans`, `Hom.trans_refl`, and `Hom.trans_assoc` —
  extensionality and category-style normalization for game-form morphisms.
* `IsNash.comap` — Nash of a mapped target profile reflects to the source.
* `Hom.OutcomeDeviationCompleteAt` — every target deviation is represented
  by a source deviation with exactly the same mapped outcome.
* `IsNash.map_of_outcomeDeviationCompleteAt` — forward Nash transfer under
  semantic deviation coverage, without requiring strategy surjectivity.
* `IsNash.map_of_strategySurjective` — forward Nash transfer when every target
  deviation lifts.
* `Iso.mapProfile_deviate` — profile isomorphisms preserve unilateral changes.
* `Iso.ext`, `Iso.refl_trans`, `Iso.trans_refl`, and `Iso.trans_assoc` —
  extensionality and category-style normalization for game-form isomorphisms.
* `IsNash.map` and `Iso.isNash_iff` — utility-compatible isomorphisms preserve
  pure Nash equilibrium in both directions.
-/

universe uN uS uO uT uP

/-- A deterministic strategy/outcome game form.

Utilities are not stored: the same outcome semantics may be interpreted by
different utility functions. -/
structure GameForm (N : Type uN) where
  /-- Pure strategy space of each player. -/
  Strategy : N → Type uS
  /-- Representation-neutral outcome type. -/
  Outcome : Type uO
  /-- Outcome generated by a pure strategy profile. -/
  outcome : (∀ i, Strategy i) → Outcome

namespace GameForm

variable {N : Type*}

/-- The game-bound pure-profile type. -/
abbrev Profile (G : GameForm N) :=
  ∀ i, G.Strategy i

/-- Unilateral pure-strategy deviation. -/
abbrev deviate {G : GameForm N} [DecidableEq N]
    (σ : G.Profile) (i : N) (strategy : G.Strategy i) :
    G.Profile :=
  Function.update σ i strategy

/-- Interpret a game form as the existing `StrategicGame` using an outcome
utility function. -/
def toStrategicGame (G : GameForm N) {U : Type*}
    (utility : G.Outcome → N → U) :
    StrategicGame N U where
  strategy := G.Strategy
  payoff σ := utility (G.outcome σ)

/-- Pure Nash equilibrium for a game form under an outcome-utility
interpretation. -/
def IsNash {U : Type*} [DecidableEq N] [Preorder U]
    (G : GameForm N) (utility : G.Outcome → N → U)
    (σ : G.Profile) : Prop :=
  ∀ (i : N) (strategy : G.Strategy i),
    utility (G.outcome (G.deviate σ i strategy)) i ≤
      utility (G.outcome σ) i

/-- `GameForm.IsNash` is exactly Nash equilibrium in its strategic-game
interpretation. -/
theorem isNash_iff_toStrategicGame
    {U : Type*} [DecidableEq N] [Preorder U]
    (G : GameForm N) (utility : G.Outcome → N → U)
    (σ : G.Profile) :
    G.IsNash utility σ ↔
      _root_.IsNashEquilibrium (G.toStrategicGame utility) σ :=
  Iff.rfl

/-! ### Morphisms -/

/-- A morphism between deterministic game forms.

Strategies map player by player, outcomes map forward, and the evaluator
square commutes. No injectivity or surjectivity is required. Consequently,
Nash equilibrium of the mapped target profile reflects to the source: every
source deviation has a mapped target deviation. Forward Nash transfer needs
an additional deviation-lifting condition and is deliberately not built into
this structure. -/
structure Hom (G H : GameForm N) where
  /-- Map each player's source strategy into a target strategy. -/
  strategyMap : (i : N) → G.Strategy i → H.Strategy i
  /-- Map source outcomes into target outcomes. -/
  outcomeMap : G.Outcome → H.Outcome
  /-- Strategy and outcome mappings commute with evaluation. -/
  map_outcome :
    ∀ profile : G.Profile,
      outcomeMap (G.outcome profile) =
        H.outcome (fun i => strategyMap i (profile i))

namespace Hom

variable {G H K : GameForm N}

/-- Game-form morphisms are equal when their strategy and outcome maps are
equal. The evaluator-square field is proposition-valued and therefore follows
by proof irrelevance. -/
@[ext]
theorem ext (f g : G.Hom H)
    (hstrategy : f.strategyMap = g.strategyMap)
    (houtcome : f.outcomeMap = g.outcomeMap) :
    f = g := by
  cases f
  cases g
  cases hstrategy
  cases houtcome
  rfl

/-- Map a complete source profile player by player. -/
def mapProfile (f : G.Hom H) (profile : G.Profile) : H.Profile :=
  fun i => f.strategyMap i (profile i)

@[simp]
theorem mapProfile_apply (f : G.Hom H) (profile : G.Profile) (i : N) :
    f.mapProfile profile i = f.strategyMap i (profile i) :=
  rfl

/-- The morphism evaluator square stated using `mapProfile`. -/
theorem map_outcome_mapProfile (f : G.Hom H) (profile : G.Profile) :
    f.outcomeMap (G.outcome profile) =
      H.outcome (f.mapProfile profile) :=
  f.map_outcome profile

/-- Playerwise strategy mapping commutes with unilateral deviation. -/
theorem mapProfile_deviate [DecidableEq N]
    (f : G.Hom H) (profile : G.Profile) (i : N)
    (strategy : G.Strategy i) :
    f.mapProfile (G.deviate profile i strategy) =
      H.deviate (f.mapProfile profile) i
        (f.strategyMap i strategy) := by
  funext j
  by_cases hji : j = i
  · subst j
    simp [mapProfile, GameForm.deviate]
  · simp [mapProfile, GameForm.deviate, hji]

/-- Identity game-form morphism. -/
def refl (G : GameForm N) : G.Hom G where
  strategyMap := fun _ strategy => strategy
  outcomeMap := id
  map_outcome := by
    intro profile
    rfl

/-- Compose game-form morphisms. -/
def trans (f : G.Hom H) (g : H.Hom K) : G.Hom K where
  strategyMap := fun i strategy =>
    g.strategyMap i (f.strategyMap i strategy)
  outcomeMap := g.outcomeMap ∘ f.outcomeMap
  map_outcome := by
    intro profile
    change
      g.outcomeMap (f.outcomeMap (G.outcome profile)) =
        K.outcome (g.mapProfile (f.mapProfile profile))
    rw [f.map_outcome_mapProfile, g.map_outcome_mapProfile]

/-- Mapping a profile through the identity morphism is a no-op. -/
@[simp]
theorem refl_mapProfile (G : GameForm N) (profile : G.Profile) :
    (refl G).mapProfile profile = profile :=
  rfl

/-- Profile mapping is functorial under morphism composition. -/
@[simp]
theorem trans_mapProfile
    (f : G.Hom H) (g : H.Hom K) (profile : G.Profile) :
    (f.trans g).mapProfile profile =
      g.mapProfile (f.mapProfile profile) :=
  rfl

/-- The identity morphism is a left unit for composition. -/
@[simp]
theorem refl_trans (f : G.Hom H) :
    (refl G).trans f = f := by
  ext <;> rfl

/-- The identity morphism is a right unit for composition. -/
@[simp]
theorem trans_refl (f : G.Hom H) :
    f.trans (refl H) = f := by
  ext <;> rfl

/-- Composition of game-form morphisms is associative. -/
theorem trans_assoc {L : GameForm N}
    (f : G.Hom H) (g : H.Hom K) (h : K.Hom L) :
    (f.trans g).trans h = f.trans (g.trans h) := by
  ext <;> rfl

/-- Utilities are compatible with a game-form morphism when mapping an outcome
does not change any player's utility. -/
def UtilityCompatible {U : Type*} (f : G.Hom H)
    (sourceUtility : G.Outcome → N → U)
    (targetUtility : H.Outcome → N → U) : Prop :=
  ∀ (outcome : G.Outcome) (i : N),
    targetUtility (f.outcomeMap outcome) i =
      sourceUtility outcome i

/-- Every target player strategy is represented by a source strategy. -/
def StrategySurjective (f : G.Hom H) : Prop :=
  ∀ i : N, Function.Surjective (f.strategyMap i)

/-- Every unilateral target deviation at a mapped profile is semantically
represented by a source deviation.

This is strictly weaker than strategy surjectivity.  The target strategy need
not be the image of a source strategy; only its resulting outcome in the
current opponents' context must equal the mapped outcome of some source
deviation.  This is the appropriate condition for realization-equivalent
strategy models such as mixed and behavioral EFG strategies. -/
def OutcomeDeviationCompleteAt [DecidableEq N]
    (f : G.Hom H) (profile : G.Profile) : Prop :=
  ∀ (i : N) (targetStrategy : H.Strategy i),
    ∃ sourceStrategy : G.Strategy i,
      H.outcome
          (H.deviate (f.mapProfile profile)
            i targetStrategy) =
        f.outcomeMap
          (G.outcome
            (G.deviate profile i sourceStrategy))

/-- Semantic deviation completeness at every source profile. -/
def OutcomeDeviationComplete [DecidableEq N]
    (f : G.Hom H) : Prop :=
  ∀ profile : G.Profile,
    f.OutcomeDeviationCompleteAt profile

/-- Literal strategy surjectivity implies semantic deviation completeness. -/
theorem StrategySurjective.outcomeDeviationCompleteAt
    [DecidableEq N]
    {f : G.Hom H}
    (hsurjective : f.StrategySurjective)
    (profile : G.Profile) :
    f.OutcomeDeviationCompleteAt profile := by
  intro i targetStrategy
  obtain ⟨sourceStrategy, rfl⟩ :=
    hsurjective i targetStrategy
  refine ⟨sourceStrategy, ?_⟩
  rw [← f.mapProfile_deviate,
    ← f.map_outcome_mapProfile]

/-- Global strategy surjectivity implies global semantic deviation
completeness. -/
theorem StrategySurjective.outcomeDeviationComplete
    [DecidableEq N]
    {f : G.Hom H}
    (hsurjective : f.StrategySurjective) :
    f.OutcomeDeviationComplete :=
  fun profile =>
    hsurjective.outcomeDeviationCompleteAt profile

/-- Semantic deviation completeness composes at corresponding profiles. -/
theorem OutcomeDeviationCompleteAt.trans
    [DecidableEq N]
    {f : G.Hom H} {g : H.Hom K}
    {profile : G.Profile}
    (hf : f.OutcomeDeviationCompleteAt profile)
    (hg :
      g.OutcomeDeviationCompleteAt
        (f.mapProfile profile)) :
    (f.trans g).OutcomeDeviationCompleteAt profile := by
  intro i targetStrategy
  obtain ⟨middleStrategy, hmiddle⟩ :=
    hg i targetStrategy
  obtain ⟨sourceStrategy, hsource⟩ :=
    hf i middleStrategy
  refine ⟨sourceStrategy, ?_⟩
  change
    K.outcome
        (K.deviate
          (g.mapProfile (f.mapProfile profile))
          i targetStrategy) =
      g.outcomeMap
        (f.outcomeMap
          (G.outcome
            (G.deviate profile i sourceStrategy)))
  rw [hmiddle, hsource]

/-- Globally deviation-complete morphisms compose. -/
theorem OutcomeDeviationComplete.trans
    [DecidableEq N]
    {f : G.Hom H} {g : H.Hom K}
    (hf : f.OutcomeDeviationComplete)
    (hg : g.OutcomeDeviationComplete) :
    (f.trans g).OutcomeDeviationComplete := by
  intro profile
  exact
    (hf profile).trans
      (hg (f.mapProfile profile))

end Hom

/-- Nash equilibrium of a mapped target profile reflects through any
utility-compatible game-form morphism.

The target may admit additional deviations not represented in the source.
Those only strengthen the target Nash hypothesis; every source deviation is
still tested through its playerwise image. -/
theorem IsNash.comap {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (f : G.Hom H)
    (hutility : f.UtilityCompatible sourceUtility targetUtility)
    {profile : G.Profile}
    (hNash : H.IsNash targetUtility (f.mapProfile profile)) :
    G.IsNash sourceUtility profile := by
  intro i sourceStrategy
  have htarget :=
    hNash i (f.strategyMap i sourceStrategy)
  rw [← f.mapProfile_deviate] at htarget
  rw [← f.map_outcome_mapProfile
      (G.deviate profile i sourceStrategy),
    ← f.map_outcome_mapProfile profile] at htarget
  rw [hutility (G.outcome (G.deviate profile i sourceStrategy)) i,
    hutility (G.outcome profile) i] at htarget
  exact htarget

/-- A utility-compatible morphism maps Nash equilibrium forward whenever
every unilateral target deviation is represented by a source deviation with
the same mapped outcome.

Unlike `map_of_strategySurjective`, this theorem allows distinct and
non-isomorphic strategy spaces. -/
theorem IsNash.map_of_outcomeDeviationCompleteAt
    {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (f : G.Hom H)
    (hutility : f.UtilityCompatible
      sourceUtility targetUtility)
    {profile : G.Profile}
    (hcomplete :
      f.OutcomeDeviationCompleteAt profile)
    (hNash : G.IsNash sourceUtility profile) :
    H.IsNash targetUtility
      (f.mapProfile profile) := by
  intro i targetStrategy
  obtain ⟨sourceStrategy, hdeviation⟩ :=
    hcomplete i targetStrategy
  rw [hdeviation]
  rw [← f.map_outcome_mapProfile profile]
  rw [hutility
      (G.outcome
        (G.deviate profile i sourceStrategy)) i,
    hutility (G.outcome profile) i]
  exact hNash i sourceStrategy

/-- Utility-compatible game-form morphisms map Nash equilibrium forward when
every target unilateral deviation lifts to a source strategy. -/
theorem IsNash.map_of_strategySurjective
    {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (f : G.Hom H)
    (hutility : f.UtilityCompatible
      sourceUtility targetUtility)
    (hsurjective : f.StrategySurjective)
    {profile : G.Profile}
    (hNash : G.IsNash sourceUtility profile) :
    H.IsNash targetUtility
      (f.mapProfile profile) := by
  exact
    hNash.map_of_outcomeDeviationCompleteAt
      f hutility
      (hsurjective.outcomeDeviationCompleteAt
        profile)

/-- Exact two-way Nash transfer under semantic deviation completeness at the
source profile. -/
theorem Hom.isNash_iff_of_outcomeDeviationCompleteAt
    {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    (f : G.Hom H)
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (hutility : f.UtilityCompatible
      sourceUtility targetUtility)
    (profile : G.Profile)
    (hcomplete :
      f.OutcomeDeviationCompleteAt profile) :
    G.IsNash sourceUtility profile ↔
      H.IsNash targetUtility
        (f.mapProfile profile) := by
  constructor
  · exact fun hNash =>
      hNash.map_of_outcomeDeviationCompleteAt
        f hutility hcomplete
  · exact fun hNash =>
      hNash.comap f hutility

/-- A utility-compatible, strategy-surjective game-form morphism preserves
Nash equilibrium in both directions. -/
theorem Hom.isNash_iff_of_strategySurjective
    {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    (f : G.Hom H)
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (hutility : f.UtilityCompatible
      sourceUtility targetUtility)
    (hsurjective : f.StrategySurjective)
    (profile : G.Profile) :
    G.IsNash sourceUtility profile ↔
      H.IsNash targetUtility
        (f.mapProfile profile) := by
  constructor
  · exact fun hNash =>
      hNash.map_of_strategySurjective
        f hutility hsurjective
  · exact fun hNash =>
      hNash.comap f hutility

/-! ### Isomorphisms -/

/-- An isomorphism between deterministic game forms.

The strategy equivalence is player-indexed.  The evaluator square says that
mapping a source outcome equals evaluating the mapped source profile. -/
structure Iso (G H : GameForm N) where
  /-- Equivalence of every player's pure strategy space. -/
  strategyEquiv : (i : N) → G.Strategy i ≃ H.Strategy i
  /-- Equivalence of outcome spaces. -/
  outcomeEquiv : G.Outcome ≃ H.Outcome
  /-- Strategy and outcome mappings commute with evaluation. -/
  map_outcome :
    ∀ σ : G.Profile,
      outcomeEquiv (G.outcome σ) =
        H.outcome (fun i => strategyEquiv i (σ i))

namespace Iso

variable {G H K : GameForm N}

/-- Game-form isomorphisms are equal when their strategy and outcome
equivalences are equal. The evaluator square then follows by proof
irrelevance. -/
@[ext]
theorem ext (e f : G.Iso H)
    (hstrategy : e.strategyEquiv = f.strategyEquiv)
    (houtcome : e.outcomeEquiv = f.outcomeEquiv) :
    e = f := by
  cases e
  cases f
  cases hstrategy
  cases houtcome
  rfl

/-- Forget invertibility and view a game-form isomorphism as a morphism. -/
def toHom (e : G.Iso H) : G.Hom H where
  strategyMap := fun i => e.strategyEquiv i
  outcomeMap := e.outcomeEquiv
  map_outcome := e.map_outcome

/-- Map a complete strategy profile along a game-form isomorphism. -/
def mapProfile (e : G.Iso H) (σ : G.Profile) : H.Profile :=
  fun i => e.strategyEquiv i (σ i)

/-- Map a target profile back along a game-form isomorphism. -/
def unmapProfile (e : G.Iso H) (σ : H.Profile) : G.Profile :=
  fun i => (e.strategyEquiv i).symm (σ i)

@[simp]
theorem mapProfile_apply (e : G.Iso H) (σ : G.Profile) (i : N) :
    e.mapProfile σ i = e.strategyEquiv i (σ i) := rfl

@[simp]
theorem unmapProfile_apply (e : G.Iso H) (σ : H.Profile) (i : N) :
    e.unmapProfile σ i = (e.strategyEquiv i).symm (σ i) := rfl

@[simp]
theorem mapProfile_unmapProfile (e : G.Iso H) (σ : H.Profile) :
    e.mapProfile (e.unmapProfile σ) = σ := by
  funext i
  exact (e.strategyEquiv i).apply_symm_apply (σ i)

@[simp]
theorem unmapProfile_mapProfile (e : G.Iso H) (σ : G.Profile) :
    e.unmapProfile (e.mapProfile σ) = σ := by
  funext i
  exact (e.strategyEquiv i).symm_apply_apply (σ i)

/-- Mapping profiles commutes with unilateral deviation. -/
theorem mapProfile_deviate [DecidableEq N]
    (e : G.Iso H) (σ : G.Profile) (i : N)
    (strategy : G.Strategy i) :
    e.mapProfile (G.deviate σ i strategy) =
      H.deviate (e.mapProfile σ) i (e.strategyEquiv i strategy) := by
  funext j
  by_cases hji : j = i
  · subst j
    simp [mapProfile, GameForm.deviate]
  · simp [mapProfile, GameForm.deviate, hji]

/-- Identity game-form isomorphism. -/
def refl (G : GameForm N) : G.Iso G where
  strategyEquiv := fun _ => Equiv.refl _
  outcomeEquiv := Equiv.refl _
  map_outcome := by
    intro σ
    rfl

/-- Reverse a game-form isomorphism. -/
def symm (e : G.Iso H) : H.Iso G where
  strategyEquiv := fun i => (e.strategyEquiv i).symm
  outcomeEquiv := e.outcomeEquiv.symm
  map_outcome := by
    intro σ
    apply e.outcomeEquiv.injective
    rw [e.outcomeEquiv.apply_symm_apply]
    symm
    calc
      e.outcomeEquiv (G.outcome (e.unmapProfile σ)) =
          H.outcome (e.mapProfile (e.unmapProfile σ)) :=
        e.map_outcome (e.unmapProfile σ)
      _ = H.outcome σ := by
        rw [e.mapProfile_unmapProfile]

/-- Compose game-form isomorphisms. -/
def trans (e : G.Iso H) (f : H.Iso K) : G.Iso K where
  strategyEquiv := fun i => (e.strategyEquiv i).trans (f.strategyEquiv i)
  outcomeEquiv := e.outcomeEquiv.trans f.outcomeEquiv
  map_outcome := by
    intro σ
    change f.outcomeEquiv (e.outcomeEquiv (G.outcome σ)) =
      K.outcome (f.mapProfile (e.mapProfile σ))
    rw [e.map_outcome, f.map_outcome]
    rfl

/-- Mapping a profile through the identity isomorphism is a no-op. -/
@[simp]
theorem refl_mapProfile (G : GameForm N) (profile : G.Profile) :
    (refl G).mapProfile profile = profile :=
  rfl

/-- Profile mapping is functorial under isomorphism composition. -/
@[simp]
theorem trans_mapProfile
    (e : G.Iso H) (f : H.Iso K) (profile : G.Profile) :
    (e.trans f).mapProfile profile =
      f.mapProfile (e.mapProfile profile) :=
  rfl

/-- The identity isomorphism is a left unit for composition. -/
@[simp]
theorem refl_trans (e : G.Iso H) :
    (refl G).trans e = e := by
  apply Iso.ext
  · funext i
    apply Equiv.ext
    intro strategy
    rfl
  · apply Equiv.ext
    intro outcome
    rfl

/-- The identity isomorphism is a right unit for composition. -/
@[simp]
theorem trans_refl (e : G.Iso H) :
    e.trans (refl H) = e := by
  apply Iso.ext
  · funext i
    apply Equiv.ext
    intro strategy
    rfl
  · apply Equiv.ext
    intro outcome
    rfl

/-- Composition of game-form isomorphisms is associative. -/
theorem trans_assoc {L : GameForm N}
    (e : G.Iso H) (f : H.Iso K) (g : K.Iso L) :
    (e.trans f).trans g = e.trans (f.trans g) := by
  apply Iso.ext
  · funext i
    apply Equiv.ext
    intro strategy
    rfl
  · apply Equiv.ext
    intro outcome
    rfl

/-- Utilities are compatible with a game-form isomorphism when mapping an
outcome does not change any player's utility. -/
def UtilityCompatible {U : Type*} (e : G.Iso H)
    (sourceUtility : G.Outcome → N → U)
    (targetUtility : H.Outcome → N → U) : Prop :=
  ∀ (outcome : G.Outcome) (i : N),
    targetUtility (e.outcomeEquiv outcome) i =
      sourceUtility outcome i

/-- Utility compatibility reverses with a game-form isomorphism. -/
theorem UtilityCompatible.symm {U : Type*} (e : G.Iso H)
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (hutility : e.UtilityCompatible sourceUtility targetUtility) :
    e.symm.UtilityCompatible targetUtility sourceUtility := by
  intro outcome i
  have h := hutility (e.outcomeEquiv.symm outcome) i
  simpa using h.symm

end Iso

/-- Utility-compatible game-form isomorphisms map pure Nash equilibria
forward. -/
theorem IsNash.map {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (e : G.Iso H)
    (hutility : e.UtilityCompatible sourceUtility targetUtility)
    {σ : G.Profile} (hNash : G.IsNash sourceUtility σ) :
    H.IsNash targetUtility (e.mapProfile σ) := by
  intro i targetStrategy
  let sourceStrategy := (e.strategyEquiv i).symm targetStrategy
  have hdeviation :
      H.deviate (e.mapProfile σ) i targetStrategy =
        e.mapProfile (G.deviate σ i sourceStrategy) := by
    rw [e.mapProfile_deviate]
    simp [sourceStrategy]
  have houtcomeDeviation :
      H.outcome (H.deviate (e.mapProfile σ) i targetStrategy) =
        e.outcomeEquiv
          (G.outcome (G.deviate σ i sourceStrategy)) := by
    rw [hdeviation]
    exact (e.map_outcome _).symm
  have houtcome :
      H.outcome (e.mapProfile σ) =
        e.outcomeEquiv (G.outcome σ) :=
    (e.map_outcome σ).symm
  rw [houtcomeDeviation, houtcome,
    hutility (G.outcome (G.deviate σ i sourceStrategy)) i,
    hutility (G.outcome σ) i]
  exact hNash i sourceStrategy

namespace Iso

/-- Utility-compatible game-form isomorphisms preserve pure Nash equilibrium
in both directions. -/
theorem isNash_iff {U : Type*} [DecidableEq N] [Preorder U]
    {G H : GameForm N}
    (e : G.Iso H)
    {sourceUtility : G.Outcome → N → U}
    {targetUtility : H.Outcome → N → U}
    (hutility : e.UtilityCompatible sourceUtility targetUtility)
    (σ : G.Profile) :
    G.IsNash sourceUtility σ ↔
      H.IsNash targetUtility (e.mapProfile σ) := by
  constructor
  · exact fun h => h.map e hutility
  · intro h
    have hmapped :=
      h.map e.symm (hutility.symm e)
    have hprofile :
        e.symm.mapProfile (e.mapProfile σ) = σ :=
      e.unmapProfile_mapProfile σ
    rw [hprofile] at hmapped
    exact hmapped

end Iso

end GameForm
