/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.GameForm.Basic
import Mathlib.Probability.ProbabilityMassFunction.Constructions

/-!
# EconCSLib.GameTheory.GameForm.Law

Representation-neutral strategy semantics with probability laws as primitive
outcomes.

`GameForm` is deterministic, but stochastic game languages have so far used it
by choosing `PMF X` as the outcome type.  `LawGameForm` exposes that common
shape directly: a complete strategy profile induces a normalized law on an
underlying outcome type `X`.

This distinction supplies the right theorem boundary for realization
equivalence.  A source profile realizes a target profile through an outcome
map when pushing the source law through that map gives the target law exactly.
The relation is reflexive and compositional.  Morphisms preserve it by
construction and compose without referring to any EFG representation.

The deterministic `GameForm` view remains available through `toGameForm`.
Consequently the existing deviation-sensitive Nash-transfer theorems apply
without duplicating their proofs.

## Main definitions

* `LawGameForm` — player-indexed strategies and an outcome-law evaluator.
* `LawGameForm.RealizesVia` — exact realization through an outcome map.
* `LawGameForm.Hom` — playerwise strategy and outcome maps preserving laws.
* `LawGameForm.Iso` — strict strategy/outcome equivalences preserving laws.
* `LawGameForm.toGameForm` — the deterministic view with `PMF Outcome` as its
  outcome.

## Main results

* `RealizesVia.refl` and `RealizesVia.trans`.
* `Hom.mapProfile_realizesVia`, `Hom.refl`, and `Hom.trans`.
* `Hom.ext`, `Hom.refl_trans`, `Hom.trans_refl`, and `Hom.trans_assoc`.
* `Hom.OutcomeDeviationCompleteAt` and
  `IsNash.map_of_outcomeDeviationCompleteAt` — semantic deviation coverage
  and Nash transfer without literal strategy surjectivity.
* `IsNash.comap`, `IsNash.map_of_strategySurjective`, and
  `Hom.isNash_iff_of_strategySurjective`.
* `Iso.isNash_iff`.
* `Iso.ext`, `Iso.refl_trans`, `Iso.trans_refl`, and `Iso.trans_assoc`.
-/

universe uN uS uO uV

/-- A strategy form whose evaluator returns a normalized law on outcomes. -/
structure LawGameForm (N : Type uN) where
  /-- Strategy space of each player. -/
  Strategy : N → Type uS
  /-- Underlying realized outcome type. -/
  Outcome : Type uO
  /-- Normalized outcome law generated by a complete strategy profile. -/
  outcomeLaw : (∀ i, Strategy i) → PMF Outcome

namespace LawGameForm

variable {N : Type uN}

/-- Complete profiles of a law-valued game form. -/
abbrev Profile (G : LawGameForm N) :=
  ∀ i, G.Strategy i

/-- Unilateral strategy deviation. -/
abbrev deviate {G : LawGameForm N} [DecidableEq N]
    (profile : G.Profile) (i : N)
    (strategy : G.Strategy i) :
    G.Profile :=
  Function.update profile i strategy

/-- Regard a law-valued game form as an ordinary deterministic game form whose
outcome is the entire probability law. -/
def toGameForm (G : LawGameForm N) : GameForm N where
  Strategy := G.Strategy
  Outcome := PMF G.Outcome
  outcome := G.outcomeLaw

/-- A source profile realizes a target profile through `outcomeMap` when the
pushforward of its complete outcome law is exactly the target law. -/
def RealizesVia
    (G H : LawGameForm N)
    (outcomeMap : G.Outcome → H.Outcome)
    (source : G.Profile) (target : H.Profile) : Prop :=
  (G.outcomeLaw source).map outcomeMap =
    H.outcomeLaw target

namespace RealizesVia

variable {G H K : LawGameForm N}

/-- Every profile realizes itself through the identity outcome map. -/
theorem refl (profile : G.Profile) :
    G.RealizesVia G id profile profile := by
  exact PMF.map_id (G.outcomeLaw profile)

/-- Exact realization composes through successive outcome maps. -/
theorem trans
    {source : G.Profile} {middle : H.Profile}
    {target : K.Profile}
    {first : G.Outcome → H.Outcome}
    {second : H.Outcome → K.Outcome}
    (hfirst :
      G.RealizesVia H first source middle)
    (hsecond :
      H.RealizesVia K second middle target) :
    G.RealizesVia K (second ∘ first)
      source target := by
  unfold RealizesVia at hfirst hsecond ⊢
  calc
    (G.outcomeLaw source).map (second ∘ first) =
        ((G.outcomeLaw source).map first).map second :=
      (PMF.map_comp first
        (G.outcomeLaw source) second).symm
    _ = (H.outcomeLaw middle).map second := by
      rw [hfirst]
    _ = K.outcomeLaw target := hsecond

end RealizesVia

/-! ### Law-preserving morphisms -/

/-- A morphism of law-valued game forms.

Every source strategy maps playerwise to a target strategy, while the complete
source outcome law is pushed through `outcomeMap` exactly. -/
structure Hom (G H : LawGameForm N) where
  /-- Map each player's source strategy. -/
  strategyMap :
    (i : N) → G.Strategy i → H.Strategy i
  /-- Map realized source outcomes. -/
  outcomeMap : G.Outcome → H.Outcome
  /-- The mapped profile realizes its source through `outcomeMap`. -/
  map_outcomeLaw :
    ∀ profile : G.Profile,
      G.RealizesVia H outcomeMap profile
        (fun i => strategyMap i (profile i))

namespace Hom

variable {G H K : LawGameForm N}

/-- Law-game morphisms are equal when their strategy and realized-outcome
maps are equal. -/
@[ext]
theorem ext (f g : G.Hom H)
    (hstrategy : f.strategyMap = g.strategyMap)
    (houtcome : f.outcomeMap = g.outcomeMap) :
    f = g := by
  cases f
  cases g
  cases hstrategy
  cases houtcome
  rfl

/-- Map a complete profile player by player. -/
def mapProfile (f : G.Hom H)
    (profile : G.Profile) : H.Profile :=
  fun i => f.strategyMap i (profile i)

@[simp]
theorem mapProfile_apply (f : G.Hom H)
    (profile : G.Profile) (i : N) :
    f.mapProfile profile i =
      f.strategyMap i (profile i) :=
  rfl

/-- The defining realization square stated with `mapProfile`. -/
theorem mapProfile_realizesVia
    (f : G.Hom H) (profile : G.Profile) :
    G.RealizesVia H f.outcomeMap profile
      (f.mapProfile profile) :=
  f.map_outcomeLaw profile

/-- A law-valued morphism induces an ordinary game-form morphism by mapping
whole laws through `PMF.map`. -/
noncomputable def toGameFormHom (f : G.Hom H) :
    G.toGameForm.Hom H.toGameForm where
  strategyMap := f.strategyMap
  outcomeMap := fun law => law.map f.outcomeMap
  map_outcome := f.map_outcomeLaw

/-- Identity law-valued morphism. -/
def refl (G : LawGameForm N) : G.Hom G where
  strategyMap := fun _ strategy => strategy
  outcomeMap := id
  map_outcomeLaw := RealizesVia.refl

/-- Compose law-valued morphisms. -/
def trans (f : G.Hom H) (g : H.Hom K) :
    G.Hom K where
  strategyMap := fun i strategy =>
    g.strategyMap i (f.strategyMap i strategy)
  outcomeMap := g.outcomeMap ∘ f.outcomeMap
  map_outcomeLaw := by
    intro profile
    exact
      (f.mapProfile_realizesVia profile).trans
        (g.mapProfile_realizesVia
          (f.mapProfile profile))

/-- Profile mapping is functorial under morphism composition. -/
@[simp]
theorem trans_mapProfile
    (f : G.Hom H) (g : H.Hom K)
    (profile : G.Profile) :
    (f.trans g).mapProfile profile =
      g.mapProfile (f.mapProfile profile) :=
  rfl

/-- Mapping a profile through the identity law morphism is a no-op. -/
@[simp]
theorem refl_mapProfile
    (G : LawGameForm N) (profile : G.Profile) :
    (refl G).mapProfile profile = profile :=
  rfl

/-- The identity law morphism is a left unit for composition. -/
@[simp]
theorem refl_trans (f : G.Hom H) :
    (refl G).trans f = f := by
  ext <;> rfl

/-- The identity law morphism is a right unit for composition. -/
@[simp]
theorem trans_refl (f : G.Hom H) :
    f.trans (refl H) = f := by
  ext <;> rfl

/-- Composition of law-game morphisms is associative. -/
theorem trans_assoc {L : LawGameForm N}
    (f : G.Hom H) (g : H.Hom K) (h : K.Hom L) :
    (f.trans g).trans h = f.trans (g.trans h) := by
  ext <;> rfl

/-- Profile mapping commutes with unilateral deviation. -/
theorem mapProfile_deviate [DecidableEq N]
    (f : G.Hom H) (profile : G.Profile)
    (i : N) (strategy : G.Strategy i) :
    f.mapProfile (G.deviate profile i strategy) =
      H.deviate (f.mapProfile profile) i
        (f.strategyMap i strategy) := by
  funext j
  by_cases hji : j = i
  · subst j
    simp [mapProfile, LawGameForm.deviate]
  · simp [mapProfile, LawGameForm.deviate, hji]

/-- Every target strategy is represented by a source strategy. -/
def StrategySurjective (f : G.Hom H) : Prop :=
  ∀ i : N, Function.Surjective (f.strategyMap i)

/-- Every unilateral target deviation at a mapped profile realizes the mapped
law of some source deviation exactly.

This is the law-valued analogue of semantic deviation completeness.  It is
strictly weaker than literal strategy surjectivity and is designed for
realization-equivalent strategy representations. -/
def OutcomeDeviationCompleteAt [DecidableEq N]
    (f : G.Hom H) (profile : G.Profile) : Prop :=
  ∀ (i : N) (targetStrategy : H.Strategy i),
    ∃ sourceStrategy : G.Strategy i,
      H.outcomeLaw
          (H.deviate (f.mapProfile profile)
            i targetStrategy) =
        (G.outcomeLaw
          (G.deviate profile i sourceStrategy)).map
            f.outcomeMap

/-- Exact law-level deviation completeness at every source profile. -/
def OutcomeDeviationComplete [DecidableEq N]
    (f : G.Hom H) : Prop :=
  ∀ profile : G.Profile,
    f.OutcomeDeviationCompleteAt profile

/-- The law-level condition is definitionally the generic outcome condition
for the deterministic `PMF`-outcome view. -/
theorem toGameFormHom_outcomeDeviationCompleteAt
    [DecidableEq N]
    (f : G.Hom H) (profile : G.Profile) :
    f.toGameFormHom.OutcomeDeviationCompleteAt profile ↔
      f.OutcomeDeviationCompleteAt profile :=
  Iff.rfl

/-- Literal strategy surjectivity implies exact law-level deviation
completeness. -/
theorem StrategySurjective.outcomeDeviationCompleteAt
    [DecidableEq N]
    {f : G.Hom H}
    (hsurjective : f.StrategySurjective)
    (profile : G.Profile) :
    f.OutcomeDeviationCompleteAt profile := by
  intro i targetStrategy
  obtain ⟨sourceStrategy, rfl⟩ :=
    hsurjective i targetStrategy
  refine ⟨sourceStrategy, ?_⟩
  rw [← f.mapProfile_deviate]
  exact
    (f.mapProfile_realizesVia
      (G.deviate profile i sourceStrategy)).symm

/-- Global strategy surjectivity implies global law-level deviation
completeness. -/
theorem StrategySurjective.outcomeDeviationComplete
    [DecidableEq N]
    {f : G.Hom H}
    (hsurjective : f.StrategySurjective) :
    f.OutcomeDeviationComplete :=
  fun profile =>
    hsurjective.outcomeDeviationCompleteAt profile

/-- Exact law-level deviation completeness composes. -/
theorem OutcomeDeviationCompleteAt.trans
    [DecidableEq N]
    {f : G.Hom H} {g : H.Hom K}
    {profile : G.Profile}
    (hf : f.OutcomeDeviationCompleteAt profile)
    (hg :
      g.OutcomeDeviationCompleteAt
        (f.mapProfile profile)) :
    (f.trans g).OutcomeDeviationCompleteAt profile := by
  intro i targetStrategy
  obtain ⟨middleStrategy, hmiddle⟩ :=
    hg i targetStrategy
  obtain ⟨sourceStrategy, hsource⟩ :=
    hf i middleStrategy
  refine ⟨sourceStrategy, ?_⟩
  change
    K.outcomeLaw
        (K.deviate
          (g.mapProfile (f.mapProfile profile))
          i targetStrategy) =
      (G.outcomeLaw
        (G.deviate profile i sourceStrategy)).map
          (g.outcomeMap ∘ f.outcomeMap)
  rw [hmiddle, hsource]
  exact
    PMF.map_comp f.outcomeMap
      (G.outcomeLaw
        (G.deviate profile i sourceStrategy))
      g.outcomeMap

/-- Globally law-deviation-complete morphisms compose. -/
theorem OutcomeDeviationComplete.trans
    [DecidableEq N]
    {f : G.Hom H} {g : H.Hom K}
    (hf : f.OutcomeDeviationComplete)
    (hg : g.OutcomeDeviationComplete) :
    (f.trans g).OutcomeDeviationComplete := by
  intro profile
  exact
    (hf profile).trans
      (hg (f.mapProfile profile))

/-- Strategy surjectivity passes to the deterministic game-form view. -/
theorem toGameFormHom_strategySurjective
    (f : G.Hom H)
    (hsurjective : f.StrategySurjective) :
    f.toGameFormHom.StrategySurjective :=
  hsurjective

/-- Utilities on complete outcome laws commute with a morphism. -/
def UtilityCompatible
    {V : Type uV}
    (f : G.Hom H)
    (sourceUtility : PMF G.Outcome → N → V)
    (targetUtility : PMF H.Outcome → N → V) : Prop :=
  ∀ (law : PMF G.Outcome) (i : N),
    targetUtility (law.map f.outcomeMap) i =
      sourceUtility law i

end Hom

/-! ### Nash equilibrium on outcome laws -/

/-- Nash equilibrium under a preference functional on complete outcome laws. -/
def IsNash
    {V : Type uV} [DecidableEq N] [Preorder V]
    (G : LawGameForm N)
    (utility : PMF G.Outcome → N → V)
    (profile : G.Profile) : Prop :=
  G.toGameForm.IsNash utility profile

namespace Hom

variable {G H : LawGameForm N}

/-- Law-utility compatibility gives ordinary game-form utility compatibility. -/
theorem toGameFormHom_utilityCompatible
    {V : Type uV}
    (f : G.Hom H)
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map f.outcomeMap) i =
          sourceUtility law i) :
    GameForm.Hom.UtilityCompatible
      f.toGameFormHom sourceUtility targetUtility :=
  hutility

end Hom

/-- Nash equilibrium of a mapped target profile reflects through every
law-preserving, utility-compatible morphism. -/
theorem IsNash.comap
    {V : Type uV} [DecidableEq N] [Preorder V]
    {G H : LawGameForm N}
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (f : G.Hom H)
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map f.outcomeMap) i =
          sourceUtility law i)
    {profile : G.Profile}
    (hNash :
      H.IsNash targetUtility
        (f.mapProfile profile)) :
    G.IsNash sourceUtility profile :=
  GameForm.IsNash.comap
    f.toGameFormHom
    (f.toGameFormHom_utilityCompatible hutility)
    hNash

/-- Nash equilibrium maps forward under exact semantic coverage of all target
deviation laws at the source profile. -/
theorem IsNash.map_of_outcomeDeviationCompleteAt
    {V : Type uV} [DecidableEq N] [Preorder V]
    {G H : LawGameForm N}
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (f : G.Hom H)
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map f.outcomeMap) i =
          sourceUtility law i)
    {profile : G.Profile}
    (hcomplete :
      f.OutcomeDeviationCompleteAt profile)
    (hNash : G.IsNash sourceUtility profile) :
    H.IsNash targetUtility
      (f.mapProfile profile) :=
  GameForm.IsNash.map_of_outcomeDeviationCompleteAt
    f.toGameFormHom
    (f.toGameFormHom_utilityCompatible hutility)
    ((f.toGameFormHom_outcomeDeviationCompleteAt
      profile).mpr hcomplete)
    hNash

/-- Nash equilibrium maps forward when all target unilateral deviations lift. -/
theorem IsNash.map_of_strategySurjective
    {V : Type uV} [DecidableEq N] [Preorder V]
    {G H : LawGameForm N}
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (f : G.Hom H)
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map f.outcomeMap) i =
          sourceUtility law i)
    (hsurjective : f.StrategySurjective)
    {profile : G.Profile}
    (hNash : G.IsNash sourceUtility profile) :
    H.IsNash targetUtility
      (f.mapProfile profile) :=
  hNash.map_of_outcomeDeviationCompleteAt
    f hutility
    (hsurjective.outcomeDeviationCompleteAt
      profile)

/-- Exact two-way Nash transfer under law-level semantic deviation
completeness at the source profile. -/
theorem Hom.isNash_iff_of_outcomeDeviationCompleteAt
    {V : Type uV} [DecidableEq N] [Preorder V]
    {G H : LawGameForm N}
    (f : G.Hom H)
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map f.outcomeMap) i =
          sourceUtility law i)
    (profile : G.Profile)
    (hcomplete :
      f.OutcomeDeviationCompleteAt profile) :
    G.IsNash sourceUtility profile ↔
      H.IsNash targetUtility
        (f.mapProfile profile) := by
  constructor
  · exact fun hNash =>
      hNash.map_of_outcomeDeviationCompleteAt
        f hutility hcomplete
  · exact fun hNash =>
      hNash.comap f hutility

/-- Exact two-way Nash transfer for a strategy-surjective law morphism. -/
theorem Hom.isNash_iff_of_strategySurjective
    {V : Type uV} [DecidableEq N] [Preorder V]
    {G H : LawGameForm N}
    (f : G.Hom H)
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map f.outcomeMap) i =
          sourceUtility law i)
    (hsurjective : f.StrategySurjective)
    (profile : G.Profile) :
    G.IsNash sourceUtility profile ↔
      H.IsNash targetUtility
        (f.mapProfile profile) := by
  constructor
  · exact fun hNash =>
      hNash.map_of_strategySurjective
        f hutility hsurjective
  · exact fun hNash =>
      hNash.comap f hutility

/-! ### Strict law-game isomorphisms -/

/-- A strict isomorphism of law-valued game forms. -/
structure Iso (G H : LawGameForm N) where
  /-- Equivalence of each player's strategy space. -/
  strategyEquiv :
    (i : N) → G.Strategy i ≃ H.Strategy i
  /-- Equivalence of realized outcomes. -/
  outcomeEquiv : G.Outcome ≃ H.Outcome
  /-- Exact naturality of complete outcome laws. -/
  map_outcomeLaw :
    ∀ profile : G.Profile,
      G.RealizesVia H outcomeEquiv profile
        (fun i => strategyEquiv i (profile i))

namespace Iso

variable {G H K : LawGameForm N}

/-- Strict law-game isomorphisms are equal when their strategy and
realized-outcome equivalences are equal. -/
@[ext]
theorem ext (e f : G.Iso H)
    (hstrategy : e.strategyEquiv = f.strategyEquiv)
    (houtcome : e.outcomeEquiv = f.outcomeEquiv) :
    e = f := by
  cases e
  cases f
  cases hstrategy
  cases houtcome
  rfl

/-- Forget invertibility and retain the law morphism. -/
def toHom (e : G.Iso H) : G.Hom H where
  strategyMap := fun i => e.strategyEquiv i
  outcomeMap := fun outcome => e.outcomeEquiv outcome
  map_outcomeLaw := e.map_outcomeLaw

/-- Map a complete profile through a strict law isomorphism. -/
def mapProfile (e : G.Iso H)
    (profile : G.Profile) : H.Profile :=
  e.toHom.mapProfile profile

@[simp]
theorem mapProfile_apply (e : G.Iso H)
    (profile : G.Profile) (i : N) :
    e.mapProfile profile i =
      e.strategyEquiv i (profile i) :=
  rfl

/-- Strict law isomorphisms are strategy-surjective. -/
theorem toHom_strategySurjective (e : G.Iso H) :
    e.toHom.StrategySurjective := by
  intro i targetStrategy
  exact
    ⟨(e.strategyEquiv i).symm targetStrategy,
      (e.strategyEquiv i).apply_symm_apply targetStrategy⟩

/-- Identity strict law isomorphism. -/
def refl (G : LawGameForm N) : G.Iso G where
  strategyEquiv := fun _ => Equiv.refl _
  outcomeEquiv := Equiv.refl _
  map_outcomeLaw := RealizesVia.refl

/-- Compose strict law isomorphisms. -/
def trans (e : G.Iso H) (f : H.Iso K) :
    G.Iso K where
  strategyEquiv := fun i =>
    (e.strategyEquiv i).trans
      (f.strategyEquiv i)
  outcomeEquiv :=
    e.outcomeEquiv.trans f.outcomeEquiv
  map_outcomeLaw := by
    intro profile
    simpa [mapProfile] using
      (e.map_outcomeLaw profile).trans
        (f.map_outcomeLaw (e.mapProfile profile))

/-- Mapping a profile through the identity law isomorphism is a no-op. -/
@[simp]
theorem refl_mapProfile
    (G : LawGameForm N) (profile : G.Profile) :
    (refl G).mapProfile profile = profile :=
  rfl

/-- Profile mapping is functorial under law-isomorphism composition. -/
@[simp]
theorem trans_mapProfile
    (e : G.Iso H) (f : H.Iso K) (profile : G.Profile) :
    (e.trans f).mapProfile profile =
      f.mapProfile (e.mapProfile profile) :=
  rfl

/-- The identity law isomorphism is a left unit for composition. -/
@[simp]
theorem refl_trans (e : G.Iso H) :
    (refl G).trans e = e := by
  apply Iso.ext
  · funext i
    apply Equiv.ext
    intro strategy
    rfl
  · apply Equiv.ext
    intro outcome
    rfl

/-- The identity law isomorphism is a right unit for composition. -/
@[simp]
theorem trans_refl (e : G.Iso H) :
    e.trans (refl H) = e := by
  apply Iso.ext
  · funext i
    apply Equiv.ext
    intro strategy
    rfl
  · apply Equiv.ext
    intro outcome
    rfl

/-- Composition of strict law isomorphisms is associative. -/
theorem trans_assoc {L : LawGameForm N}
    (e : G.Iso H) (f : H.Iso K) (g : K.Iso L) :
    (e.trans f).trans g = e.trans (f.trans g) := by
  apply Iso.ext
  · funext i
    apply Equiv.ext
    intro strategy
    rfl
  · apply Equiv.ext
    intro outcome
    rfl

/-- Strict law isomorphisms preserve Nash equilibrium under a compatible
functional on complete laws. -/
theorem isNash_iff
    {V : Type uV} [DecidableEq N] [Preorder V]
    (e : G.Iso H)
    {sourceUtility : PMF G.Outcome → N → V}
    {targetUtility : PMF H.Outcome → N → V}
    (hutility :
      ∀ (law : PMF G.Outcome) (i : N),
        targetUtility (law.map e.outcomeEquiv) i =
          sourceUtility law i)
    (profile : G.Profile) :
    G.IsNash sourceUtility profile ↔
      H.IsNash targetUtility
        (e.mapProfile profile) :=
  e.toHom.isNash_iff_of_strategySurjective
    hutility e.toHom_strategySurjective profile

end Iso

end LawGameForm
