/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.StrategicGame.NoRegret.Internal
import Mathlib.Data.Real.Sqrt

/-!
# Calibration from internal consistency

This module formalizes calibration on finite forecast grids and the reduction
from internal consistency in [MFoGT, Section 7.3.3]. It provides the
conditional-process reduction and the ingredients for the canonical
finite-history forecast law in `NoRegret.Process`.

## References

* [MFoGT] Chapter 7, Section 7.3.3
-/

open Finset BigOperators Filter Topology
open scoped MeasureTheory

namespace StrategicGame

universe uK uL uN uS uΩ uOut

/-! ### Calibration: MFoGT 7.3.3 -/

/-- A finite set of distinct forecast distributions over outcomes `Ω`, indexed
by the finite type `point`. -/
structure ForecastGrid (Ω : Type uOut) [Fintype Ω] where
  point : Type uOut
  pointFintype : Fintype point
  pointDecidableEq : DecidableEq point
  forecast : point → stdSimplex ℝ Ω
  /-- Distinct grid points represent distinct forecast distributions. -/
  forecast_injective : Function.Injective forecast

attribute [instance] ForecastGrid.pointFintype
attribute [instance] ForecastGrid.pointDecidableEq

/-- A forecasting strategy over a finite grid, depending on past forecasts
and outcomes. This is the history used by the internal-consistency construction
in [MFoGT, Proposition 7.3.10]. -/
abbrev ForecastStrategy (Ω : Type*) [Fintype Ω] (V : ForecastGrid Ω) :=
  (n : ℕ) → (Fin n → V.point) × (Fin n → Ω) → stdSimplex ℝ V.point

/-- The finite history of past forecasts and past outcomes generated by a realized
forecast/outcome path before stage `n`. -/
def forecastHistoryOf {Ω : Type*} [Fintype Ω] {V : ForecastGrid Ω}
    (forecast : ℕ → V.point) (outcome : ℕ → Ω) (n : ℕ) :
    (Fin n → V.point) × (Fin n → Ω) :=
  (fun t => forecast t.val, fun t => outcome t.val)

/-- Pathwise support relation for a forecast path. The probability layer uses
the stronger conditional-law predicate `IsGeneratedByForecastStrategyAE`. -/
def IsSupportedByForecastStrategy {Ω : Type*} [Fintype Ω]
    {V : ForecastGrid Ω} (φ : ForecastStrategy Ω V)
    (forecast : ℕ → V.point) (outcome : ℕ → Ω) : Prop :=
  ∀ n : ℕ, 0 < (φ n (forecastHistoryOf forecast outcome n)).val (forecast n)

/-- The empirical frequency with which forecast grid point `v` is used up to
stage `n + 1`. -/
noncomputable def forecastUseFrequency {Ω : Type*} [Fintype Ω]
    {V : ForecastGrid Ω} (forecast : ℕ → V.point) (n : ℕ) (v : V.point) : ℝ :=
  ((n + 1 : ℝ)⁻¹) * ∑ t : Fin (n + 1), if forecast t.val = v then 1 else 0

/-- The empirical joint frequency of using forecast `v` and observing outcome
`ω` up to stage `n + 1`. -/
noncomputable def forecastOutcomeFrequency {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    {V : ForecastGrid Ω} (forecast : ℕ → V.point) (outcome : ℕ → Ω)
    (n : ℕ) (v : V.point) (ω : Ω) : ℝ :=
  ((n + 1 : ℝ)⁻¹) *
    ∑ t : Fin (n + 1), if forecast t.val = v ∧ outcome t.val = ω then 1 else 0

/-- The empirical conditional distribution of outcomes on the stages where
forecast `v` was used. If `v` was not used, the forecast itself is returned so
that the corresponding calibration term is zero. -/
noncomputable def conditionalOutcomeFrequency {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    {V : ForecastGrid Ω} (forecast : ℕ → V.point) (outcome : ℕ → Ω)
    (n : ℕ) (v : V.point) (ω : Ω) : ℝ :=
  if forecastUseFrequency forecast n v = 0 then
    (V.forecast v).val ω
  else
    forecastOutcomeFrequency forecast outcome n v ω / forecastUseFrequency forecast n v

/-- The finite `L2` calibration error from [MFoGT Definition 7.3.9]: each forecast
grid point contributes its empirical use frequency times the distance between
the empirical conditional outcome distribution and the announced forecast. -/
noncomputable def calibrationError {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    (V : ForecastGrid Ω) (forecast : ℕ → V.point) (outcome : ℕ → Ω) (n : ℕ) : ℝ :=
  ∑ v : V.point,
    forecastUseFrequency forecast n v *
      Real.sqrt
        (∑ ω : Ω,
          (conditionalOutcomeFrequency forecast outcome n v ω - (V.forecast v).val ω) ^ 2)

/-- The normalized calibration residual at forecast `v` and outcome coordinate
`ω`, written in the direct empirical-frequency form of
[MFoGT, Definition 7.3.9]. -/
noncomputable def calibrationResidual {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    (V : ForecastGrid Ω) (forecast : ℕ → V.point) (outcome : ℕ → Ω)
    (n : ℕ) (v : V.point) (ω : Ω) : ℝ :=
  forecastOutcomeFrequency forecast outcome n v ω -
    forecastUseFrequency forecast n v * (V.forecast v).val ω

/-- The source-literal calibration error: sum over forecasts of the Euclidean
norm of the normalized empirical residual vector. -/
noncomputable def directCalibrationError {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    (V : ForecastGrid Ω) (forecast : ℕ → V.point) (outcome : ℕ → Ω)
    (n : ℕ) : ℝ :=
  ∑ v : V.point,
    Real.sqrt (∑ ω : Ω, calibrationResidual V forecast outcome n v ω ^ 2)

/-- Realized-path ε-calibration from [MFoGT, Definition 7.3.9], expressed as
`limsup calibrationError ≤ ε` via
`VanishesAboveZero (calibrationError - ε)`. Positivity of `ε` is imposed by
the existence theorem rather than by this path predicate. -/
def IsEpsilonCalibrated {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    (V : ForecastGrid Ω) (ε : ℝ) (forecast : ℕ → V.point) (outcome : ℕ → Ω) : Prop :=
  VanishesAboveZero fun n => calibrationError V forecast outcome n - ε

/-- Support-based pathwise ε-calibration: every supported forecast path is
ε-calibrated against every outcome path. This is stronger than the
almost-sure randomized statement in [MFoGT, Proposition 7.3.10]. -/
def IsRobustPathwiseEpsilonCalibrated {Ω : Type*} [Fintype Ω] [DecidableEq Ω]
    (V : ForecastGrid Ω) (ε : ℝ) (φ : ForecastStrategy Ω V) : Prop :=
  ∀ forecast outcome,
    IsSupportedByForecastStrategy φ forecast outcome →
      IsEpsilonCalibrated V ε forecast outcome

/-! ### Calibration from internal consistency

Following [MFoGT, Proposition 7.3.10], grid points are treated as actions with
squared-error loss. Internal consistency bounds the conditional empirical
outcome distribution at every announced grid point; the grid mesh then gives
ε-calibration. -/

/-- Squared Euclidean distance in `Out → ℝ` between a point `v` of the simplex and an
arbitrary vector `a` (typically an empirical average of outcome indicators). -/
noncomputable def calibrationSqDistTo {Out : Type*} [Fintype Out]
    (v : stdSimplex ℝ Out) (a : Out → ℝ) : ℝ :=
  ∑ ω' : Out, (v.val ω' - a ω') ^ 2

/-- Squared Euclidean distance between a point `v` of the simplex and the indicator (point
mass) at outcome `ω`. This is the loss `‖X − v‖²` of [MFoGT Proposition 7.3.10], with the realized
outcome represented as a basis vector. -/
noncomputable def calibrationSqLoss {Out : Type*} [Fintype Out] [DecidableEq Out]
    (v : stdSimplex ℝ Out) (ω : Out) : ℝ :=
  calibrationSqDistTo v (fun ω' => if ω' = ω then (1 : ℝ) else 0)

/-- The loss game used to reduce calibration to internal regret: the "payoff" of forecast `v`
against realized outcome `ω` is the negative of the squared loss (higher is better), matching
the sign convention of `internalRegretStage`. -/
noncomputable def calibrationPayoff {Out : Type*} [Fintype Out] [DecidableEq Out]
    (V : ForecastGrid Out) (ω : Out) (v : V.point) : ℝ :=
  - calibrationSqLoss (V.forecast v) ω

/-- Polarization identity for the difference between the squared losses of
two forecasts. It permits averaging the samplewise loss difference at the
conditional empirical outcome distribution. -/
lemma calibrationSqDistTo_sub_eq {Out : Type*} [Fintype Out]
    (v w : stdSimplex ℝ Out) (a : Out → ℝ) :
    calibrationSqDistTo v a - calibrationSqDistTo w a
      = (∑ ω' : Out, v.val ω' ^ 2 - ∑ ω' : Out, w.val ω' ^ 2)
        - 2 * (∑ ω' : Out, (v.val ω' - w.val ω') * a ω') := by
  unfold calibrationSqDistTo
  rw [← Finset.sum_sub_distrib]
  have hterm : ∀ ω' : Out, (v.val ω' - a ω') ^ 2 - (w.val ω' - a ω') ^ 2
      = (v.val ω' ^ 2 - w.val ω' ^ 2) - 2 * ((v.val ω' - w.val ω') * a ω') := fun ω' => by ring
  simp_rw [hterm]
  rw [Finset.sum_sub_distrib, Finset.sum_sub_distrib, ← Finset.mul_sum]

/-- If forecast grid point `v` is never used up to stage `n`, its joint frequency with any
outcome vanishes too. -/
lemma forecastOutcomeFrequency_eq_zero_of_forecastUseFrequency_eq_zero
    {Out : Type*} [Fintype Out] [DecidableEq Out] {V : ForecastGrid Out}
    (forecast : ℕ → V.point) (outcome : ℕ → Out) (n : ℕ) (v : V.point) (ω : Out)
    (h : forecastUseFrequency forecast n v = 0) :
    forecastOutcomeFrequency forecast outcome n v ω = 0 := by
  have hne : ∀ t : Fin (n + 1), forecast t.val ≠ v := by
    intro t hc
    have hSpos : (0 : ℝ) < ∑ t' : Fin (n + 1), (if forecast t'.val = v then (1 : ℝ) else 0) :=
      Finset.sum_pos' (fun t' _ => by split <;> norm_num) ⟨t, Finset.mem_univ t, by simp [hc]⟩
    have hcpos : (0 : ℝ) < ((n : ℝ) + 1)⁻¹ := by positivity
    have hpos : (0 : ℝ) < forecastUseFrequency forecast n v := mul_pos hcpos hSpos
    linarith [h ▸ hpos]
  unfold forecastOutcomeFrequency
  exact mul_eq_zero_of_right _ (Finset.sum_eq_zero fun t _ => if_neg (fun hcon => hne t hcon.1))

/-- The joint use/outcome frequency factors as the marginal use frequency times the
conditional outcome frequency. -/
lemma forecastOutcomeFrequency_eq_use_mul_conditional
    {Out : Type*} [Fintype Out] [DecidableEq Out] {V : ForecastGrid Out}
    (forecast : ℕ → V.point) (outcome : ℕ → Out) (n : ℕ) (v : V.point) (ω : Out) :
    forecastOutcomeFrequency forecast outcome n v ω
      = forecastUseFrequency forecast n v * conditionalOutcomeFrequency forecast outcome n v ω := by
  unfold conditionalOutcomeFrequency
  by_cases h : forecastUseFrequency forecast n v = 0
  · rw [if_pos h, h, zero_mul,
      forecastOutcomeFrequency_eq_zero_of_forecastUseFrequency_eq_zero forecast outcome n v ω h]
  · rw [if_neg h]; field_simp

/-- The direct residual is the forecast-use frequency times the conditional
forecast error, including when the forecast is unused. -/
lemma calibrationResidual_eq_use_mul_conditional
    {Out : Type*} [Fintype Out] [DecidableEq Out] {V : ForecastGrid Out}
    (forecast : ℕ → V.point) (outcome : ℕ → Out)
    (n : ℕ) (v : V.point) (ω : Out) :
    calibrationResidual V forecast outcome n v ω =
      forecastUseFrequency forecast n v *
        (conditionalOutcomeFrequency forecast outcome n v ω -
          (V.forecast v).val ω) := by
  rw [calibrationResidual,
    forecastOutcomeFrequency_eq_use_mul_conditional]
  ring

/-- The direct residual-vector formula in [MFoGT, Definition 7.3.9] is exactly
the frequency-weighted conditional-frequency formula used by
`calibrationError`. -/
theorem directCalibrationError_eq_calibrationError
    {Out : Type*} [Fintype Out] [DecidableEq Out] (V : ForecastGrid Out)
    (forecast : ℕ → V.point) (outcome : ℕ → Out) (n : ℕ) :
    directCalibrationError V forecast outcome n =
      calibrationError V forecast outcome n := by
  classical
  unfold directCalibrationError calibrationError
  apply Finset.sum_congr rfl
  intro v _
  have huse : 0 ≤ forecastUseFrequency forecast n v := by
    unfold forecastUseFrequency
    positivity
  have hsq :
      (∑ ω : Out, calibrationResidual V forecast outcome n v ω ^ 2) =
        forecastUseFrequency forecast n v ^ 2 *
          ∑ ω : Out,
            (conditionalOutcomeFrequency forecast outcome n v ω -
              (V.forecast v).val ω) ^ 2 := by
    simp_rw [calibrationResidual_eq_use_mul_conditional, mul_pow]
    rw [Finset.mul_sum]
  rw [hsq, Real.sqrt_mul (sq_nonneg _), Real.sqrt_sq_eq_abs,
    abs_of_nonneg huse]

/-- Realized-path ε-calibration can equivalently be stated using the
source-literal residual-vector error. -/
theorem isEpsilonCalibrated_iff_directCalibrationError
    {Out : Type*} [Fintype Out] [DecidableEq Out] (V : ForecastGrid Out)
    (ε : ℝ) (forecast : ℕ → V.point) (outcome : ℕ → Out) :
    IsEpsilonCalibrated V ε forecast outcome ↔
      VanishesAboveZero fun n => directCalibrationError V forecast outcome n - ε := by
  simp only [IsEpsilonCalibrated, directCalibrationError_eq_calibrationError]

/-- Summing a function of the outcome, weighted by the realized-forecast indicator, against the
empirical frequencies rewrites as a sum over outcomes weighted by the joint frequency. -/
lemma sum_indicator_mul_apply_eq
    {Out : Type*} [Fintype Out] [DecidableEq Out] {V : ForecastGrid Out}
    (forecast : ℕ → V.point) (outcome : ℕ → Out) (n : ℕ) (v : V.point) (f : Out → ℝ) :
    ((n : ℝ) + 1)⁻¹ *
        ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) * f (outcome t.val)
      = ∑ ω : Out, f ω * forecastOutcomeFrequency forecast outcome n v ω := by
  have hstep : ∀ t : Fin (n + 1),
      (∑ ω : Out, f ω * (if forecast t.val = v ∧ outcome t.val = ω then (1 : ℝ) else 0))
        = (if forecast t.val = v then (1 : ℝ) else 0) * f (outcome t.val) := by
    intro t
    rw [Finset.sum_eq_single (outcome t.val)
      (fun ω _ hne => by simp [Ne.symm hne]) (fun h => absurd (Finset.mem_univ _) h)]
    by_cases hf : forecast t.val = v <;> simp [hf, mul_comm]
  simp_rw [← hstep]
  rw [Finset.mul_sum]
  simp_rw [Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun ω _ => ?_
  unfold forecastOutcomeFrequency
  rw [Finset.mul_sum, Finset.mul_sum]
  exact Finset.sum_congr rfl fun t _ => by ring

/-- In the calibration loss game, average internal regret from `v` to `w`
equals the use frequency of `v` times the corresponding conditional
squared-loss difference. -/
lemma averageInternalRegret_calibrationPayoff_eq
    {Out : Type*} [Fintype Out] [DecidableEq Out] {V : ForecastGrid Out}
    (forecast : ℕ → V.point) (outcome : ℕ → Out) (n : ℕ) (v w : V.point) :
    averageInternalRegret forecast (fun t => calibrationPayoff V (outcome t)) n v w
      = forecastUseFrequency forecast n v *
        (calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v)
          - calibrationSqDistTo (V.forecast w) (conditionalOutcomeFrequency forecast outcome n v)) := by
  set C : ℝ := ∑ ω' : Out, (V.forecast v).val ω' ^ 2 - ∑ ω' : Out, (V.forecast w).val ω' ^ 2
    with hC_def
  have hstage : ∀ t : Fin (n + 1),
      internalRegretStage (forecast t.val) (fun v' => calibrationPayoff V (outcome t.val) v') v w
        = (if forecast t.val = v then (1 : ℝ) else 0) *
          (C - 2 * ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val))) := by
    intro t
    have hpol := calibrationSqDistTo_sub_eq (V.forecast v) (V.forecast w)
      (fun ω' => if ω' = outcome t.val then (1 : ℝ) else 0)
    rw [← hC_def] at hpol
    have hind : (∑ ω' : Out, ((V.forecast v).val ω' - (V.forecast w).val ω') *
          (if ω' = outcome t.val then (1 : ℝ) else 0))
        = (V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val) := by
      rw [show (∑ ω' : Out, ((V.forecast v).val ω' - (V.forecast w).val ω') *
            (if ω' = outcome t.val then (1 : ℝ) else 0))
          = ∑ ω' : Out, if ω' = outcome t.val then
              (V.forecast v).val ω' - (V.forecast w).val ω' else 0 from
          Finset.sum_congr rfl fun ω' _ => by split <;> ring]
      exact Fintype.sum_ite_eq' (outcome t.val)
        (fun ω' => (V.forecast v).val ω' - (V.forecast w).val ω')
    rw [hind] at hpol
    unfold internalRegretStage calibrationPayoff calibrationSqLoss
    dsimp only
    split
    · linarith [hpol]
    · ring
  unfold averageInternalRegret
  simp_rw [hstage]
  rw [show (∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
        (C - 2 * ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val))))
      = C * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0)
        - 2 * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
            ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val)) from by
    rw [Finset.mul_sum, Finset.mul_sum]
    rw [← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun t _ => by ring]
  have hSeq : ((n : ℝ) + 1)⁻¹ * (C * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0))
      = C * forecastUseFrequency forecast n v := by
    unfold forecastUseFrequency; ring
  have hTeq : ((n : ℝ) + 1)⁻¹ * (2 * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
        ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val)))
      = 2 * (forecastUseFrequency forecast n v *
          ∑ ω : Out, ((V.forecast v).val ω - (V.forecast w).val ω) *
            conditionalOutcomeFrequency forecast outcome n v ω) := by
    rw [show ((n : ℝ) + 1)⁻¹ * (2 * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
          ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val)))
        = 2 * (((n : ℝ) + 1)⁻¹ * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
          ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val))) from by ring]
    rw [sum_indicator_mul_apply_eq forecast outcome n v
      (fun ω => (V.forecast v).val ω - (V.forecast w).val ω)]
    congr 1
    rw [Finset.mul_sum]
    exact Finset.sum_congr rfl fun ω _ => by
      rw [forecastOutcomeFrequency_eq_use_mul_conditional]; ring
  rw [show (((n : ℝ) + 1)⁻¹ *
        (C * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0)
          - 2 * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
              ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val))))
      = ((n : ℝ) + 1)⁻¹ * (C * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0))
        - ((n : ℝ) + 1)⁻¹ * (2 * ∑ t : Fin (n + 1), (if forecast t.val = v then (1 : ℝ) else 0) *
            ((V.forecast v).val (outcome t.val) - (V.forecast w).val (outcome t.val))) from by ring]
  rw [hSeq, hTeq]
  have hpol := calibrationSqDistTo_sub_eq (V.forecast v) (V.forecast w)
    (conditionalOutcomeFrequency forecast outcome n v)
  rw [← hC_def] at hpol
  rw [hpol]
  ring

namespace NoRegretProbability

variable {Ω : Type uΩ} [mΩ : MeasurableSpace Ω]

/-! ### Calibration, almost surely -/

/-- Indicator of the event that the realized forecast at stage `n` is `v`. -/
def forecastIndicator {Out : Type*} [Fintype Out]
    {V : ForecastGrid Out} (forecast : ℕ → Ω → V.point)
    (n : ℕ) (v : V.point) : Ω → ℝ :=
  fun ω => if forecast n ω = v then 1 else 0

/-- Indicator of the event that the realized outcome at stage `n` is `ω'`. -/
def outcomeIndicator {Out : Type*} [Fintype Out] [DecidableEq Out]
    (outcome : ℕ → Ω → Out) (n : ℕ) (ω' : Out) : Ω → ℝ :=
  fun ω => if outcome n ω = ω' then 1 else 0

/-- The probability assigned by a forecasting strategy to grid point `v` after
the realized history of past forecasts and past outcomes before stage `n`. -/
def forecastStrategyProbability {Out : Type*} [Fintype Out]
    {V : ForecastGrid Out} (φ : ForecastStrategy Out V)
    (forecast : ℕ → Ω → V.point) (outcome : ℕ → Ω → Out) (n : ℕ) (v : V.point) : Ω → ℝ :=
  fun ω => (φ n (fun t => forecast t.val ω, fun t => outcome t.val ω)).val v

/-- The realized histories of forecasts and outcomes are measurable with respect to the
filtration available at the stage when they enter the strategy's history. -/
structure IsForecastHistoryAdapted {Out : Type*} [Fintype Out] [DecidableEq Out]
    (ℱ : MeasureTheory.Filtration ℕ mΩ)
    {V : ForecastGrid Out} (forecast : ℕ → Ω → V.point) (outcome : ℕ → Ω → Out) : Prop where
  /-- Past forecast indicators are measurable at the stage when they enter the strategy's
  history. -/
  forecastHistory :
    ∀ n : ℕ, ∀ t : Fin n, ∀ v : V.point, Measurable[ℱ n] (forecastIndicator forecast t.val v)
  /-- Past outcome indicators are measurable at the stage when they enter the strategy's
  history. -/
  outcomeHistory :
    ∀ n : ℕ, ∀ t : Fin n, ∀ ω' : Out, Measurable[ℱ n] (outcomeIndicator outcome t.val ω')

/-- A forecast/outcome process is generated by `φ` when its histories are
adapted, `φ` gives the conditional law of each forecast, and the current
outcome is measurable before the forecast randomization. The strategy itself
receives only the explicit past history; conditioning on the larger
pre-randomization σ-algebra expresses independence from the fresh forecast
draw. -/
structure IsGeneratedByForecastStrategyAE {Out : Type*} [Fintype Out] [DecidableEq Out]
    (P : MeasureTheory.Measure Ω) (ℱ : MeasureTheory.Filtration ℕ mΩ)
    {V : ForecastGrid Out} (φ : ForecastStrategy Out V)
    (forecast : ℕ → Ω → V.point) (outcome : ℕ → Ω → Out) : Prop where
  /-- The realized finite history used by the strategy is nonanticipative. -/
  historyAdapted : IsForecastHistoryAdapted ℱ forecast outcome
  /-- The strategy's announced mixed forecast is measurable with respect to the
  current-stage information. -/
  strategyProbabilityMeasurable :
    ∀ n : ℕ, ∀ v : V.point, Measurable[ℱ n] (forecastStrategyProbability φ forecast outcome n v)
  /-- Conditional probability identity for each forecast grid point and stage. -/
  condProb :
    ∀ n : ℕ, ∀ v : V.point,
      forecastStrategyProbability φ forecast outcome n v =ᵐ[P]
        MeasureTheory.condExp (ℱ n) P (forecastIndicator forecast n v)
  /-- The stage-`n` outcome is fixed in the pre-forecast information `ℱ n` and
  therefore cannot react to the fresh randomization used for the stage-`n`
  forecast. It is not part of the explicit history supplied to `φ`. -/
  outcomePredictable : ∀ n : ℕ, ∀ ω' : Out, Measurable[ℱ n] (outcomeIndicator outcome n ω')

/-- A realized random forecast/outcome pair is ε-calibrated almost surely.
This is the direct almost-sure lifting of [MFoGT Definition 7.3.9]. -/
def IsEpsilonCalibratedAE
    {Out : Type*} [Fintype Out] [DecidableEq Out]
    (P : MeasureTheory.Measure Ω) (V : ForecastGrid Out) (ε : ℝ)
    (forecast : ℕ → Ω → V.point) (outcome : ℕ → Ω → Out) : Prop :=
  ∀ᵐ ω ∂P,
    IsEpsilonCalibrated V ε (fun n => forecast n ω) (fun n => outcome n ω)

/-- Every predictable-outcome process generated by `φ` is ε-calibrated almost
surely. This is a universal conditional property and does not assert existence
of a generated process on the supplied probability space. -/
def IsEpsilonCalibratedOnGeneratedProcessesAE
    {Out : Type*} [Fintype Out] [DecidableEq Out]
    (P : MeasureTheory.Measure Ω) (ℱ : MeasureTheory.Filtration ℕ mΩ)
    (V : ForecastGrid Out) (ε : ℝ) (φ : ForecastStrategy Out V) : Prop :=
  ∀ forecast outcome,
    IsGeneratedByForecastStrategyAE P ℱ φ forecast outcome →
      IsEpsilonCalibratedAE P V ε forecast outcome

/-! ### Generated-process ε-calibration reduction: MFoGT Proposition 7.3.10 -/

/-- Rescaling a payoff process by a positive constant rescales average internal regret by the
same constant. -/
lemma averageInternalRegret_const_smul {K : Type uK} [DecidableEq K]
    (c : ℝ) (play : ℕ → K) (payoff : ℕ → K → ℝ) (n : ℕ) (j ℓ : K) :
    averageInternalRegret play (fun t k => c * payoff t k) n j ℓ
      = c * averageInternalRegret play payoff n j ℓ := by
  unfold averageInternalRegret
  have hstage : ∀ t : Fin (n + 1),
      internalRegretStage (play t.val) (fun k => c * payoff t.val k) j ℓ
        = c * internalRegretStage (play t.val) (payoff t.val) j ℓ := by
    intro t; unfold internalRegretStage; split <;> ring
  simp_rw [hstage, ← Finset.mul_sum]
  ring

/-- `VanishesAboveZero` is unaffected by rescaling by a positive constant. -/
lemma vanishesAboveZero_const_smul_iff {c : ℝ} (hc : 0 < c) (a : ℕ → ℝ) :
    VanishesAboveZero (fun n => c * a n) ↔ VanishesAboveZero a := by
  constructor
  · intro h ε hε
    obtain ⟨N, hN⟩ := h (c * ε) (by positivity)
    exact ⟨N, fun n hn => le_of_mul_le_mul_left (hN n hn) hc⟩
  · intro h ε hε
    obtain ⟨N, hN⟩ := h (ε / c) (by positivity)
    refine ⟨N, fun n hn => ?_⟩
    have := mul_le_mul_of_nonneg_left (hN n hn) hc.le
    rwa [mul_div_cancel₀ ε hc.ne'] at this

omit mΩ in
/-- If, for a fixed stage `t`, the indicator of each outcome value is measurable, then every
real-valued function of the realized outcome at stage `t` is measurable: `Out` being finite,
this is just a finite sum of scaled indicators. -/
lemma measurable_of_outcomeIndicator {Out : Type*} [Fintype Out] [DecidableEq Out]
    {m : MeasurableSpace Ω} (outcome : ℕ → Ω → Out) (t : ℕ)
    (hind : ∀ ω' : Out, Measurable[m] (outcomeIndicator outcome t ω'))
    (f : Out → ℝ) :
    Measurable[m] (fun ω => f (outcome t ω)) := by
  have heq : (fun ω => f (outcome t ω))
      = fun ω => ∑ ω' : Out, f ω' * outcomeIndicator outcome t ω' ω := by
    funext ω
    unfold outcomeIndicator
    rw [Finset.sum_eq_single (outcome t ω)
      (fun ω' _ hne => by simp [Ne.symm hne]) (fun h => absurd (Finset.mem_univ _) h)]
    simp
  rw [heq]
  have hsum : ∀ s : Finset Out,
      Measurable[m] (fun ω => ∑ ω' ∈ s, f ω' * outcomeIndicator outcome t ω' ω) := by
    intro s
    refine Finset.induction_on s ?_ ?_
    · simp
    · intro a s' hx ih
      simp_rw [Finset.sum_insert hx]
      exact (measurable_const.mul (hind a)).add ih
  exact hsum Finset.univ

/-- The calibration squared loss is at most `2`: it equals `‖v‖² - 2 v(ω) + 1` for a simplex
point `v`, and `‖v‖² ≤ ∑ v = 1` while `v(ω) ≥ 0`. -/
lemma calibrationSqLoss_le_two {Out : Type*} [Fintype Out] [DecidableEq Out]
    (v : stdSimplex ℝ Out) (ω : Out) : calibrationSqLoss v ω ≤ 2 := by
  unfold calibrationSqLoss calibrationSqDistTo
  have hterm : ∀ ω' : Out, (v.val ω' - (if ω' = ω then (1 : ℝ) else 0)) ^ 2
      = v.val ω' ^ 2 - 2 * (if ω' = ω then v.val ω' else 0)
        + (if ω' = ω then (1 : ℝ) else 0) := fun ω' => by split <;> ring
  simp_rw [hterm]
  rw [Finset.sum_add_distrib, Finset.sum_sub_distrib, ← Finset.mul_sum,
    Fintype.sum_ite_eq' ω v.val, Fintype.sum_ite_eq' ω (fun _ : Out => (1 : ℝ))]
  have hsq_le : (∑ ω' : Out, v.val ω' ^ 2) ≤ 1 := by
    have h1 : ∀ ω' : Out, v.val ω' ^ 2 ≤ v.val ω' := fun ω' => by
      have h0 : 0 ≤ v.val ω' := v.2.1 ω'
      have h1' : v.val ω' ≤ 1 := by
        calc v.val ω' ≤ ∑ ω'' : Out, v.val ω'' :=
              Finset.single_le_sum (fun ω'' _ => v.2.1 ω'') (Finset.mem_univ ω')
          _ = 1 := v.2.2
      nlinarith [h0, h1']
    calc (∑ ω' : Out, v.val ω' ^ 2) ≤ ∑ ω' : Out, v.val ω' :=
          Finset.sum_le_sum (fun ω' _ => h1 ω')
      _ = 1 := v.2.2
  have hv_nonneg : 0 ≤ v.val ω := v.2.1 ω
  linarith [hsq_le, hv_nonneg]

/-- The forecasting rule in [MFoGT, Proposition 7.3.10]: apply internal-regret
matching to the forecast grid with payoff `-‖e_ω - v‖² / 2`. The factor `1/2`
keeps payoffs in `[-1, 1]`; positive rescaling does not change the selected
invariant measures. -/
noncomputable def calibratedForecastStrategy {Out : Type*} [Fintype Out] [DecidableEq Out]
    (V : ForecastGrid Out) [Nonempty V.point] : ForecastStrategy Out V :=
  fun n hist =>
    internalRegretMatchingStrategy V.point n
      (hist.1, fun t v => (2 : ℝ)⁻¹ * calibrationPayoff V (hist.2 t) v)

/-- Reinterpret a process generated by `calibratedForecastStrategy V` as one
generated by internal-regret matching on the halved calibration-loss payoff
process. -/
lemma isGeneratedByExternalStrategyAE_of_isGeneratedByForecastStrategyAE
    {Out : Type*} [Fintype Out] [DecidableEq Out] {V : ForecastGrid Out} [Nonempty V.point]
    {P : MeasureTheory.Measure Ω} {ℱ : MeasureTheory.Filtration ℕ mΩ}
    {forecast : ℕ → Ω → V.point} {outcome : ℕ → Ω → Out}
    (hgen : IsGeneratedByForecastStrategyAE P ℱ (calibratedForecastStrategy V) forecast outcome) :
    IsGeneratedByExternalStrategyAE P ℱ (internalRegretMatchingStrategy V.point) forecast
      (fun n ω v => (2 : ℝ)⁻¹ * calibrationPayoff V (outcome n ω) v) := by
  refine ⟨⟨?_, ?_⟩, ?_, ?_, ?_⟩
  · intro n t v
    exact hgen.historyAdapted.forecastHistory n t v
  · intro n t k
    exact measurable_of_outcomeIndicator outcome t.val (hgen.historyAdapted.outcomeHistory n t)
      (fun ω' => (2 : ℝ)⁻¹ * calibrationPayoff V ω' k)
  · intro n v
    exact hgen.strategyProbabilityMeasurable n v
  · intro n v
    exact hgen.condProb n v
  · intro n k
    exact measurable_of_outcomeIndicator outcome n (hgen.outcomePredictable n)
      (fun ω' => (2 : ℝ)⁻¹ * calibrationPayoff V ω' k)

/-- The halved calibration payoff always lies in `[-1, 1]`. -/
lemma isBoundedPayoffProcessAE_calibrationPayoff_half {Out : Type*} [Fintype Out] [DecidableEq Out]
    (V : ForecastGrid Out) (P : MeasureTheory.Measure Ω) (outcome : ℕ → Ω → Out) :
    IsBoundedPayoffProcessAE P (fun n ω v => (2 : ℝ)⁻¹ * calibrationPayoff V (outcome n ω) v) := by
  filter_upwards with ω
  intro n v
  unfold calibrationPayoff
  have hloss_nonneg : 0 ≤ calibrationSqLoss (V.forecast v) (outcome n ω) := by
    unfold calibrationSqLoss calibrationSqDistTo
    exact Finset.sum_nonneg fun ω' _ => sq_nonneg _
  have hloss_le := calibrationSqLoss_le_two (V.forecast v) (outcome n ω)
  constructor <;> nlinarith

/-- Internal-regret step of [MFoGT, Proposition 7.3.10]. A process generated by
`calibratedForecastStrategy V` has no internal regret almost surely for the
unscaled calibration payoff. -/
theorem calibratedForecastStrategy_hasNoInternalRegretAE_of_generatedProcess
    {Out : Type*} [Fintype Out] [DecidableEq Out] (V : ForecastGrid Out) [Nonempty V.point]
    (P : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure P]
    (ℱ : MeasureTheory.Filtration ℕ mΩ)
    {forecast : ℕ → Ω → V.point} {outcome : ℕ → Ω → Out}
    (hgen : IsGeneratedByForecastStrategyAE P ℱ (calibratedForecastStrategy V) forecast outcome) :
    HasNoInternalRegretAE P forecast (fun n ω v => calibrationPayoff V (outcome n ω) v) := by
  have hgen' := isGeneratedByExternalStrategyAE_of_isGeneratedByForecastStrategyAE hgen
  have hbdd := isBoundedPayoffProcessAE_calibrationPayoff_half V P outcome
  have hno := internalRegretMatchingStrategy_hasNoInternalRegretOnGeneratedProcessesAE P ℱ forecast
    (fun n ω v => (2 : ℝ)⁻¹ * calibrationPayoff V (outcome n ω) v) hgen' hbdd
  filter_upwards [hno] with ω hω
  intro j ℓ
  have heq : (fun n => posPart (averageInternalRegret (fun m => forecast m ω)
        (fun m v => (2 : ℝ)⁻¹ * calibrationPayoff V (outcome m ω) v) n j ℓ))
      = fun n => (2 : ℝ)⁻¹ * posPart (averageInternalRegret (fun m => forecast m ω)
        (fun m v => calibrationPayoff V (outcome m ω) v) n j ℓ) := by
    funext n
    rw [averageInternalRegret_const_smul (2 : ℝ)⁻¹ (fun m => forecast m ω)
      (fun m v => calibrationPayoff V (outcome m ω) v) n j ℓ,
      posPart_pos_smul (by norm_num : (0 : ℝ) < (2 : ℝ)⁻¹)]
  have hωjl := hω j ℓ
  rw [heq] at hωjl
  exact (vanishesAboveZero_const_smul_iff (by norm_num : (0 : ℝ) < (2 : ℝ)⁻¹) _).mp hωjl

/-- The forecast grid `V` has `L2` mesh at most `δ`: every point of the simplex over outcomes is
within squared distance `δ²` of some grid point's forecast. -/
def _root_.StrategicGame.ForecastGrid.MeshLe {Out : Type*} [Fintype Out] [DecidableEq Out]
    (V : ForecastGrid Out) (δ : ℝ) : Prop :=
  ∀ x : stdSimplex ℝ Out, ∃ w : V.point, calibrationSqDistTo (V.forecast w) x.val ≤ δ ^ 2

/-- The empirical joint use/outcome frequency, summed over outcomes, recovers the use
frequency: every stage where `v` is forecast contributes exactly one realized outcome. -/
lemma sum_forecastOutcomeFrequency_eq_forecastUseFrequency {Out : Type*} [Fintype Out]
    [DecidableEq Out] {V : ForecastGrid Out} (forecast : ℕ → V.point) (outcome : ℕ → Out)
    (n : ℕ) (v : V.point) :
    ∑ ω : Out, forecastOutcomeFrequency forecast outcome n v ω
      = forecastUseFrequency forecast n v := by
  have h := sum_indicator_mul_apply_eq forecast outcome n v (fun _ : Out => (1 : ℝ))
  simp only [mul_one, one_mul] at h
  unfold forecastUseFrequency
  exact h.symm

/-- The empirical conditional outcome distribution is itself a point of the standard simplex. -/
lemma conditionalOutcomeFrequency_mem_stdSimplex {Out : Type*} [Fintype Out] [DecidableEq Out]
    {V : ForecastGrid Out} (forecast : ℕ → V.point) (outcome : ℕ → Out) (n : ℕ) (v : V.point) :
    conditionalOutcomeFrequency forecast outcome n v ∈ stdSimplex ℝ Out := by
  by_cases h : forecastUseFrequency forecast n v = 0
  · have heq : conditionalOutcomeFrequency forecast outcome n v = (V.forecast v).val := by
      funext ω; unfold conditionalOutcomeFrequency; rw [if_pos h]
    rw [heq]; exact (V.forecast v).2
  · have heq : conditionalOutcomeFrequency forecast outcome n v
        = fun ω => forecastOutcomeFrequency forecast outcome n v ω / forecastUseFrequency forecast n v := by
      funext ω; unfold conditionalOutcomeFrequency; rw [if_neg h]
    rw [heq]
    have hUse_nonneg : 0 ≤ forecastUseFrequency forecast n v := by
      unfold forecastUseFrequency; positivity
    have hUse_pos : 0 < forecastUseFrequency forecast n v := hUse_nonneg.lt_of_ne (Ne.symm h)
    refine ⟨fun ω => ?_, ?_⟩
    · have hOF_nonneg : 0 ≤ forecastOutcomeFrequency forecast outcome n v ω := by
        unfold forecastOutcomeFrequency; positivity
      exact div_nonneg hOF_nonneg hUse_pos.le
    · rw [← Finset.sum_div, sum_forecastOutcomeFrequency_eq_forecastUseFrequency, div_self h]

/-- The empirical use frequencies of the (finitely many) forecast grid points always sum to
`1`: every stage announces exactly one forecast. -/
lemma sum_forecastUseFrequency_eq_one {Out : Type*} [Fintype Out] {V : ForecastGrid Out}
    (forecast : ℕ → V.point) (n : ℕ) :
    ∑ v : V.point, forecastUseFrequency forecast n v = 1 := by
  unfold forecastUseFrequency
  rw [← Finset.mul_sum, Finset.sum_comm]
  have hinner : ∀ t : Fin (n + 1),
      ∑ v : V.point, (if forecast t.val = v then (1 : ℝ) else 0) = 1 :=
    fun t => Fintype.sum_ite_eq (forecast t.val) (fun _ : V.point => (1 : ℝ))
  simp_rw [hinner]
  rw [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul, mul_one, Nat.cast_add_one]
  exact inv_mul_cancel₀ (by positivity : ((n : ℝ) + 1) ≠ 0)

/-- If, for finitely many indices, a family of sequences each vanishes above zero (after taking
positive part), there is a single stage beyond which the underlying (non-truncated) sequences
are all simultaneously below any given tolerance. -/
lemma exists_uniform_regret_bound {K : Type*} [Fintype K] (a : K → K → ℕ → ℝ)
    (h : ∀ v w : K, VanishesAboveZero fun n => posPart (a v w n)) {η : ℝ} (hη : 0 < η) :
    ∃ N : ℕ, ∀ n ≥ N, ∀ v w : K, a v w n ≤ η := by
  choose N hN using fun vw : K × K => h vw.1 vw.2 η hη
  refine ⟨Finset.univ.sup N, fun n hn v w => ?_⟩
  have hbound := hN (v, w) n (le_trans (Finset.le_sup (Finset.mem_univ (v, w))) hn)
  exact (le_max_left (a v w n) 0).trans hbound

/-- The calibration error's summand matches the polarization-friendly `calibrationSqDistTo`. -/
lemma calibrationError_eq_sum_sqrt_calibrationSqDistTo {Out : Type*} [Fintype Out]
    [DecidableEq Out] {V : ForecastGrid Out} (forecast : ℕ → V.point) (outcome : ℕ → Out)
    (n : ℕ) :
    calibrationError V forecast outcome n
      = ∑ v : V.point, forecastUseFrequency forecast n v *
          Real.sqrt (calibrationSqDistTo (V.forecast v)
            (conditionalOutcomeFrequency forecast outcome n v)) := by
  unfold calibrationError calibrationSqDistTo
  refine Finset.sum_congr rfl fun v _ => ?_
  congr 2
  exact Finset.sum_congr rfl fun ω _ => by ring

/-- Reduction step of [MFoGT, Proposition 7.3.10]. No internal regret for the
calibration loss on a grid of `L2` mesh at most `δ` implies pathwise
`δ`-calibration. -/
theorem isEpsilonCalibrated_of_hasNoInternalRegret {Out : Type*} [Fintype Out] [DecidableEq Out]
    {V : ForecastGrid Out} [Nonempty V.point] {δ : ℝ} (hδ : 0 ≤ δ) (hmesh : V.MeshLe δ)
    {forecast : ℕ → V.point} {outcome : ℕ → Out}
    (hNoRegret : HasNoInternalRegret forecast (fun t v => calibrationPayoff V (outcome t) v)) :
    VanishesAboveZero fun n => calibrationError V forecast outcome n - δ := by
  intro η hη
  set C : ℝ := (Fintype.card V.point : ℝ) with hC_def
  have hC_pos : 0 < C := by
    rw [hC_def]; exact_mod_cast Fintype.card_pos
  set η' : ℝ := ((δ + η) ^ 2 - δ ^ 2) / C with hη'_def
  have hη'_pos : 0 < η' := by
    rw [hη'_def]; apply div_pos _ hC_pos; nlinarith
  obtain ⟨N, hN⟩ := exists_uniform_regret_bound
    (fun v w n => averageInternalRegret forecast (fun t => calibrationPayoff V (outcome t)) n v w)
    hNoRegret hη'_pos
  refine ⟨N, fun n hn => ?_⟩
  have hperv : ∀ v : V.point,
      forecastUseFrequency forecast n v *
          calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v)
        ≤ forecastUseFrequency forecast n v * δ ^ 2 + η' := by
    intro v
    obtain ⟨w, hw⟩ := hmesh ⟨conditionalOutcomeFrequency forecast outcome n v,
      conditionalOutcomeFrequency_mem_stdSimplex forecast outcome n v⟩
    have hregret := hN n hn v w
    rw [averageInternalRegret_calibrationPayoff_eq] at hregret
    have hUse_nonneg : 0 ≤ forecastUseFrequency forecast n v := by
      unfold forecastUseFrequency; positivity
    nlinarith [hregret, hw, mul_le_mul_of_nonneg_left hw hUse_nonneg]
  have hsum_le : (∑ v : V.point,
        forecastUseFrequency forecast n v *
          calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v))
      ≤ δ ^ 2 + C * η' := by
    calc (∑ v : V.point,
          forecastUseFrequency forecast n v *
            calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v))
        ≤ ∑ v : V.point, (forecastUseFrequency forecast n v * δ ^ 2 + η') :=
          Finset.sum_le_sum fun v _ => hperv v
      _ = δ ^ 2 * ∑ v : V.point, forecastUseFrequency forecast n v + C * η' := by
          rw [Finset.sum_add_distrib, Finset.sum_const, Finset.card_univ, nsmul_eq_mul, hC_def,
            ← Finset.sum_mul]
          ring
      _ = δ ^ 2 + C * η' := by rw [sum_forecastUseFrequency_eq_one]; ring
  have hCS : (calibrationError V forecast outcome n) ^ 2
      ≤ ∑ v : V.point,
          forecastUseFrequency forecast n v *
            calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v) := by
    rw [calibrationError_eq_sum_sqrt_calibrationSqDistTo]
    have hD_nonneg : ∀ v : V.point,
        0 ≤ calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v) := by
      intro v; unfold calibrationSqDistTo; exact Finset.sum_nonneg fun ω _ => sq_nonneg _
    have hUse_nonneg : ∀ v : V.point, 0 ≤ forecastUseFrequency forecast n v := by
      intro v; unfold forecastUseFrequency; positivity
    have hkey := sum_mul_sq_le_sq_mul_sq Finset.univ
      (fun v : V.point => Real.sqrt (forecastUseFrequency forecast n v))
      (fun v : V.point => Real.sqrt (forecastUseFrequency forecast n v) *
        Real.sqrt (calibrationSqDistTo (V.forecast v)
          (conditionalOutcomeFrequency forecast outcome n v)))
    have hlhs : ∀ v : V.point, Real.sqrt (forecastUseFrequency forecast n v) *
        (Real.sqrt (forecastUseFrequency forecast n v) *
          Real.sqrt (calibrationSqDistTo (V.forecast v)
            (conditionalOutcomeFrequency forecast outcome n v)))
        = forecastUseFrequency forecast n v *
          Real.sqrt (calibrationSqDistTo (V.forecast v)
            (conditionalOutcomeFrequency forecast outcome n v)) := by
      intro v; rw [← mul_assoc, Real.mul_self_sqrt (hUse_nonneg v)]
    have hrhs1 : ∀ v : V.point, Real.sqrt (forecastUseFrequency forecast n v) ^ 2
        = forecastUseFrequency forecast n v := fun v => Real.sq_sqrt (hUse_nonneg v)
    have hrhs2 : ∀ v : V.point,
        (Real.sqrt (forecastUseFrequency forecast n v) *
          Real.sqrt (calibrationSqDistTo (V.forecast v)
            (conditionalOutcomeFrequency forecast outcome n v))) ^ 2
        = forecastUseFrequency forecast n v *
          calibrationSqDistTo (V.forecast v) (conditionalOutcomeFrequency forecast outcome n v) := by
      intro v
      rw [mul_pow, Real.sq_sqrt (hUse_nonneg v), Real.sq_sqrt (hD_nonneg v)]
    simp_rw [hlhs] at hkey
    simp_rw [hrhs1, hrhs2] at hkey
    rwa [sum_forecastUseFrequency_eq_one, one_mul] at hkey
  have hCE_le : (calibrationError V forecast outcome n) ^ 2 ≤ (δ + η) ^ 2 := by
    have hcomb := hCS.trans hsum_le
    have hCη' : C * η' = (δ + η) ^ 2 - δ ^ 2 := by rw [hη'_def]; field_simp
    rw [hCη'] at hcomb
    linarith
  have hce_nonneg : 0 ≤ calibrationError V forecast outcome n := by
    unfold calibrationError
    exact Finset.sum_nonneg fun v _ => mul_nonneg
      (by unfold forecastUseFrequency; positivity) (Real.sqrt_nonneg _)
  have hde_nonneg : 0 ≤ δ + η := by linarith
  have hsqrt := Real.sqrt_le_sqrt hCE_le
  rw [Real.sqrt_sq hce_nonneg, Real.sqrt_sq hde_nonneg] at hsqrt
  linarith

/-- Finite-grid step of [MFoGT, Proposition 7.3.10]. Compactness of the
standard simplex gives a nonempty finite forecast grid of any prescribed
positive `L2` mesh. -/
lemma exists_forecastGrid_meshLe (Out : Type*) [Fintype Out] [DecidableEq Out] [Nonempty Out]
    {δ : ℝ} (hδ : 0 < δ) :
    ∃ V : ForecastGrid Out, Nonempty V.point ∧ V.MeshLe δ := by
  classical
  have hcont : ∀ y : stdSimplex ℝ Out,
      Continuous (fun x : stdSimplex ℝ Out => calibrationSqDistTo y x.val) := by
    intro y
    unfold calibrationSqDistTo
    refine continuous_finsetSum Finset.univ (fun ω' _ => ?_)
    exact (continuous_const.sub ((continuous_apply ω').comp continuous_subtype_val)).pow 2
  have hUopen : ∀ y : stdSimplex ℝ Out,
      IsOpen {x : stdSimplex ℝ Out | calibrationSqDistTo y x.val < δ ^ 2} :=
    fun y => isOpen_lt (hcont y) continuous_const
  have hUcover : (Set.univ : Set (stdSimplex ℝ Out))
      ⊆ ⋃ y : stdSimplex ℝ Out, {x : stdSimplex ℝ Out | calibrationSqDistTo y x.val < δ ^ 2} := by
    intro x _
    refine Set.mem_iUnion.mpr ⟨x, ?_⟩
    have hzero : calibrationSqDistTo x x.val = 0 := by unfold calibrationSqDistTo; simp
    show calibrationSqDistTo x x.val < δ ^ 2
    rw [hzero]; exact pow_pos hδ 2
  obtain ⟨t, ht_sub⟩ :=
    isCompact_univ.elim_finite_subcover
      (fun y : stdSimplex ℝ Out => {x : stdSimplex ℝ Out | calibrationSqDistTo y x.val < δ ^ 2})
      hUopen hUcover
  have ht_ne : t.Nonempty := by
    rcases t.eq_empty_or_nonempty with hempty | hne
    · exact absurd (ht_sub (Set.mem_univ (Classical.arbitrary (stdSimplex ℝ Out))))
        (by simp [hempty])
    · exact hne
  obtain ⟨y0, hy0⟩ := ht_ne
  refine ⟨{ point := { y // y ∈ t }
            pointFintype := inferInstance
            pointDecidableEq := inferInstance
            forecast := fun p => p.val
            forecast_injective := Subtype.val_injective }, ⟨⟨y0, hy0⟩⟩, ?_⟩
  intro x
  obtain ⟨y, hy_mem, hy⟩ := Set.mem_iUnion₂.mp (ht_sub (Set.mem_univ x))
  exact ⟨⟨y, hy_mem⟩, le_of_lt hy⟩

/-- Conditional process form of [MFoGT, Proposition 7.3.10]. For every
`ε > 0`, internal-regret matching on a suitable finite grid is ε-calibrated
almost surely against every predictable outcome process that it generates. -/
theorem exists_forecastRule_isEpsilonCalibratedOnGeneratedProcessesAE
    (Out : Type*) [Fintype Out] [DecidableEq Out] [Nonempty Out]
    (P : MeasureTheory.Measure Ω) [MeasureTheory.IsProbabilityMeasure P]
    (ℱ : MeasureTheory.Filtration ℕ mΩ) {ε : ℝ} (hε : 0 < ε) :
    ∃ (V : ForecastGrid Out) (φ : ForecastStrategy Out V),
      Nonempty V.point ∧
        IsEpsilonCalibratedOnGeneratedProcessesAE P ℱ V ε φ := by
  obtain ⟨V, hVne, hVmesh⟩ := exists_forecastGrid_meshLe Out hε
  haveI := hVne
  refine ⟨V, calibratedForecastStrategy V, hVne, ?_⟩
  intro forecast outcome hgen
  have hno := calibratedForecastStrategy_hasNoInternalRegretAE_of_generatedProcess V P ℱ hgen
  unfold IsEpsilonCalibratedAE IsEpsilonCalibrated
  filter_upwards [hno] with ω hω
  exact isEpsilonCalibrated_of_hasNoInternalRegret hε.le hVmesh hω

end NoRegretProbability

end StrategicGame
