/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Interface.Execution.Finite
import EconCSLib.GameTheory.ExtensiveGame.Execution.InfiniteTrajectory
import EconCSLib.GameTheory.ExtensiveGame.Observed.Controlled.Law.DiscretePath
import EconCSLib.GameTheory.ExtensiveGame.Observed.InfiniteExecution

/-!
# Infinite discrete event-time EFG execution

Stable public import for terminal-absorbing probability laws on infinite
natural-number-indexed histories generated by discrete PMF policies.

It extends `Interface.Execution.Finite` with the representation-independent
lawful probability carrier, its discrete behavioral implementation,
Ionescu--Tulcea path measures, coordinate recovery, almost-sure termination,
stopped/terminal payoffs, and expectation convergence. MeasureTheory is
intrinsic to this infinite-path surface even though every local action law is
a PMF. Non-atomic
`MeasurableKernelArena` execution remains in `Interface.Execution.Analytic`.
-/
