/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Observed.Mixed

/-!
# Discrete general strategies

A discrete general strategy is an ex-ante `PMF` over behavioral strategies.
It is distinct from:

* a behavioral strategy, which independently randomizes locally;
* a mixed strategy, which randomizes over complete pure plans;
* an analytic general strategy, which needs a probability measure and a
  measurable behavioral-strategy space.

This module defines the strategy carriers and their elementary embeddings. It
does not claim that countably supported `PMF`s exhaust textbook general
strategies on infinite or continuous strategy spaces, and it does not add an
execution law before the required conditional measurability is available.
-/

namespace ExtensiveGame.ObservedGame

variable {N U : Type*} (G : ObservedGame N U)

/-- Countably supported ex-ante randomization over behavioral strategies.

The `Discrete` qualifier is semantic: this is a `PMF`, not an arbitrary
probability measure on a measurable behavioral-strategy space. -/
abbrev DiscreteGeneralStrategy (i : N) :=
  PMF (G.BehavioralStrategy i)

/-- One discrete general strategy for every player. -/
abbrev DiscreteGeneralProfile :=
  (i : N) → G.DiscreteGeneralStrategy i

/-- Compatibility alias for the former overly broad name. -/
@[deprecated DiscreteGeneralStrategy (since := "2026-07-31")]
abbrev GeneralStrategy := G.DiscreteGeneralStrategy

/-- Compatibility alias for the former overly broad profile name. -/
@[deprecated DiscreteGeneralProfile (since := "2026-07-31")]
abbrev GeneralProfile := G.DiscreteGeneralProfile

/-- Embed one behavioral strategy as a Dirac discrete general strategy. -/
noncomputable def BehavioralStrategy.toDiscreteGeneral {i : N}
    (strategy : G.BehavioralStrategy i) :
    G.DiscreteGeneralStrategy i :=
  PMF.pure strategy

/-- Embed a behavioral profile componentwise as a discrete general profile.
-/
noncomputable def BehavioralProfile.toDiscreteGeneral
    (profile : G.BehavioralProfile) :
    G.DiscreteGeneralProfile :=
  fun i => (profile i).toDiscreteGeneral G

/-- Embed a pure contingent plan as a Dirac discrete general strategy
concentrated on its point-mass behavioral strategy. -/
noncomputable def PureStrategy.toDiscreteGeneral {i : N}
    (strategy : G.PureStrategy i) :
    G.DiscreteGeneralStrategy i :=
  (strategy.toBehavioral G).toDiscreteGeneral G

/-- Embed a pure profile componentwise as a discrete general profile. -/
noncomputable def PureProfile.toDiscreteGeneral
    (profile : G.PureProfile) :
    G.DiscreteGeneralProfile :=
  fun i => (profile i).toDiscreteGeneral G

namespace DiscreteGeneralProfile

/-- The independent joint law on behavioral profiles generated by a discrete
general profile.

A directly supplied `PMF G.BehavioralProfile` would instead allow correlation
between players and is therefore a different semantic object. -/
noncomputable def behavioralProfileLaw [Fintype N]
    (profile : G.DiscreteGeneralProfile) :
    PMF G.BehavioralProfile :=
  PMF.fintypePi profile

/-- Replace one player's general strategy. -/
def deviate [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who : N)
    (deviation : G.DiscreteGeneralStrategy who) :
    G.DiscreteGeneralProfile :=
  Function.update profile who deviation

@[simp]
theorem deviate_same [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who : N)
    (deviation : G.DiscreteGeneralStrategy who) :
    profile.deviate G who deviation who = deviation := by
  simp [deviate]

@[simp]
theorem deviate_of_ne [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who other : N)
    (deviation : G.DiscreteGeneralStrategy who)
    (hne : other ≠ who) :
    profile.deviate G who deviation other =
      profile other := by
  simp [deviate, hne]

end DiscreteGeneralProfile

/-! Compatibility names for the pre-qualification API. -/

/-- Compatibility alias for `BehavioralStrategy.toDiscreteGeneral`. -/
@[deprecated BehavioralStrategy.toDiscreteGeneral (since := "2026-07-31")]
noncomputable abbrev BehavioralStrategy.toGeneral :=
  @BehavioralStrategy.toDiscreteGeneral

/-- Compatibility alias for `BehavioralProfile.toDiscreteGeneral`. -/
@[deprecated BehavioralProfile.toDiscreteGeneral (since := "2026-07-31")]
noncomputable abbrev BehavioralProfile.toGeneral :=
  @BehavioralProfile.toDiscreteGeneral

/-- Compatibility alias for `PureStrategy.toDiscreteGeneral`. -/
@[deprecated PureStrategy.toDiscreteGeneral (since := "2026-07-31")]
noncomputable abbrev PureStrategy.toGeneral :=
  @PureStrategy.toDiscreteGeneral

/-- Compatibility alias for `PureProfile.toDiscreteGeneral`. -/
@[deprecated PureProfile.toDiscreteGeneral (since := "2026-07-31")]
noncomputable abbrev PureProfile.toGeneral :=
  @PureProfile.toDiscreteGeneral

namespace GeneralProfile

/-- Compatibility alias for the discrete product law. -/
@[deprecated DiscreteGeneralProfile.behavioralProfileLaw
  (since := "2026-07-31")]
noncomputable abbrev behavioralProfileLaw :=
  @DiscreteGeneralProfile.behavioralProfileLaw

/-- Compatibility alias for discrete general-profile deviation. -/
@[deprecated DiscreteGeneralProfile.deviate (since := "2026-07-31")]
abbrev deviate := @DiscreteGeneralProfile.deviate

/-- Compatibility theorem for deviation at the changed player. -/
@[deprecated DiscreteGeneralProfile.deviate_same
  (since := "2026-07-31")]
theorem deviate_same [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who : N)
    (deviation : G.DiscreteGeneralStrategy who) :
    DiscreteGeneralProfile.deviate G profile who deviation who =
      deviation :=
  DiscreteGeneralProfile.deviate_same G profile who deviation

/-- Compatibility theorem for deviation at another player. -/
@[deprecated DiscreteGeneralProfile.deviate_of_ne
  (since := "2026-07-31")]
theorem deviate_of_ne [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who other : N)
    (deviation : G.DiscreteGeneralStrategy who)
    (hne : other ≠ who) :
    DiscreteGeneralProfile.deviate G profile who deviation other =
      profile other :=
  DiscreteGeneralProfile.deviate_of_ne G profile who other deviation hne

end GeneralProfile

end ExtensiveGame.ObservedGame
