/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Observed.Mixed

/-!
# Discrete general strategies

A discrete general strategy is an ex-ante `FiniteLaw` over behavioral strategies.
It is distinct from:

* a behavioral strategy, which independently randomizes locally;
* a mixed strategy, which randomizes over complete pure plans;
* an analytic general strategy, which needs a probability measure and a
  measurable behavioral-strategy space.

This module defines the strategy carriers and their elementary embeddings. It
does not claim that finite laws exhaust textbook general strategies on
infinite or continuous strategy spaces, and it does not add an
execution law before the required conditional measurability is available.
-/

namespace ExtensiveGame.ObservedGame

variable {N U : Type*} (G : ObservedGame N U)

/-- Finitely supported ex-ante randomization over behavioral strategies.

The `Discrete` qualifier is semantic: this is a `FiniteLaw`, not an arbitrary
probability measure on a measurable behavioral-strategy space. -/
abbrev DiscreteGeneralStrategy (i : N) :=
  FiniteLaw (G.BehavioralStrategy i)

/-- One discrete general strategy for every player. -/
abbrev DiscreteGeneralProfile :=
  (i : N) → G.DiscreteGeneralStrategy i

/-- Embed one behavioral strategy as a Dirac discrete general strategy. -/
def BehavioralStrategy.toDiscreteGeneral {i : N}
    (strategy : G.BehavioralStrategy i) :
    G.DiscreteGeneralStrategy i :=
  FiniteLaw.pure strategy

/-- Embed a behavioral profile componentwise as a discrete general profile.
-/
def BehavioralProfile.toDiscreteGeneral
    (profile : G.BehavioralProfile) :
    G.DiscreteGeneralProfile :=
  fun i =>
    ObservedGame.BehavioralStrategy.toDiscreteGeneral
      G (profile i)

/-- Embed a pure contingent plan as a Dirac discrete general strategy
concentrated on its point-mass behavioral strategy. -/
def PureStrategy.toDiscreteGeneral {i : N}
    (strategy : G.PureStrategy i) :
    G.DiscreteGeneralStrategy i :=
  ObservedGame.BehavioralStrategy.toDiscreteGeneral G
    (ObservedGame.PureStrategy.toBehavioral G strategy)

/-- Embed a pure profile componentwise as a discrete general profile. -/
def PureProfile.toDiscreteGeneral
    (profile : G.PureProfile) :
    G.DiscreteGeneralProfile :=
  fun i =>
    ObservedGame.PureStrategy.toDiscreteGeneral
      G (profile i)

namespace DiscreteGeneralProfile

/-- The independent joint law on behavioral profiles generated by a discrete
general profile.

A directly supplied `FiniteLaw G.BehavioralProfile` would instead allow correlation
between players and is therefore a different semantic object. -/
def behavioralProfileLaw [Fintype N] [LinearOrder N]
    (profile : G.DiscreteGeneralProfile) :
    FiniteLaw G.BehavioralProfile :=
  FiniteLaw.fintypePi profile

/-- Replace one player's general strategy. -/
def deviate [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who : N)
    (deviation : G.DiscreteGeneralStrategy who) :
    G.DiscreteGeneralProfile :=
  Function.update profile who deviation

@[simp]
theorem deviate_same [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who : N)
    (deviation : G.DiscreteGeneralStrategy who) :
    profile.deviate G who deviation who = deviation := by
  simp [deviate]

@[simp]
theorem deviate_of_ne [DecidableEq N]
    (profile : G.DiscreteGeneralProfile) (who other : N)
    (deviation : G.DiscreteGeneralStrategy who)
    (hne : other ≠ who) :
    profile.deviate G who deviation other =
      profile other := by
  simp [deviate, hne]

end DiscreteGeneralProfile

end ExtensiveGame.ObservedGame
