/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.ExtensiveGame.Observed.General
import Mathlib.MeasureTheory.Measure.ProbabilityMeasure

/-!
# Arbitrary-measure pure-strategy laws

This module defines probability measures on explicitly measurable pure
strategy and pure-profile carriers. It does not infer a measurable structure
on dependent function spaces.

`ArbitraryMeasurePureProfileLaw` is a joint law on complete pure profiles and
may correlate players. It is different from `MixedProfile`, whose finite-player
PMF semantics samples player plans independently, and from
`DiscreteGeneralProfile`, whose carrier is a playerwise PMF over behavioral
strategies.

The primitive semantics is measurable pushforward through a caller-certified
profile evaluator. Pure and PMF laws embed exactly, and PMF pushforward agrees
as a complete measure. No unrestricted arbitrary-measure Kuhn equivalence is
claimed: measurable evaluation, recall, standard-Borel disintegration,
independence, and null-information conditioning remain explicit downstream
obligations. See `docs/design/efg-arbitrary-measure-strategies.md`.
-/

open MeasureTheory

namespace ExtensiveGame.ObservedGame

universe uN uU uOutcome

variable {N : Type uN} {U : Type uU}

/-- Explicit measurable structures for dependent pure strategies and complete
pure profiles.

The coordinate condition is the minimum bridge needed to recover player
marginals from a joint profile law. It does not assert that the profile space
is a product measurable space or that arbitrary player laws admit an
independent product. -/
structure PureProfileMeasurableModel (G : ObservedGame N U) where
  /-- Measurable space on each player's complete pure-strategy carrier. -/
  strategyMeasurableSpace :
    (i : N) → MeasurableSpace (G.PureStrategy i)
  /-- Measurable space on complete pure profiles. -/
  profileMeasurableSpace : MeasurableSpace G.PureProfile
  /-- Every player-coordinate projection is measurable. -/
  coordinate_measurable :
    ∀ i : N,
      @Measurable G.PureProfile (G.PureStrategy i)
        profileMeasurableSpace (strategyMeasurableSpace i)
        (fun profile => profile i)

variable {G : ObservedGame N U}

/-- An arbitrary probability measure on one explicitly measurable pure
strategy carrier. -/
abbrev ArbitraryMeasurePureStrategy
    (model : G.PureProfileMeasurableModel) (i : N) :=
  @ProbabilityMeasure (G.PureStrategy i)
    (model.strategyMeasurableSpace i)

/-- A joint, potentially correlated arbitrary probability measure on complete
pure profiles. -/
abbrev ArbitraryMeasurePureProfileLaw
    (model : G.PureProfileMeasurableModel) :=
  @ProbabilityMeasure G.PureProfile model.profileMeasurableSpace

namespace ArbitraryMeasurePureProfileLaw

variable (model : G.PureProfileMeasurableModel)

/-- Embed one complete pure profile as a Dirac probability law. -/
noncomputable def ofPure (profile : G.PureProfile) :
    G.ArbitraryMeasurePureProfileLaw model := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  exact
    ⟨Measure.dirac profile,
      Measure.dirac.isProbabilityMeasure⟩

/-- Embed a countably supported law on complete pure profiles as its Mathlib
probability measure. -/
noncomputable def ofPMF (law : PMF G.PureProfile) :
    G.ArbitraryMeasurePureProfileLaw model := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  exact ⟨law.toMeasure, inferInstance⟩

/-- Push a joint pure-profile law through an explicitly measurable evaluator.
-/
noncomputable def outcomeLaw
    (law : G.ArbitraryMeasurePureProfileLaw model)
    {Outcome : Type uOutcome} [MeasurableSpace Outcome]
    (evaluate : G.PureProfile → Outcome)
    (hevaluate :
      @Measurable G.PureProfile Outcome
        model.profileMeasurableSpace inferInstance evaluate) :
    ProbabilityMeasure Outcome := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  exact ProbabilityMeasure.map law hevaluate.aemeasurable

/-- Complete-path law generated by a measurable pure-profile executor.

The executor is supplied explicitly because measurability of EFG execution
does not follow from the carrier alone. -/
noncomputable def pathLaw
    (law : G.ArbitraryMeasurePureProfileLaw model)
    [MeasurableSpace G.base.CompletePlay]
    (execute : G.PureProfile → G.base.CompletePlay)
    (hexecute :
      @Measurable G.PureProfile G.base.CompletePlay
        model.profileMeasurableSpace inferInstance execute) :
    ProbabilityMeasure G.base.CompletePlay := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  exact law.outcomeLaw model execute hexecute

/-- The underlying measure of a PMF embedding is definitionally
`PMF.toMeasure`. -/
@[simp]
theorem toMeasure_ofPMF (law : PMF G.PureProfile) :
    @ProbabilityMeasure.toMeasure G.PureProfile
        model.profileMeasurableSpace (ofPMF model law) =
      @PMF.toMeasure G.PureProfile model.profileMeasurableSpace law :=
  rfl

/-- Measurable semantics of a PMF embedding agrees with the existing PMF
pushforward as a complete outcome measure. -/
theorem outcomeLaw_ofPMF
    (law : PMF G.PureProfile)
    {Outcome : Type uOutcome} [MeasurableSpace Outcome]
    (evaluate : G.PureProfile → Outcome)
    (hevaluate :
      @Measurable G.PureProfile Outcome
        model.profileMeasurableSpace inferInstance evaluate) :
    ((outcomeLaw model (ofPMF model law) evaluate hevaluate :
        ProbabilityMeasure Outcome) : Measure Outcome) =
      (law.map evaluate).toMeasure := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  change
    (@PMF.toMeasure G.PureProfile model.profileMeasurableSpace law).map
        evaluate =
      (law.map evaluate).toMeasure
  exact PMF.toMeasure_map evaluate law hevaluate

/-- A pure profile embedded through the PMF route agrees with the direct
Dirac embedding. -/
theorem ofPMF_pure (profile : G.PureProfile) :
    ofPMF model (PMF.pure profile) =
      ofPure model profile := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  apply ProbabilityMeasure.toMeasure_injective
  exact @PMF.toMeasure_pure
    G.PureProfile profile model.profileMeasurableSpace

/-- The marginal law of one player is the measurable pushforward of the joint
profile law through that coordinate. -/
noncomputable def marginal
    (law : G.ArbitraryMeasurePureProfileLaw model)
    (i : N) :
    G.ArbitraryMeasurePureStrategy model i := by
  letI : MeasurableSpace G.PureProfile :=
    model.profileMeasurableSpace
  letI : MeasurableSpace (G.PureStrategy i) :=
    model.strategyMeasurableSpace i
  exact
    ProbabilityMeasure.map law
      (model.coordinate_measurable i).aemeasurable

end ArbitraryMeasurePureProfileLaw

namespace MixedProfile

/-- Embed the existing finite-player independent mixed profile into the
arbitrary-measure joint carrier.

Independence is established first by `pureProfileLaw`; `ofPMF` then changes
only the law representation. -/
noncomputable def toArbitraryMeasurePureProfileLaw
    [Fintype N]
    (model : G.PureProfileMeasurableModel)
    (profile : G.MixedProfile) :
    G.ArbitraryMeasurePureProfileLaw model :=
  ArbitraryMeasurePureProfileLaw.ofPMF model
    (profile.pureProfileLaw G)

/-- The arbitrary-measure embedding of an existing mixed profile has exactly
the `PMF.toMeasure` joint law. -/
theorem toMeasure_toArbitraryMeasurePureProfileLaw
    [Fintype N]
    (model : G.PureProfileMeasurableModel)
    (profile : G.MixedProfile) :
    @ProbabilityMeasure.toMeasure G.PureProfile
        model.profileMeasurableSpace
        (profile.toArbitraryMeasurePureProfileLaw model) =
      @PMF.toMeasure G.PureProfile model.profileMeasurableSpace
        (profile.pureProfileLaw G) :=
  rfl

end MixedProfile

end ExtensiveGame.ObservedGame
