/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.Math.Probability.FiniteLaw.Product
import EconCSLib.GameTheory.ExtensiveGame.Observed.Realization

/-!
# EconCSLib.GameTheory.ExtensiveGame.Observed.Mixed

Mixed contingent-plan semantics for observed chance EFGs.

A mixed strategy randomizes over one player's complete pure contingent plan.
For a finite player type, a mixed profile is executed by independently
sampling every player's plan once and then running the resulting pure profile
against the game's chance kernels.  Thus this module keeps the classical
distinction between mixed and behavioral randomization explicit:

* mixed randomization occurs once, before play, over complete plans;
* behavioral randomization occurs locally at each information state;
* a mixed profile is a playerwise product, not an arbitrary correlated law on
  pure profiles.

The execution uses the existing behavioral chance semantics after embedding a
sampled pure plan as point-mass local action laws.  Strict observed chance-EFG
isomorphisms transport the complete mixed law and bounded Nash equilibrium on
presentation-designated continuations exactly. A separate `...On` predicate
accepts a possibly conservative lawful `SubgameSystem`; complete bounded
standard mixed SPE requires a `CompleteSubgameSystem`.

## Main definitions

* `ObservedGame.MixedStrategy` and `MixedProfile`.
* `ObservedGame.PureProfile.toBehavioral` and `toMixed`.
* `ObservedGame.MixedProfile.pureProfileLaw`.
* `ObservedChanceGame.mixedStoppedPayoffLawFrom`.
* `ObservedChanceGame.mixedLawGameForm`.
* `ObservedChanceGame.IsMixedNashOnRootsAtFuel`.

## Main results

* `ObservedGame.PureProfile.toMixed_pureProfileLaw`.
* `ObservedChanceGame.toMixed_mixedStoppedPayoffLawFrom`.
* `ObservedChanceGame.Iso.map_mixedStoppedPayoffLawFrom`.
* `ObservedChanceGame.Iso.isMixedNashOnRootsAtFuel_iff`.
-/

namespace FiniteLaw

universe uα

/-- Casting the outcome type of a Dirac law is the Dirac law on the cast
outcome. -/
theorem cast_pure {α β : Type uα}
    (htype : α = β) (value : α) :
    cast (congrArg FiniteLaw htype) (FiniteLaw.pure value) =
      FiniteLaw.pure (cast htype value) := by
  subst β
  rfl

end FiniteLaw

namespace ExtensiveGame.ObservedGame

variable {N U : Type*} (G : ObservedGame N U)

/-- Embed a pure contingent plan as point-mass local action laws. -/
def PureStrategy.toBehavioral {i : N}
    (strategy : G.PureStrategy i) :
    G.BehavioralStrategy i :=
  fun information => FiniteLaw.pure (strategy information)

/-- Embed a complete pure profile as a behavioral profile. -/
def PureProfile.toBehavioral
    (profile : G.PureProfile) :
    G.BehavioralProfile :=
  fun i =>
    ObservedGame.PureStrategy.toBehavioral G (profile i)

/-- A mixed strategy randomizes over one complete pure contingent plan. -/
abbrev MixedStrategy (i : N) :=
  FiniteLaw (G.PureStrategy i)

/-- One independent-mixing component for every player. -/
abbrev MixedProfile :=
  (i : N) → G.MixedStrategy i

/-- Embed a pure strategy as a Dirac mixed strategy. -/
def PureStrategy.toMixed {i : N}
    (strategy : G.PureStrategy i) :
    G.MixedStrategy i :=
  FiniteLaw.pure strategy

/-- Embed a pure profile as a profile of Dirac mixed strategies. -/
def PureProfile.toMixed
    (profile : G.PureProfile) :
    G.MixedProfile :=
  fun i =>
    ObservedGame.PureStrategy.toMixed G (profile i)

namespace MixedProfile

/-- The independent joint law on pure profiles generated by a mixed profile.

This is intentionally a playerwise product.  A directly supplied
`FiniteLaw G.PureProfile` would instead describe a correlated strategy. -/
def pureProfileLaw [Fintype N] [LinearOrder N]
    (profile : G.MixedProfile) :
    FiniteLaw G.PureProfile :=
  FiniteLaw.fintypePi profile

end MixedProfile

/-- Dirac mixing independently selects the declared pure profile with
probability one. -/
theorem PureProfile.toMixed_pureProfileLaw [Fintype N] [LinearOrder N]
    (profile : G.PureProfile) :
    (profile.toMixed G).pureProfileLaw G =
      FiniteLaw.pure profile := by
  change
    FiniteLaw.fintypePi (fun i => FiniteLaw.pure (profile i)) =
      FiniteLaw.pure profile
  exact FiniteLaw.fintypePi_pure profile

end ExtensiveGame.ObservedGame

namespace ExtensiveGame.ObservedChanceGame

universe uV

variable {N U : Type*} (G : ObservedChanceGame N U)

/-- At a player history, the stochastic policy induced by a pure profile's
Dirac behavioral embedding is the point mass at that profile's prescribed
concrete action. -/
theorem pureProfile_toBehavioral_toHistoryPolicy_of_mover
    (profile : G.observed.PureProfile)
    (history :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (hnonterminal :
      ¬ G.observed.base.isTerminal history.1)
    (i : N)
    (hmover :
      G.observed.base.mover history.1 = some i) :
    BehavioralProfile.toHistoryPolicy
        G
        (profile.toBehavioral G.observed)
        history hnonterminal =
      FiniteLaw.pure
        (profile.actionAt G.observed history i hmover
          (G.observed.base.toArena.isDecision_of_not_isTerminal
            history.1 hnonterminal)) := by
  rw [BehavioralProfile.toHistoryPolicy_of_mover
    G (profile.toBehavioral G.observed)
    history hnonterminal i hmover]
  unfold ObservedGame.BehavioralProfile.actionLawAt
    ObservedGame.BehavioralStrategy.actionLawAt
    ControlledObservedGame.BehavioralStrategy.actionLawAt
    ObservedGame.PureProfile.toBehavioral
    ObservedGame.PureStrategy.toBehavioral
    ObservedGame.PureProfile.actionAt
    ObservedGame.PureStrategy.actionAt
  dsimp only
  exact FiniteLaw.pure_map _ _

/-- Bounded optional-payoff law of a mixed contingent-plan profile.

Every player independently samples a complete pure plan once.  Conditional on
that sampled pure profile, play uses point-mass behavioral choices at player
information states and the declared chance kernel at chance histories. -/
def mixedStoppedPayoffLawFrom [Fintype N] [LinearOrder N]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (profile : G.observed.MixedProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    FiniteLaw (Option (N → U)) :=
  (profile.pureProfileLaw G.observed).bind fun pureProfile =>
    G.behavioralStoppedPayoffLawFrom
      (pureProfile.toBehavioral G.observed)
      current fuel

/-- A Dirac mixed profile has exactly the execution law of the corresponding
pure profile embedded behaviorally. -/
theorem toMixed_mixedStoppedPayoffLawFrom [Fintype N] [LinearOrder N]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (profile : G.observed.PureProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    G.mixedStoppedPayoffLawFrom
        (profile.toMixed G.observed) current fuel =
      G.behavioralStoppedPayoffLawFrom
        (profile.toBehavioral G.observed) current fuel := by
  unfold mixedStoppedPayoffLawFrom
  rw [ObservedGame.PureProfile.toMixed_pureProfileLaw,
    FiniteLaw.pure_bind]

/-- The bounded mixed contingent-plan semantics as a law-valued game form. -/
def mixedLawGameForm [Fintype N] [LinearOrder N]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    LawGameForm N where
  Strategy := G.observed.MixedStrategy
  Outcome := Option (N → U)
  outcomeLaw profile :=
    G.mixedStoppedPayoffLawFrom profile current fuel

/-- Bounded mixed-strategy Nash equilibrium on presentation-designated
continuations.

The same ex-ante mixed contingent-plan profile must be Nash in the bounded
continuation at every declared root. -/
def IsMixedNashOnRootsAtFuel [Fintype N] [LinearOrder N]
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (roots : G.observed.RootPresentation)
    (utility : FiniteLaw (Option (N → U)) → N → V)
    (profile : G.observed.MixedProfile)
    (fuel : ℕ) : Prop :=
  ∀ current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init,
    roots.IsRoot current →
      (G.mixedLawGameForm current fuel).IsNash
        utility profile

/-- Bounded mixed-strategy subgame perfection on an explicit, possibly
conservative, lawful subgame system. -/
def IsMixedSubgamePerfectOnAtFuel [Fintype N] [LinearOrder N]
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (system : G.observed.SubgameSystem)
    (utility : FiniteLaw (Option (N → U)) → N → V)
    (profile : G.observed.MixedProfile)
    (fuel : ℕ) : Prop :=
  ∀ current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init,
    system.IsRoot current →
      (G.mixedLawGameForm current fuel).IsNash
        utility profile

/-- Bounded standard mixed-strategy SPE on every structurally lawful subgame
root. -/
def IsMixedStandardSubgamePerfectAtFuel [Fintype N] [LinearOrder N]
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (system : G.observed.CompleteSubgameSystem)
    (utility : FiniteLaw (Option (N → U)) → N → V)
    (profile : G.observed.MixedProfile)
    (fuel : ℕ) : Prop :=
  G.IsMixedSubgamePerfectOnAtFuel system.toSubgameSystem
    utility profile fuel

end ExtensiveGame.ObservedChanceGame

namespace ExtensiveGame.ObservedGame.Iso

variable {N U : Type*}
variable {G H : ObservedGame N U}

/-- A strict observed-EFG isomorphism transports mixed contingent plans by
pushforward along its pure-strategy equivalence. -/
def mixedStrategyEquiv (e : G.Iso H) (i : N) :
    G.MixedStrategy i ≃ H.MixedStrategy i :=
  FiniteLaw.mapEquiv (e.strategyEquiv i)

/-- Map a mixed profile player by player along a strict isomorphism. -/
def mapMixedProfile (e : G.Iso H)
    (profile : G.MixedProfile) :
    H.MixedProfile :=
  fun i => e.mixedStrategyEquiv i (profile i)

/-- Map a target mixed profile back through a strict isomorphism. -/
def unmapMixedProfile (e : G.Iso H)
    (profile : H.MixedProfile) :
    G.MixedProfile :=
  fun i => (e.mixedStrategyEquiv i).symm (profile i)

/-- Strict observed-EFG isomorphisms induce an equivalence of mixed
profiles. -/
def mixedProfileEquiv (e : G.Iso H) :
    G.MixedProfile ≃ H.MixedProfile where
  toFun := e.mapMixedProfile
  invFun := e.unmapMixedProfile
  left_inv := by
    intro profile
    funext i
    exact
      (e.mixedStrategyEquiv i).symm_apply_apply
        (profile i)
  right_inv := by
    intro profile
    funext i
    exact
      (e.mixedStrategyEquiv i).apply_symm_apply
        (profile i)

@[simp]
theorem mapMixedProfile_apply (e : G.Iso H)
    (profile : G.MixedProfile) (i : N) :
    e.mapMixedProfile profile i =
      (profile i).map (e.strategyEquiv i) :=
  rfl

@[simp]
theorem mapMixedProfile_unmapMixedProfile (e : G.Iso H)
    (profile : H.MixedProfile) :
    e.mapMixedProfile (e.unmapMixedProfile profile) =
      profile :=
  e.mixedProfileEquiv.apply_symm_apply profile

@[simp]
theorem unmapMixedProfile_mapMixedProfile (e : G.Iso H)
    (profile : G.MixedProfile) :
    e.unmapMixedProfile (e.mapMixedProfile profile) =
      profile :=
  e.mixedProfileEquiv.symm_apply_apply profile

/-- Pure-to-behavioral embedding commutes with strict structural
isomorphisms. -/
theorem mapProfile_toBehavioral (e : G.Iso H)
    (profile : G.PureProfile) :
    (e.mapProfile profile).toBehavioral H =
      e.mapBehavioralProfile
        (profile.toBehavioral G) := by
  funext i targetInformation
  let sourceInformation :=
    (e.representedInfoEquiv i).symm targetInformation
  have hinformation :
      e.representedInfoEquiv i sourceInformation =
        targetInformation :=
    (e.representedInfoEquiv i).apply_symm_apply
      targetInformation
  have hpure :=
    Equiv.piCongr_apply_of_eq
      (W := fun information : G.RepresentedInfo i =>
        G.InfoAction i information.1)
      (Z := fun information : H.RepresentedInfo i =>
        H.InfoAction i information.1)
      (e.representedInfoEquiv i)
      (e.representedInfoActionEquiv i)
      (profile i)
      sourceInformation targetInformation
      hinformation
  have hbehavior :=
    Equiv.piCongr_apply_of_eq
      (W := fun information : G.RepresentedInfo i =>
        FiniteLaw (G.InfoAction i information.1))
      (Z := fun information : H.RepresentedInfo i =>
        FiniteLaw (H.InfoAction i information.1))
      (e.representedInfoEquiv i)
      (fun information =>
        FiniteLaw.mapEquiv
          (e.representedInfoActionEquiv i information))
      ((profile.toBehavioral G) i)
      sourceInformation targetInformation
      hinformation
  unfold ObservedGame.PureProfile.toBehavioral
    ObservedGame.PureStrategy.toBehavioral
  change
    (FiniteLaw.pure
        (e.strategyEquiv i (profile i) targetInformation) :
      FiniteLaw (H.InfoAction i targetInformation.1)) =
      e.behavioralStrategyEquiv i
        ((profile.toBehavioral G) i)
        targetInformation
  change
    e.strategyEquiv i (profile i) targetInformation = _ at hpure
  rw [hpure]
  unfold behavioralStrategyEquiv
  refine Eq.trans ?_ hbehavior.symm
  change
    FiniteLaw.pure
        (cast
          (congrArg
            (fun information : H.RepresentedInfo i =>
              H.InfoAction i information.1) hinformation)
          (e.representedInfoActionEquiv i sourceInformation
            (profile i sourceInformation))) =
      cast
        (congrArg
          (fun information : H.RepresentedInfo i =>
            FiniteLaw (H.InfoAction i information.1))
          hinformation)
        ((FiniteLaw.pure
          (profile i sourceInformation)).map
            (e.representedInfoActionEquiv i sourceInformation))
  symm
  calc
    cast
        (congrArg
          (fun information : H.RepresentedInfo i =>
            FiniteLaw (H.InfoAction i information.1))
          hinformation)
        ((FiniteLaw.pure
          (profile i sourceInformation)).map
            (e.representedInfoActionEquiv i sourceInformation)) =
      cast
        (congrArg
          (fun information : H.RepresentedInfo i =>
            FiniteLaw (H.InfoAction i information.1))
          hinformation)
        (FiniteLaw.pure
          (e.representedInfoActionEquiv i sourceInformation
            (profile i sourceInformation))) := by
      exact congrArg
        (cast
          (congrArg
            (fun information : H.RepresentedInfo i =>
              FiniteLaw (H.InfoAction i information.1))
            hinformation))
        (FiniteLaw.pure_map
          (f := e.representedInfoActionEquiv i sourceInformation)
          (profile i sourceInformation))
    _ = cast
        (congrArg FiniteLaw
          (congrArg
            (fun information : H.RepresentedInfo i =>
              H.InfoAction i information.1) hinformation))
        (FiniteLaw.pure
          (e.representedInfoActionEquiv i sourceInformation
            (profile i sourceInformation))) := by
      congr
    _ = FiniteLaw.pure
        (cast
          (congrArg
            (fun information : H.RepresentedInfo i =>
              H.InfoAction i information.1) hinformation)
          (e.representedInfoActionEquiv i sourceInformation
            (profile i sourceInformation))) :=
      FiniteLaw.cast_pure
        (congrArg
          (fun information : H.RepresentedInfo i =>
            H.InfoAction i information.1) hinformation)
        (e.representedInfoActionEquiv i sourceInformation
          (profile i sourceInformation))

/-- Independent sampling of player plans commutes with strict profile
transport. -/
theorem map_pureProfileLaw [Fintype N] [LinearOrder N]
    (e : G.Iso H) (profile : G.MixedProfile) :
    (profile.pureProfileLaw G).map e.mapProfile =
      (e.mapMixedProfile profile).pureProfileLaw H := by
  change
    (FiniteLaw.fintypePi profile).map
        (fun pureProfile i =>
          e.strategyEquiv i (pureProfile i)) =
      FiniteLaw.fintypePi
        (fun i =>
          (profile i).map (e.strategyEquiv i))
  exact
    FiniteLaw.fintypePi_map profile
      (fun i => e.strategyEquiv i)

end ExtensiveGame.ObservedGame.Iso

namespace ExtensiveGame.ObservedChanceGame.Iso

universe uV

variable {N U : Type*}
variable {G H : ObservedChanceGame N U}

/-- Strict observed chance-EFG isomorphisms preserve the complete bounded
mixed contingent-plan payoff law. -/
theorem map_mixedStoppedPayoffLawFrom [Fintype N] [LinearOrder N]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (profile : G.observed.MixedProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    H.mixedStoppedPayoffLawFrom
        (e.observedIso.mapMixedProfile profile)
        (e.observedIso.historyIso.stateEquiv current)
        fuel =
      G.mixedStoppedPayoffLawFrom
        profile current fuel := by
  unfold mixedStoppedPayoffLawFrom
  rw [← e.observedIso.map_pureProfileLaw profile,
    FiniteLaw.bind_map]
  congr 1
  funext pureProfile
  change
    H.behavioralStoppedPayoffLawFrom
        ((e.observedIso.mapProfile
          pureProfile).toBehavioral H.observed)
        (e.observedIso.historyIso.stateEquiv current)
        fuel =
      G.behavioralStoppedPayoffLawFrom
        (pureProfile.toBehavioral G.observed)
        current fuel
  rw [e.observedIso.mapProfile_toBehavioral]
  exact
    e.map_behavioralStoppedPayoffLawFrom
      (pureProfile.toBehavioral G.observed)
      current fuel

/-- A strict observed chance-EFG isomorphism induces an isomorphism of
bounded mixed law semantics at corresponding histories. -/
def mixedLawGameFormIso [Fintype N] [LinearOrder N]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.mixedLawGameForm current fuel).Iso
      (H.mixedLawGameForm
        (e.observedIso.historyIso.stateEquiv current)
        fuel) where
  strategyEquiv :=
    e.observedIso.mixedStrategyEquiv
  outcomeEquiv := Equiv.refl _
  map_outcomeLaw := by
    intro profile
    unfold LawGameForm.RealizesVia
    change
      (G.mixedStoppedPayoffLawFrom
          profile current fuel).map id =
        H.mixedStoppedPayoffLawFrom
          (e.observedIso.mapMixedProfile profile)
          (e.observedIso.historyIso.stateEquiv current)
          fuel
    rw [FiniteLaw.map_id]
    exact
      (e.map_mixedStoppedPayoffLawFrom
        profile current fuel).symm

/-- Strict isomorphisms preserve mixed Nash equilibrium at corresponding
bounded continuations. -/
theorem mixedLawIsNash_iff [Fintype N] [LinearOrder N]
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (utility : FiniteLaw (Option (N → U)) → N → V)
    (profile : G.observed.MixedProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.mixedLawGameForm current fuel).IsNash
        utility profile ↔
      (H.mixedLawGameForm
        (e.observedIso.historyIso.stateEquiv current)
        fuel).IsNash utility
          (e.observedIso.mapMixedProfile profile) := by
  apply
    (e.mixedLawGameFormIso
      current fuel).isNash_iff
  intro law i
  change utility (law.map id) i = utility law i
  rw [FiniteLaw.map_id]

/-- Strict observed chance-EFG isomorphisms preserve bounded mixed Nash on
explicitly corresponding root presentations in both directions. -/
theorem isMixedNashOnRootsAtFuel_iff [Fintype N] [LinearOrder N]
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (sourceRoots : G.observed.RootPresentation)
    (targetRoots : H.observed.RootPresentation)
    (hroots :
      e.observedIso.PreservesRootPresentations
        sourceRoots targetRoots)
    (utility : FiniteLaw (Option (N → U)) → N → V)
    (profile : G.observed.MixedProfile)
    (fuel : ℕ) :
    G.IsMixedNashOnRootsAtFuel sourceRoots utility profile fuel ↔
      H.IsMixedNashOnRootsAtFuel targetRoots utility
        (e.observedIso.mapMixedProfile profile) fuel := by
  constructor
  · intro hspe targetRoot htargetRoot
    let sourceRoot :=
      e.observedIso.historyIso.stateEquiv.symm
        targetRoot
    have hmap :
        e.observedIso.historyIso.stateEquiv sourceRoot =
          targetRoot :=
      e.observedIso.historyIso.stateEquiv.apply_symm_apply
        targetRoot
    have hsourceRoot : sourceRoots.IsRoot sourceRoot := by
      apply (hroots sourceRoot).mpr
      simpa [hmap] using htargetRoot
    have hmapped :=
      (e.mixedLawIsNash_iff
        utility profile sourceRoot fuel).mp
        (hspe sourceRoot hsourceRoot)
    change
      (H.mixedLawGameForm
        (e.observedIso.historyIso.stateEquiv sourceRoot)
        fuel).IsNash utility
          (e.observedIso.mapMixedProfile profile) at hmapped
    rw [hmap] at hmapped
    exact hmapped
  · intro hspe sourceRoot hsourceRoot
    have htargetRoot :
        targetRoots.IsRoot
          (e.observedIso.historyIso.stateEquiv
            sourceRoot) :=
      (hroots sourceRoot).mp hsourceRoot
    exact
      (e.mixedLawIsNash_iff
        utility profile sourceRoot fuel).mpr
        (hspe
          (e.observedIso.historyIso.stateEquiv
            sourceRoot)
          htargetRoot)

end ExtensiveGame.ObservedChanceGame.Iso
