/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.GameTheory.GameForm.Law
import EconCSLib.GameTheory.ExtensiveGame.Observed.BehaviorRefinement.Execution

/-!
# EconCSLib.GameTheory.ExtensiveGame.Observed.Realization

Law-valued semantics and realization transfer for observed chance EFGs.

The existing bounded behavioral continuation form uses
`GameForm.Outcome := PMF (Option payoff)`.  This module exposes the same
semantics through `LawGameForm`, where the optional terminal payoff is the
underlying outcome and its `PMF` is generated by the evaluator.

This factoring makes exact realization explicit:

* strict observed chance-EFG isomorphisms induce `LawGameForm.Iso`s;
* chance-aware information refinements induce `LawGameForm.Hom`s;
* their defining laws are instances of the representation-neutral
  `LawGameForm.RealizesVia` relation.

The old deterministic `GameForm` view is definitionally recovered, so the new
layer reorganizes existing semantics rather than introducing a competing
evaluation.

## Main definitions

* `ObservedChanceGame.behavioralLawGameForm`.
* `ObservedChanceGame.Iso.behavioralLawGameFormIso`.
* `ObservedChanceGame.InformationRefinement.behavioralLawGameFormHom`.

## Main results

* `behavioralLawGameForm_toGameForm`.
* `Iso.behavioralProfile_realizesVia`.
* `InformationRefinement.behavioralProfile_realizesVia`.
* `Iso.behavioralLawIsNash_iff`.
* `InformationRefinement.behavioralLawIsNash_of_map`.
-/

namespace ExtensiveGame.ObservedChanceGame

universe uV

variable {N U : Type*}

/-- The bounded behavioral continuation semantics as a law-valued game form.

The underlying outcome distinguishes terminal payoff vectors from
fuel-exhausted prefixes using `Option`; the evaluator retains the complete
normalized law. -/
noncomputable def behavioralLawGameForm
    (G : ObservedChanceGame N U)
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    LawGameForm N where
  Strategy := G.observed.BehavioralStrategy
  Outcome := Option (N → U)
  outcomeLaw profile :=
    G.behavioralStoppedPayoffLawFrom
      profile current fuel

/-- Forgetting that the evaluator is law-valued recovers the existing bounded
behavioral continuation `GameForm` definitionally. -/
theorem behavioralLawGameForm_toGameForm
    (G : ObservedChanceGame N U)
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.behavioralLawGameForm current fuel).toGameForm =
      G.behavioralContinuationGameForm current fuel :=
  rfl

namespace Iso

variable {G H : ObservedChanceGame N U}

/-- A strict observed chance-EFG isomorphism induces a strict isomorphism of
bounded behavioral law semantics at corresponding histories. -/
noncomputable def behavioralLawGameFormIso
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.behavioralLawGameForm current fuel).Iso
      (H.behavioralLawGameForm
        (e.observedIso.historyIso.stateEquiv current)
        fuel) where
  strategyEquiv :=
    e.observedIso.behavioralStrategyEquiv
  outcomeEquiv := Equiv.refl _
  map_outcomeLaw := by
    intro profile
    unfold LawGameForm.RealizesVia
    change
      (G.behavioralStoppedPayoffLawFrom
          profile current fuel).map id =
        H.behavioralStoppedPayoffLawFrom
          (e.observedIso.mapBehavioralProfile profile)
          (e.observedIso.historyIso.stateEquiv current)
          fuel
    rw [PMF.map_id]
    exact
      (e.map_behavioralStoppedPayoffLawFrom
        profile current fuel).symm

/-- A mapped behavioral profile exactly realizes its source at every bounded
continuation under a strict observed chance-EFG isomorphism. -/
theorem behavioralProfile_realizesVia
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (profile : G.observed.BehavioralProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.behavioralLawGameForm current fuel).RealizesVia
      (H.behavioralLawGameForm
        (e.observedIso.historyIso.stateEquiv current)
        fuel)
      (e.behavioralLawGameFormIso
        current fuel).outcomeEquiv
      profile
      ((e.behavioralLawGameFormIso
        current fuel).mapProfile profile) :=
  (e.behavioralLawGameFormIso
    current fuel).toHom.mapProfile_realizesVia profile

/-- Strict observed chance-EFG isomorphisms preserve Nash equilibrium stated
directly over bounded behavioral outcome laws. -/
theorem behavioralLawIsNash_iff
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (e : G.Iso H)
    (utility :
      PMF (Option (N → U)) → N → V)
    (profile : G.observed.BehavioralProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.behavioralLawGameForm
        current fuel).IsNash utility profile ↔
      (H.behavioralLawGameForm
        (e.observedIso.historyIso.stateEquiv current)
        fuel).IsNash utility
          ((e.behavioralLawGameFormIso
            current fuel).mapProfile profile) := by
  apply
    (e.behavioralLawGameFormIso
      current fuel).isNash_iff
  intro law i
  change utility (law.map id) i = utility law i
  rw [PMF.map_id]

end Iso

namespace InformationRefinement

variable {G H : ObservedChanceGame N U}

/-- A chance-aware information refinement is a law-valued morphism of bounded
behavioral continuations. -/
noncomputable def behavioralLawGameFormHom
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (r : G.InformationRefinement H)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.behavioralLawGameForm current fuel).Hom
      (H.behavioralLawGameForm
        (r.observedRefinement.historyIso.stateEquiv
          current)
        fuel) where
  strategyMap :=
    r.observedRefinement.mapBehavioralStrategy
  outcomeMap := id
  map_outcomeLaw := by
    intro profile
    unfold LawGameForm.RealizesVia
    change
      (G.behavioralStoppedPayoffLawFrom
          profile current fuel).map id =
        H.behavioralStoppedPayoffLawFrom
          (r.observedRefinement.mapBehavioralProfile
            profile)
          (r.observedRefinement.historyIso.stateEquiv
            current)
          fuel
    rw [PMF.map_id]
    exact
      (r.map_behavioralStoppedPayoffLawFrom
        profile current fuel).symm

/-- A lifted behavioral profile exactly realizes its coarse source through an
information refinement. -/
theorem behavioralProfile_realizesVia
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (r : G.InformationRefinement H)
    (profile : G.observed.BehavioralProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ) :
    (G.behavioralLawGameForm current fuel).RealizesVia
      (H.behavioralLawGameForm
        (r.observedRefinement.historyIso.stateEquiv
          current)
        fuel)
      (r.behavioralLawGameFormHom
        current fuel).outcomeMap
      profile
      ((r.behavioralLawGameFormHom
        current fuel).mapProfile profile) :=
  (r.behavioralLawGameFormHom
    current fuel).mapProfile_realizesVia profile

/-- Behavioral-strategy surjectivity of an information refinement gives
strategy surjectivity of its law-valued morphism. -/
theorem behavioralLawGameFormHom_strategySurjective
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (r : G.InformationRefinement H)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ)
    (hsurjective :
      r.observedRefinement.BehavioralStrategySurjective) :
    (r.behavioralLawGameFormHom
      current fuel).StrategySurjective :=
  hsurjective

/-- Nash equilibrium of a lifted fine behavioral law reflects to its coarse
source through any chance-aware information refinement. -/
theorem behavioralLawIsNash_of_map
    [DecidableEq N] [Preorder V]
    [(state : G.observed.base.State) →
      Decidable (G.observed.base.isTerminal state)]
    [(state : H.observed.base.State) →
      Decidable (H.observed.base.isTerminal state)]
    (r : G.InformationRefinement H)
    (utility :
      PMF (Option (N → U)) → N → V)
    (profile : G.observed.BehavioralProfile)
    (current :
      G.observed.base.toArena.HistoryFrom
        G.observed.base.init)
    (fuel : ℕ)
    (hNash :
      (H.behavioralLawGameForm
        (r.observedRefinement.historyIso.stateEquiv
          current)
        fuel).IsNash utility
          ((r.behavioralLawGameFormHom
            current fuel).mapProfile profile)) :
    (G.behavioralLawGameForm
      current fuel).IsNash utility profile := by
  apply hNash.comap
    (r.behavioralLawGameFormHom
      current fuel)
  intro law i
  change utility (law.map id) i = utility law i
  rw [PMF.map_id]

end InformationRefinement

end ExtensiveGame.ObservedChanceGame
