/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.Math.Probability.Effective.Enclosure

/-!
# Effective probability queries over coded events

This module defines a measure-free executable language for probability and
expectation queries.  An event type is syntax chosen by a concrete model.  A
`SimpleObservable` is a finite rational linear combination of indicators of
those event codes, and an `EffectiveLaw` answers each event query with a
certified rational enclosure oracle.

Pushforwards are represented by executable preimage compilers.  Kernels use
their expectation-transformer form: `pullEvent` turns a target event into a
source simple observable.  This choice makes law bind and kernel composition
ordinary structural recursion and function composition.  It also records the
essential closure condition that an event-only probability oracle would omit.

The module deliberately contains no `Measure`, Mathlib `Kernel`, set-valued
event interpretation, or real integral.  Those denotations and correctness
theorems live in `Effective.Semantics`.
-/

namespace EffectiveProbability

universe uEvent vEvent wEvent

/-- Finite rational observable syntax generated by constants and coded event
indicators.  Overlap between coded events is allowed: addition denotes a sum
of functions, not a disjoint union. -/
inductive SimpleObservable (EventCode : Type uEvent) where
  | const (value : ℚ)
  | indicator (event : EventCode)
  | add (left right : SimpleObservable EventCode)
  | scale (coefficient : ℚ) (observable : SimpleObservable EventCode)
deriving Repr

namespace SimpleObservable

/-- Subtraction in the finite observable language. -/
def sub {EventCode : Type uEvent}
    (left right : SimpleObservable EventCode) :
    SimpleObservable EventCode :=
  .add left (.scale (-1) right)

/-- Transport event codes through a compiler, preserving the observable's
rational expression tree. -/
def mapEvents {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) :
    SimpleObservable SourceCode → SimpleObservable TargetCode
  | .const value => .const value
  | .indicator event => .indicator (compile event)
  | .add left right => .add (mapEvents compile left) (mapEvents compile right)
  | .scale coefficient observable =>
      .scale coefficient (mapEvents compile observable)

@[simp]
theorem mapEvents_const {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) (value : ℚ) :
    mapEvents compile (.const value) = .const value :=
  rfl

@[simp]
theorem mapEvents_indicator
    {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) (event : SourceCode) :
    mapEvents compile (.indicator event) = .indicator (compile event) :=
  rfl

@[simp]
theorem mapEvents_add {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode)
    (left right : SimpleObservable SourceCode) :
    mapEvents compile (.add left right) =
      .add (mapEvents compile left) (mapEvents compile right) :=
  rfl

@[simp]
theorem mapEvents_scale
    {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) (coefficient : ℚ)
    (observable : SimpleObservable SourceCode) :
    mapEvents compile (.scale coefficient observable) =
      .scale coefficient (mapEvents compile observable) :=
  rfl

@[simp]
theorem mapEvents_id {EventCode : Type uEvent}
    (observable : SimpleObservable EventCode) :
    mapEvents id observable = observable := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [mapEvents, ihLeft, ihRight]
  | scale coefficient observable ih => simp [mapEvents, ih]

theorem mapEvents_comp
    {FirstCode : Type uEvent} {SecondCode : Type vEvent}
    {ThirdCode : Type wEvent}
    (second : SecondCode → ThirdCode) (first : FirstCode → SecondCode)
    (observable : SimpleObservable FirstCode) :
    mapEvents second (mapEvents first observable) =
      mapEvents (second ∘ first) observable := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [mapEvents, ihLeft, ihRight]
  | scale coefficient observable ih => simp [mapEvents, ih]

end SimpleObservable

/-- An effective probability law queried only through a chosen event-code
language.  Each query returns an arbitrary-precision rational enclosure oracle.
-/
structure EffectiveLaw (EventCode : Type uEvent) where
  /-- Arbitrary-precision mass oracle for one coded event. -/
  mass : EventCode → RatOracle

namespace EffectiveLaw

variable {EventCode : Type uEvent}

/-- Evaluate a finite rational observable by structural recursion from event
mass queries.  This is the executable integration algorithm for the simple
observable language. -/
def expect (law : EffectiveLaw EventCode) :
    SimpleObservable EventCode → RatOracle
  | .const value => RatOracle.exact value
  | .indicator event => law.mass event
  | .add left right => (law.expect left).add (law.expect right)
  | .scale coefficient observable =>
      RatOracle.scale coefficient (law.expect observable)

@[simp]
theorem expect_const (law : EffectiveLaw EventCode) (value : ℚ) :
    law.expect (.const value) = RatOracle.exact value :=
  rfl

@[simp]
theorem expect_indicator (law : EffectiveLaw EventCode) (event : EventCode) :
    law.expect (.indicator event) = law.mass event :=
  rfl

@[simp]
theorem expect_add (law : EffectiveLaw EventCode)
    (left right : SimpleObservable EventCode) :
    law.expect (.add left right) = (law.expect left).add (law.expect right) :=
  rfl

@[simp]
theorem expect_scale (law : EffectiveLaw EventCode) (coefficient : ℚ)
    (observable : SimpleObservable EventCode) :
    law.expect (.scale coefficient observable) =
      RatOracle.scale coefficient (law.expect observable) :=
  rfl

@[ext]
theorem ext {left right : EffectiveLaw EventCode}
    (hmass : ∀ event, left.mass event = right.mass event) : left = right := by
  cases left
  cases right
  congr
  funext event
  exact hmass event

end EffectiveLaw

end EffectiveProbability
