/-
Copyright (c) 2026 EconCSLib contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/

import EconCSLib.Math.Probability.Effective.Enclosure

/-!
# Effective probability queries over coded events

This module defines a measure-free executable language for probability and
expectation queries.  An event type is syntax chosen by a concrete model.  A
`SimpleObservable` is a finite rational linear combination of indicators of
those event codes, and an `EffectiveLaw` answers each event query with a
certified rational enclosure oracle.

Pushforwards are represented by executable preimage compilers.  Kernels use
their expectation-transformer form: `pullEvent` turns a target event into a
source simple observable.  This choice makes law bind and kernel composition
ordinary structural recursion and function composition.  It also records the
essential closure condition that an event-only probability oracle would omit.

The module deliberately contains no `Measure`, Mathlib `Kernel`, set-valued
event interpretation, or real integral.  Those denotations and correctness
theorems live in `Effective.Semantics`.
-/

namespace EffectiveProbability

universe uEvent vEvent wEvent

/-- Finite rational observable syntax generated by constants and coded event
indicators.  Overlap between coded events is allowed: addition denotes a sum
of functions, not a disjoint union. -/
inductive SimpleObservable (EventCode : Type uEvent) where
  | const (value : ℚ)
  | indicator (event : EventCode)
  | add (left right : SimpleObservable EventCode)
  | scale (coefficient : ℚ) (observable : SimpleObservable EventCode)
deriving Repr

namespace SimpleObservable

/-- Subtraction in the finite observable language. -/
def sub {EventCode : Type uEvent}
    (left right : SimpleObservable EventCode) :
    SimpleObservable EventCode :=
  .add left (.scale (-1) right)

/-- Transport event codes through a compiler, preserving the observable's
rational expression tree. -/
def mapEvents {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) :
    SimpleObservable SourceCode → SimpleObservable TargetCode
  | .const value => .const value
  | .indicator event => .indicator (compile event)
  | .add left right => .add (mapEvents compile left) (mapEvents compile right)
  | .scale coefficient observable =>
      .scale coefficient (mapEvents compile observable)

@[simp]
theorem mapEvents_const {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) (value : ℚ) :
    mapEvents compile (.const value) = .const value :=
  rfl

@[simp]
theorem mapEvents_indicator
    {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) (event : SourceCode) :
    mapEvents compile (.indicator event) = .indicator (compile event) :=
  rfl

@[simp]
theorem mapEvents_add {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode)
    (left right : SimpleObservable SourceCode) :
    mapEvents compile (.add left right) =
      .add (mapEvents compile left) (mapEvents compile right) :=
  rfl

@[simp]
theorem mapEvents_scale
    {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (compile : SourceCode → TargetCode) (coefficient : ℚ)
    (observable : SimpleObservable SourceCode) :
    mapEvents compile (.scale coefficient observable) =
      .scale coefficient (mapEvents compile observable) :=
  rfl

@[simp]
theorem mapEvents_id {EventCode : Type uEvent}
    (observable : SimpleObservable EventCode) :
    mapEvents id observable = observable := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [mapEvents, ihLeft, ihRight]
  | scale coefficient observable ih => simp [mapEvents, ih]

theorem mapEvents_comp
    {FirstCode : Type uEvent} {SecondCode : Type vEvent}
    {ThirdCode : Type wEvent}
    (second : SecondCode → ThirdCode) (first : FirstCode → SecondCode)
    (observable : SimpleObservable FirstCode) :
    mapEvents second (mapEvents first observable) =
      mapEvents (second ∘ first) observable := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [mapEvents, ihLeft, ihRight]
  | scale coefficient observable ih => simp [mapEvents, ih]

end SimpleObservable

/-- An effective probability law queried only through a chosen event-code
language.  Each query returns an arbitrary-precision rational enclosure oracle.
-/
structure EffectiveLaw (EventCode : Type uEvent) where
  /-- Arbitrary-precision mass oracle for one coded event. -/
  mass : EventCode → RatOracle

namespace EffectiveLaw

variable {EventCode : Type uEvent}

/-- Evaluate a finite rational observable by structural recursion from event
mass queries.  This is the executable integration algorithm for the simple
observable language. -/
def expect (law : EffectiveLaw EventCode) :
    SimpleObservable EventCode → RatOracle
  | .const value => RatOracle.exact value
  | .indicator event => law.mass event
  | .add left right => (law.expect left).add (law.expect right)
  | .scale coefficient observable =>
      RatOracle.scale coefficient (law.expect observable)

@[simp]
theorem expect_const (law : EffectiveLaw EventCode) (value : ℚ) :
    law.expect (.const value) = RatOracle.exact value :=
  rfl

@[simp]
theorem expect_indicator (law : EffectiveLaw EventCode) (event : EventCode) :
    law.expect (.indicator event) = law.mass event :=
  rfl

@[simp]
theorem expect_add (law : EffectiveLaw EventCode)
    (left right : SimpleObservable EventCode) :
    law.expect (.add left right) = (law.expect left).add (law.expect right) :=
  rfl

@[simp]
theorem expect_scale (law : EffectiveLaw EventCode) (coefficient : ℚ)
    (observable : SimpleObservable EventCode) :
    law.expect (.scale coefficient observable) =
      RatOracle.scale coefficient (law.expect observable) :=
  rfl

@[ext]
theorem ext {left right : EffectiveLaw EventCode}
    (hmass : ∀ event, left.mass event = right.mass event) : left = right := by
  cases left
  cases right
  congr
  funext event
  exact hmass event

end EffectiveLaw

/-- Exact rational event masses, useful when a symbolic non-atomic model has
closed-form answers for its selected event language. -/
structure ExactLaw (EventCode : Type uEvent) where
  /-- Exact rational mass of one coded event. -/
  mass : EventCode → ℚ

namespace ExactLaw

variable {EventCode : Type uEvent}

/-- Regard an exact rational law as an arbitrary-precision effective law. -/
def toEffective (law : ExactLaw EventCode) : EffectiveLaw EventCode where
  mass event := RatOracle.exact (law.mass event)

/-- Exact expectation of a finite rational observable. -/
def expectRat (law : ExactLaw EventCode) :
    SimpleObservable EventCode → ℚ
  | .const value => value
  | .indicator event => law.mass event
  | .add left right => law.expectRat left + law.expectRat right
  | .scale coefficient observable =>
      coefficient * law.expectRat observable

@[simp]
theorem expectRat_const (law : ExactLaw EventCode) (value : ℚ) :
    law.expectRat (.const value) = value :=
  rfl

@[simp]
theorem expectRat_indicator (law : ExactLaw EventCode) (event : EventCode) :
    law.expectRat (.indicator event) = law.mass event :=
  rfl

@[simp]
theorem expectRat_add (law : ExactLaw EventCode)
    (left right : SimpleObservable EventCode) :
    law.expectRat (.add left right) =
      law.expectRat left + law.expectRat right :=
  rfl

@[simp]
theorem expectRat_scale (law : ExactLaw EventCode) (coefficient : ℚ)
    (observable : SimpleObservable EventCode) :
    law.expectRat (.scale coefficient observable) =
      coefficient * law.expectRat observable :=
  rfl

/-- The effective oracle obtained from an exact rational law encloses the
law's structurally computed exact expectation. -/
theorem toEffective_expect_encloses (law : ExactLaw EventCode)
    (observable : SimpleObservable EventCode) :
    (law.toEffective.expect observable).Encloses
      (law.expectRat observable) := by
  induction observable with
  | const value => exact RatOracle.exact_encloses value
  | indicator event => exact RatOracle.exact_encloses (law.mass event)
  | add left right ihLeft ihRight => exact ihLeft.add ihRight
  | scale coefficient observable ih => exact ih.scale coefficient

end ExactLaw

/-- Executable preimage compilation for a measurable-map interpretation. -/
structure EffectiveMap (SourceCode : Type uEvent) (TargetCode : Type vEvent) where
  /-- Compile a target event into its source preimage code. -/
  preimage : TargetCode → SourceCode

namespace EffectiveLaw

/-- Effective pushforward: answer a target event by compiling its preimage and
querying the source law. -/
def map {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (law : EffectiveLaw SourceCode)
    (mapping : EffectiveMap SourceCode TargetCode) :
    EffectiveLaw TargetCode where
  mass event := law.mass (mapping.preimage event)

@[simp]
theorem map_mass {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (law : EffectiveLaw SourceCode)
    (mapping : EffectiveMap SourceCode TargetCode) (event : TargetCode) :
    (law.map mapping).mass event = law.mass (mapping.preimage event) :=
  rfl

end EffectiveLaw

/-- Effective Markov operator in expectation-transformer form.  Pulling an
event indicator back through the kernel must remain in the selected finite
source-observable language. -/
structure EffectiveKernel (SourceCode : Type uEvent) (TargetCode : Type vEvent) where
  /-- Pull a target-event indicator back to a source simple observable. -/
  pullEvent : TargetCode → SimpleObservable SourceCode

namespace EffectiveKernel

variable {SourceCode : Type uEvent} {TargetCode : Type vEvent}

/-- Extend event pullback structurally to every finite rational observable. -/
def pullObservable (kernel : EffectiveKernel SourceCode TargetCode) :
    SimpleObservable TargetCode → SimpleObservable SourceCode
  | .const value => .const value
  | .indicator event => kernel.pullEvent event
  | .add left right =>
      .add (kernel.pullObservable left) (kernel.pullObservable right)
  | .scale coefficient observable =>
      .scale coefficient (kernel.pullObservable observable)

@[simp]
theorem pullObservable_const
    (kernel : EffectiveKernel SourceCode TargetCode) (value : ℚ) :
    kernel.pullObservable (.const value) = .const value :=
  rfl

@[simp]
theorem pullObservable_indicator
    (kernel : EffectiveKernel SourceCode TargetCode) (event : TargetCode) :
    kernel.pullObservable (.indicator event) = kernel.pullEvent event :=
  rfl

@[simp]
theorem pullObservable_add
    (kernel : EffectiveKernel SourceCode TargetCode)
    (left right : SimpleObservable TargetCode) :
    kernel.pullObservable (.add left right) =
      .add (kernel.pullObservable left) (kernel.pullObservable right) :=
  rfl

@[simp]
theorem pullObservable_scale
    (kernel : EffectiveKernel SourceCode TargetCode) (coefficient : ℚ)
    (observable : SimpleObservable TargetCode) :
    kernel.pullObservable (.scale coefficient observable) =
      .scale coefficient (kernel.pullObservable observable) :=
  rfl

/-- Identity Markov operator on one event language. -/
def id (EventCode : Type uEvent) : EffectiveKernel EventCode EventCode where
  pullEvent event := .indicator event

@[simp]
theorem id_pullObservable {EventCode : Type uEvent}
    (observable : SimpleObservable EventCode) :
    (id EventCode).pullObservable observable = observable := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [pullObservable, ihLeft, ihRight]
  | scale coefficient observable ih => simp [pullObservable, ih]

/-- Compose Markov operators in execution order: first `outer`, then `inner`.
The corresponding expectation transformers compose in the reverse direction.
-/
def comp {MiddleCode : Type vEvent} {TargetCode : Type wEvent}
    (outer : EffectiveKernel SourceCode MiddleCode)
    (inner : EffectiveKernel MiddleCode TargetCode) :
    EffectiveKernel SourceCode TargetCode where
  pullEvent event := outer.pullObservable (inner.pullEvent event)

theorem pullObservable_comp {MiddleCode : Type vEvent} {TargetCode : Type wEvent}
    (outer : EffectiveKernel SourceCode MiddleCode)
    (inner : EffectiveKernel MiddleCode TargetCode)
    (observable : SimpleObservable TargetCode) :
    (outer.comp inner).pullObservable observable =
      outer.pullObservable (inner.pullObservable observable) := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [pullObservable, ihLeft, ihRight]
  | scale coefficient observable ih => simp [pullObservable, ih]

@[ext]
theorem ext {left right : EffectiveKernel SourceCode TargetCode}
    (hpull : ∀ event, left.pullEvent event = right.pullEvent event) :
    left = right := by
  cases left
  cases right
  congr
  funext event
  exact hpull event

/-- The identity transformer is a left identity for composition. -/
@[simp]
theorem id_comp {MiddleCode : Type vEvent}
    (kernel : EffectiveKernel SourceCode MiddleCode) :
    (id SourceCode).comp kernel = kernel := by
  apply EffectiveKernel.ext
  intro event
  exact id_pullObservable (kernel.pullEvent event)

/-- The identity transformer is a right identity for composition. -/
@[simp]
theorem comp_id (kernel : EffectiveKernel SourceCode TargetCode) :
    kernel.comp (id TargetCode) = kernel := by
  apply EffectiveKernel.ext
  intro event
  rfl

/-- Effective expectation-transformer composition is associative. -/
theorem comp_assoc {MiddleCode : Type vEvent} {TargetCode : Type wEvent}
    {FinalCode : Type*}
    (first : EffectiveKernel SourceCode MiddleCode)
    (second : EffectiveKernel MiddleCode TargetCode)
    (third : EffectiveKernel TargetCode FinalCode) :
    (first.comp second).comp third = first.comp (second.comp third) := by
  apply EffectiveKernel.ext
  intro event
  exact pullObservable_comp first second (third.pullEvent event)

/-- Deterministic map as a Markov operator. -/
def deterministic (mapping : EffectiveMap SourceCode TargetCode) :
    EffectiveKernel SourceCode TargetCode where
  pullEvent event := .indicator (mapping.preimage event)

end EffectiveKernel

namespace EffectiveLaw

/-- Bind an effective law through an effective Markov operator. -/
def bind {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (law : EffectiveLaw SourceCode)
    (kernel : EffectiveKernel SourceCode TargetCode) :
    EffectiveLaw TargetCode where
  mass event := law.expect (kernel.pullEvent event)

@[simp]
theorem bind_mass {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (law : EffectiveLaw SourceCode)
    (kernel : EffectiveKernel SourceCode TargetCode) (event : TargetCode) :
    (law.bind kernel).mass event = law.expect (kernel.pullEvent event) :=
  rfl

/-- Expectation under a bound law is source expectation after observable
pullback. -/
theorem bind_expect {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (law : EffectiveLaw SourceCode)
    (kernel : EffectiveKernel SourceCode TargetCode)
    (observable : SimpleObservable TargetCode) :
    (law.bind kernel).expect observable =
      law.expect (kernel.pullObservable observable) := by
  induction observable with
  | const => rfl
  | indicator => rfl
  | add left right ihLeft ihRight => simp [expect, EffectiveKernel.pullObservable,
      ihLeft, ihRight]
  | scale coefficient observable ih =>
      simp [expect, EffectiveKernel.pullObservable, ih]

/-- Sequential bind agrees with effective-kernel composition. -/
theorem bind_comp {SourceCode : Type uEvent} {MiddleCode : Type vEvent}
    {TargetCode : Type wEvent}
    (law : EffectiveLaw SourceCode)
    (outer : EffectiveKernel SourceCode MiddleCode)
    (inner : EffectiveKernel MiddleCode TargetCode) :
    (law.bind outer).bind inner = law.bind (outer.comp inner) := by
  apply EffectiveLaw.ext
  intro event
  exact bind_expect law outer (inner.pullEvent event)

/-- Binding through a deterministic effective map is its event-query
pushforward. -/
theorem bind_deterministic_eq_map
    {SourceCode : Type uEvent} {TargetCode : Type vEvent}
    (law : EffectiveLaw SourceCode)
    (mapping : EffectiveMap SourceCode TargetCode) :
    law.bind (EffectiveKernel.deterministic mapping) = law.map mapping :=
  rfl

end EffectiveLaw

end EffectiveProbability
